/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaymentMethodBankAccount,
  PaymentMethodBankAccount$inboundSchema,
} from "./payment-method-bank-account.js";

/**
 * The payment method type. If type is Check, then `split_by` and `splits` do not need to be populated. If type is Direct Deposit, `split_by` and `splits` are required.
 */
export const EmployeePaymentMethodType = {
  DirectDeposit: "Direct Deposit",
  Check: "Check",
} as const;
/**
 * The payment method type. If type is Check, then `split_by` and `splits` do not need to be populated. If type is Direct Deposit, `split_by` and `splits` are required.
 */
export type EmployeePaymentMethodType = OpenEnum<
  typeof EmployeePaymentMethodType
>;

export const EmployeePaymentMethodSplitBy = {
  Amount: "Amount",
  Percentage: "Percentage",
} as const;
export type EmployeePaymentMethodSplitBy = OpenEnum<
  typeof EmployeePaymentMethodSplitBy
>;

/**
 * Example response
 */
export type EmployeePaymentMethod = {
  /**
   * The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field.
   */
  version?: string | undefined;
  /**
   * The payment method type. If type is Check, then `split_by` and `splits` do not need to be populated. If type is Direct Deposit, `split_by` and `splits` are required.
   */
  type?: EmployeePaymentMethodType | undefined;
  /**
   * Describes how the payment will be split. If `split_by` is Percentage, then the split amounts must add up to exactly 100. If `split_by` is Amount, then the last split `amount` must be `null` to capture the remainder.
   */
  splitBy?: EmployeePaymentMethodSplitBy | null | undefined;
  splits?: Array<PaymentMethodBankAccount> | null | undefined;
};

/** @internal */
export const EmployeePaymentMethodType$inboundSchema: z.ZodMiniType<
  EmployeePaymentMethodType,
  unknown
> = openEnums.inboundSchema(EmployeePaymentMethodType);

/** @internal */
export const EmployeePaymentMethodSplitBy$inboundSchema: z.ZodMiniType<
  EmployeePaymentMethodSplitBy,
  unknown
> = openEnums.inboundSchema(EmployeePaymentMethodSplitBy);

/** @internal */
export const EmployeePaymentMethod$inboundSchema: z.ZodMiniType<
  EmployeePaymentMethod,
  unknown
> = z.pipe(
  z.object({
    version: types.optional(types.string()),
    type: types.optional(EmployeePaymentMethodType$inboundSchema),
    split_by: z.optional(
      z.nullable(EmployeePaymentMethodSplitBy$inboundSchema),
    ),
    splits: z.optional(
      z.nullable(z.array(PaymentMethodBankAccount$inboundSchema)),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "split_by": "splitBy",
    });
  }),
);

export function employeePaymentMethodFromJSON(
  jsonString: string,
): SafeParseResult<EmployeePaymentMethod, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmployeePaymentMethod$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmployeePaymentMethod' from JSON`,
  );
}
