/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * The employee's authorization status
 */
export const AuthorizationStatus = {
  Citizen: "citizen",
  Noncitizen: "noncitizen",
  PermanentResident: "permanent_resident",
  Alien: "alien",
} as const;
/**
 * The employee's authorization status
 */
export type AuthorizationStatus = OpenEnum<typeof AuthorizationStatus>;

/**
 * The document's document type
 */
export const I9AuthorizationDocumentType = {
  UscisAlienRegistrationNumber: "uscis_alien_registration_number",
  FormI94: "form_i94",
  ForeignPassport: "foreign_passport",
} as const;
/**
 * The document's document type
 */
export type I9AuthorizationDocumentType = OpenEnum<
  typeof I9AuthorizationDocumentType
>;

/**
 * An employee's I-9 authorization
 */
export type I9Authorization = {
  /**
   * The UUID of the I-9 authorization
   */
  uuid: string;
  /**
   * The UUID of the Form associated with this I-9 authorization. Use this with "Employee Forms" API endpoints.
   */
  formUuid?: string | null | undefined;
  /**
   * The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field.
   */
  version: string;
  /**
   * The employee's authorization status
   */
  authorizationStatus: AuthorizationStatus;
  /**
   * The document's document type
   */
  documentType?: I9AuthorizationDocumentType | null | undefined;
  /**
   * Whether or not a `document_number` exists for this document.
   */
  hasDocumentNumber?: boolean | null | undefined;
  /**
   * The document's expiration date
   */
  expirationDate?: string | null | undefined;
  /**
   * The document's country of issuance
   */
  country?: string | null | undefined;
  /**
   * Whether the employer has signed the Form I-9
   */
  employerSigned: boolean;
  /**
   * Whether the employee has signed the Form I-9
   */
  employeeSigned: boolean;
  /**
   * Any additional notes
   */
  additionalInfo?: string | null | undefined;
  /**
   * Whether an alternative procedure authorized by DHS to examine documents was used
   */
  altProcedure?: boolean | null | undefined;
};

/** @internal */
export const AuthorizationStatus$inboundSchema: z.ZodMiniType<
  AuthorizationStatus,
  unknown
> = openEnums.inboundSchema(AuthorizationStatus);

/** @internal */
export const I9AuthorizationDocumentType$inboundSchema: z.ZodMiniType<
  I9AuthorizationDocumentType,
  unknown
> = openEnums.inboundSchema(I9AuthorizationDocumentType);

/** @internal */
export const I9Authorization$inboundSchema: z.ZodMiniType<
  I9Authorization,
  unknown
> = z.pipe(
  z.object({
    uuid: types.string(),
    form_uuid: z.optional(z.nullable(types.string())),
    version: types.string(),
    authorization_status: AuthorizationStatus$inboundSchema,
    document_type: z.optional(
      z.nullable(I9AuthorizationDocumentType$inboundSchema),
    ),
    has_document_number: z.optional(z.nullable(types.boolean())),
    expiration_date: z.optional(z.nullable(types.string())),
    country: z.optional(z.nullable(types.string())),
    employer_signed: types.boolean(),
    employee_signed: types.boolean(),
    additional_info: z.optional(z.nullable(types.string())),
    alt_procedure: z.optional(z.nullable(types.boolean())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "form_uuid": "formUuid",
      "authorization_status": "authorizationStatus",
      "document_type": "documentType",
      "has_document_number": "hasDocumentNumber",
      "expiration_date": "expirationDate",
      "employer_signed": "employerSigned",
      "employee_signed": "employeeSigned",
      "additional_info": "additionalInfo",
      "alt_procedure": "altProcedure",
    });
  }),
);

export function i9AuthorizationFromJSON(
  jsonString: string,
): SafeParseResult<I9Authorization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => I9Authorization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'I9Authorization' from JSON`,
  );
}
