/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Splits = {
  bankAccountUuid: string;
  name: string;
  hiddenAccountNumber: string;
  encryptedAccountNumber?: string | null | undefined;
  routingNumber: string;
  priority: number;
  splitAmount: number;
  accountType: string;
};

export type ContractorPaymentDetailsList = {
  contractorUuid: string;
  paymentMethod: string;
  firstName?: string | undefined;
  lastName?: string | undefined;
  splitBy?: string | null | undefined;
  splits?: Array<Splits> | null | undefined;
};

/** @internal */
export const Splits$inboundSchema: z.ZodType<Splits, z.ZodTypeDef, unknown> = z
  .object({
    bank_account_uuid: z.string(),
    name: z.string(),
    hidden_account_number: z.string(),
    encrypted_account_number: z.nullable(z.string()).optional(),
    routing_number: z.string(),
    priority: z.number().int(),
    split_amount: z.number(),
    account_type: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "bank_account_uuid": "bankAccountUuid",
      "hidden_account_number": "hiddenAccountNumber",
      "encrypted_account_number": "encryptedAccountNumber",
      "routing_number": "routingNumber",
      "split_amount": "splitAmount",
      "account_type": "accountType",
    });
  });

/** @internal */
export type Splits$Outbound = {
  bank_account_uuid: string;
  name: string;
  hidden_account_number: string;
  encrypted_account_number?: string | null | undefined;
  routing_number: string;
  priority: number;
  split_amount: number;
  account_type: string;
};

/** @internal */
export const Splits$outboundSchema: z.ZodType<
  Splits$Outbound,
  z.ZodTypeDef,
  Splits
> = z.object({
  bankAccountUuid: z.string(),
  name: z.string(),
  hiddenAccountNumber: z.string(),
  encryptedAccountNumber: z.nullable(z.string()).optional(),
  routingNumber: z.string(),
  priority: z.number().int(),
  splitAmount: z.number(),
  accountType: z.string(),
}).transform((v) => {
  return remap$(v, {
    bankAccountUuid: "bank_account_uuid",
    hiddenAccountNumber: "hidden_account_number",
    encryptedAccountNumber: "encrypted_account_number",
    routingNumber: "routing_number",
    splitAmount: "split_amount",
    accountType: "account_type",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Splits$ {
  /** @deprecated use `Splits$inboundSchema` instead. */
  export const inboundSchema = Splits$inboundSchema;
  /** @deprecated use `Splits$outboundSchema` instead. */
  export const outboundSchema = Splits$outboundSchema;
  /** @deprecated use `Splits$Outbound` instead. */
  export type Outbound = Splits$Outbound;
}

export function splitsToJSON(splits: Splits): string {
  return JSON.stringify(Splits$outboundSchema.parse(splits));
}

export function splitsFromJSON(
  jsonString: string,
): SafeParseResult<Splits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Splits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Splits' from JSON`,
  );
}

/** @internal */
export const ContractorPaymentDetailsList$inboundSchema: z.ZodType<
  ContractorPaymentDetailsList,
  z.ZodTypeDef,
  unknown
> = z.object({
  contractor_uuid: z.string(),
  payment_method: z.string(),
  first_name: z.string().optional(),
  last_name: z.string().optional(),
  split_by: z.nullable(z.string()).optional(),
  splits: z.nullable(z.array(z.lazy(() => Splits$inboundSchema))).optional(),
}).transform((v) => {
  return remap$(v, {
    "contractor_uuid": "contractorUuid",
    "payment_method": "paymentMethod",
    "first_name": "firstName",
    "last_name": "lastName",
    "split_by": "splitBy",
  });
});

/** @internal */
export type ContractorPaymentDetailsList$Outbound = {
  contractor_uuid: string;
  payment_method: string;
  first_name?: string | undefined;
  last_name?: string | undefined;
  split_by?: string | null | undefined;
  splits?: Array<Splits$Outbound> | null | undefined;
};

/** @internal */
export const ContractorPaymentDetailsList$outboundSchema: z.ZodType<
  ContractorPaymentDetailsList$Outbound,
  z.ZodTypeDef,
  ContractorPaymentDetailsList
> = z.object({
  contractorUuid: z.string(),
  paymentMethod: z.string(),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  splitBy: z.nullable(z.string()).optional(),
  splits: z.nullable(z.array(z.lazy(() => Splits$outboundSchema))).optional(),
}).transform((v) => {
  return remap$(v, {
    contractorUuid: "contractor_uuid",
    paymentMethod: "payment_method",
    firstName: "first_name",
    lastName: "last_name",
    splitBy: "split_by",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ContractorPaymentDetailsList$ {
  /** @deprecated use `ContractorPaymentDetailsList$inboundSchema` instead. */
  export const inboundSchema = ContractorPaymentDetailsList$inboundSchema;
  /** @deprecated use `ContractorPaymentDetailsList$outboundSchema` instead. */
  export const outboundSchema = ContractorPaymentDetailsList$outboundSchema;
  /** @deprecated use `ContractorPaymentDetailsList$Outbound` instead. */
  export type Outbound = ContractorPaymentDetailsList$Outbound;
}

export function contractorPaymentDetailsListToJSON(
  contractorPaymentDetailsList: ContractorPaymentDetailsList,
): string {
  return JSON.stringify(
    ContractorPaymentDetailsList$outboundSchema.parse(
      contractorPaymentDetailsList,
    ),
  );
}

export function contractorPaymentDetailsListFromJSON(
  jsonString: string,
): SafeParseResult<ContractorPaymentDetailsList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContractorPaymentDetailsList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContractorPaymentDetailsList' from JSON`,
  );
}
