/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PayrollPayPeriodType = {
  /**
   * The start date, inclusive, of the pay period.
   */
  startDate?: string | undefined;
  /**
   * The start date, inclusive, of the pay period.
   */
  endDate?: string | undefined;
  /**
   * The UUID of the pay schedule for the payroll.
   */
  payScheduleUuid?: string | null | undefined;
};

/** @internal */
export const PayrollPayPeriodType$inboundSchema: z.ZodType<
  PayrollPayPeriodType,
  z.ZodTypeDef,
  unknown
> = z.object({
  start_date: z.string().optional(),
  end_date: z.string().optional(),
  pay_schedule_uuid: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "start_date": "startDate",
    "end_date": "endDate",
    "pay_schedule_uuid": "payScheduleUuid",
  });
});

/** @internal */
export type PayrollPayPeriodType$Outbound = {
  start_date?: string | undefined;
  end_date?: string | undefined;
  pay_schedule_uuid?: string | null | undefined;
};

/** @internal */
export const PayrollPayPeriodType$outboundSchema: z.ZodType<
  PayrollPayPeriodType$Outbound,
  z.ZodTypeDef,
  PayrollPayPeriodType
> = z.object({
  startDate: z.string().optional(),
  endDate: z.string().optional(),
  payScheduleUuid: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    startDate: "start_date",
    endDate: "end_date",
    payScheduleUuid: "pay_schedule_uuid",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayrollPayPeriodType$ {
  /** @deprecated use `PayrollPayPeriodType$inboundSchema` instead. */
  export const inboundSchema = PayrollPayPeriodType$inboundSchema;
  /** @deprecated use `PayrollPayPeriodType$outboundSchema` instead. */
  export const outboundSchema = PayrollPayPeriodType$outboundSchema;
  /** @deprecated use `PayrollPayPeriodType$Outbound` instead. */
  export type Outbound = PayrollPayPeriodType$Outbound;
}

export function payrollPayPeriodTypeToJSON(
  payrollPayPeriodType: PayrollPayPeriodType,
): string {
  return JSON.stringify(
    PayrollPayPeriodType$outboundSchema.parse(payrollPayPeriodType),
  );
}

export function payrollPayPeriodTypeFromJSON(
  jsonString: string,
): SafeParseResult<PayrollPayPeriodType, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayrollPayPeriodType$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayrollPayPeriodType' from JSON`,
  );
}
