/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export const GetV1CompaniesCompanyIdEmployeesPaymentDetailsXGustoAPIVersion = {
  TwoThousandAndTwentyFiveMinus11Minus15: "2025-11-15",
} as const;
/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export type GetV1CompaniesCompanyIdEmployeesPaymentDetailsXGustoAPIVersion =
  ClosedEnum<
    typeof GetV1CompaniesCompanyIdEmployeesPaymentDetailsXGustoAPIVersion
  >;

export type GetV1CompaniesCompanyIdEmployeesPaymentDetailsRequest = {
  /**
   * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
   */
  xGustoAPIVersion?:
    | GetV1CompaniesCompanyIdEmployeesPaymentDetailsXGustoAPIVersion
    | undefined;
  /**
   * The UUID of the company
   */
  companyId: string;
  /**
   * The UUID of a specific employee to fetch payment details for.
   */
  employeeUuid?: string | undefined;
  /**
   * The UUID of a specific payroll to fetch payment details for employees on that payroll.
   */
  payrollUuid?: string | undefined;
  /**
   * The page that is requested. When unspecified, will load all objects unless endpoint forces pagination.
   */
  page?: number | undefined;
  /**
   * Number of objects per page. For majority of endpoints will default to 25
   */
  per?: number | undefined;
};

/** @internal */
export const GetV1CompaniesCompanyIdEmployeesPaymentDetailsXGustoAPIVersion$outboundSchema:
  z.ZodMiniEnum<
    typeof GetV1CompaniesCompanyIdEmployeesPaymentDetailsXGustoAPIVersion
  > = z.enum(GetV1CompaniesCompanyIdEmployeesPaymentDetailsXGustoAPIVersion);

/** @internal */
export type GetV1CompaniesCompanyIdEmployeesPaymentDetailsRequest$Outbound = {
  "X-Gusto-API-Version": string;
  company_id: string;
  employee_uuid?: string | undefined;
  payroll_uuid?: string | undefined;
  page?: number | undefined;
  per?: number | undefined;
};

/** @internal */
export const GetV1CompaniesCompanyIdEmployeesPaymentDetailsRequest$outboundSchema:
  z.ZodMiniType<
    GetV1CompaniesCompanyIdEmployeesPaymentDetailsRequest$Outbound,
    GetV1CompaniesCompanyIdEmployeesPaymentDetailsRequest
  > = z.pipe(
    z.object({
      xGustoAPIVersion: z._default(
        GetV1CompaniesCompanyIdEmployeesPaymentDetailsXGustoAPIVersion$outboundSchema,
        "2025-11-15",
      ),
      companyId: z.string(),
      employeeUuid: z.optional(z.string()),
      payrollUuid: z.optional(z.string()),
      page: z.optional(z.int()),
      per: z.optional(z.int()),
    }),
    z.transform((v) => {
      return remap$(v, {
        xGustoAPIVersion: "X-Gusto-API-Version",
        companyId: "company_id",
        employeeUuid: "employee_uuid",
        payrollUuid: "payroll_uuid",
      });
    }),
  );

export function getV1CompaniesCompanyIdEmployeesPaymentDetailsRequestToJSON(
  getV1CompaniesCompanyIdEmployeesPaymentDetailsRequest:
    GetV1CompaniesCompanyIdEmployeesPaymentDetailsRequest,
): string {
  return JSON.stringify(
    GetV1CompaniesCompanyIdEmployeesPaymentDetailsRequest$outboundSchema.parse(
      getV1CompaniesCompanyIdEmployeesPaymentDetailsRequest,
    ),
  );
}
