/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export const GetV1ContractorPaymentsContractorPaymentIdPdfXGustoAPIVersion = {
  TwoThousandAndTwentyFiveMinus11Minus15: "2025-11-15",
} as const;
/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export type GetV1ContractorPaymentsContractorPaymentIdPdfXGustoAPIVersion =
  ClosedEnum<
    typeof GetV1ContractorPaymentsContractorPaymentIdPdfXGustoAPIVersion
  >;

export type GetV1ContractorPaymentsContractorPaymentIdPdfRequest = {
  /**
   * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
   */
  xGustoAPIVersion?:
    | GetV1ContractorPaymentsContractorPaymentIdPdfXGustoAPIVersion
    | undefined;
  /**
   * The UUID of the contractor payment
   */
  contractorPaymentId: string;
};

/** @internal */
export const GetV1ContractorPaymentsContractorPaymentIdPdfXGustoAPIVersion$outboundSchema:
  z.ZodMiniEnum<
    typeof GetV1ContractorPaymentsContractorPaymentIdPdfXGustoAPIVersion
  > = z.enum(GetV1ContractorPaymentsContractorPaymentIdPdfXGustoAPIVersion);

/** @internal */
export type GetV1ContractorPaymentsContractorPaymentIdPdfRequest$Outbound = {
  "X-Gusto-API-Version": string;
  contractor_payment_id: string;
};

/** @internal */
export const GetV1ContractorPaymentsContractorPaymentIdPdfRequest$outboundSchema:
  z.ZodMiniType<
    GetV1ContractorPaymentsContractorPaymentIdPdfRequest$Outbound,
    GetV1ContractorPaymentsContractorPaymentIdPdfRequest
  > = z.pipe(
    z.object({
      xGustoAPIVersion: z._default(
        GetV1ContractorPaymentsContractorPaymentIdPdfXGustoAPIVersion$outboundSchema,
        "2025-11-15",
      ),
      contractorPaymentId: z.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        xGustoAPIVersion: "X-Gusto-API-Version",
        contractorPaymentId: "contractor_payment_id",
      });
    }),
  );

export function getV1ContractorPaymentsContractorPaymentIdPdfRequestToJSON(
  getV1ContractorPaymentsContractorPaymentIdPdfRequest:
    GetV1ContractorPaymentsContractorPaymentIdPdfRequest,
): string {
  return JSON.stringify(
    GetV1ContractorPaymentsContractorPaymentIdPdfRequest$outboundSchema.parse(
      getV1ContractorPaymentsContractorPaymentIdPdfRequest,
    ),
  );
}
