/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { RFCDate } from "../../types/rfcdate.js";
import {
  HTTPMetadata,
  HTTPMetadata$inboundSchema,
} from "../components/httpmetadata.js";
import {
  TaxPayment,
  TaxPayment$inboundSchema,
} from "../components/taxpayment.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export const GetTaxPaymentsHeaderXGustoAPIVersion = {
  TwoThousandAndTwentyFiveMinus11Minus15: "2025-11-15",
} as const;
/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export type GetTaxPaymentsHeaderXGustoAPIVersion = ClosedEnum<
  typeof GetTaxPaymentsHeaderXGustoAPIVersion
>;

export type GetTaxPaymentsRequest = {
  /**
   * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
   */
  xGustoAPIVersion?: GetTaxPaymentsHeaderXGustoAPIVersion | undefined;
  /**
   * The UUID of the company
   */
  companyUuid: string;
  /**
   * Filter by tax jurisdiction. Accepts one or more two-letter state codes, or `US` for federal, as a comma-separated list (e.g. `IL,CA`). Codes are case-insensitive.
   */
  jurisdiction?: Array<string> | undefined;
  /**
   * Lower-bound (inclusive) date filter on due_date.
   */
  dueDateFrom?: RFCDate | undefined;
  /**
   * Upper-bound (inclusive) date filter on due_date.
   */
  dueDateTo?: RFCDate | undefined;
  /**
   * Lower-bound (inclusive) date filter on payment_sent_on.
   */
  paymentSentOnFrom?: RFCDate | undefined;
  /**
   * Upper-bound (inclusive) date filter on payment_sent_on.
   */
  paymentSentOnTo?: RFCDate | undefined;
  /**
   * Lower-bound (inclusive) date filter on period_start.
   */
  periodStartFrom?: RFCDate | undefined;
  /**
   * Upper-bound (inclusive) date filter on period_start.
   */
  periodStartTo?: RFCDate | undefined;
  /**
   * Lower-bound (inclusive) date filter on period_end.
   */
  periodEndFrom?: RFCDate | undefined;
  /**
   * Upper-bound (inclusive) date filter on period_end.
   */
  periodEndTo?: RFCDate | undefined;
  /**
   * Lower-bound (inclusive) filter on amount.
   */
  amountMin?: number | undefined;
  /**
   * Upper-bound (inclusive) filter on amount.
   */
  amountMax?: number | undefined;
  /**
   * Sort by one or more fields. Options: amount, due_date, payment_sent_on, period_end, period_start. Append `:asc` or `:desc` to specify direction (e.g., `amount:asc`). Defaults to ascending.
   */
  sortBy?: string | undefined;
  /**
   * The page that is requested. When unspecified, will load all objects unless endpoint forces pagination.
   */
  page?: number | undefined;
  /**
   * Number of objects per page. For majority of endpoints will default to 25
   */
  per?: number | undefined;
};

export type GetTaxPaymentsResponse = {
  httpMeta: HTTPMetadata;
  /**
   * Success
   */
  taxPaymentList?: Array<TaxPayment> | undefined;
};

/** @internal */
export const GetTaxPaymentsHeaderXGustoAPIVersion$outboundSchema:
  z.ZodNativeEnum<typeof GetTaxPaymentsHeaderXGustoAPIVersion> = z.nativeEnum(
    GetTaxPaymentsHeaderXGustoAPIVersion,
  );

/** @internal */
export type GetTaxPaymentsRequest$Outbound = {
  "X-Gusto-API-Version": string;
  company_uuid: string;
  jurisdiction?: Array<string> | undefined;
  due_date_from?: string | undefined;
  due_date_to?: string | undefined;
  payment_sent_on_from?: string | undefined;
  payment_sent_on_to?: string | undefined;
  period_start_from?: string | undefined;
  period_start_to?: string | undefined;
  period_end_from?: string | undefined;
  period_end_to?: string | undefined;
  amount_min?: number | undefined;
  amount_max?: number | undefined;
  sort_by?: string | undefined;
  page?: number | undefined;
  per?: number | undefined;
};

/** @internal */
export const GetTaxPaymentsRequest$outboundSchema: z.ZodType<
  GetTaxPaymentsRequest$Outbound,
  z.ZodTypeDef,
  GetTaxPaymentsRequest
> = z.object({
  xGustoAPIVersion: GetTaxPaymentsHeaderXGustoAPIVersion$outboundSchema.default(
    "2025-11-15",
  ),
  companyUuid: z.string(),
  jurisdiction: z.array(z.string()).optional(),
  dueDateFrom: z.instanceof(RFCDate).transform(v => v.toString()).optional(),
  dueDateTo: z.instanceof(RFCDate).transform(v => v.toString()).optional(),
  paymentSentOnFrom: z.instanceof(RFCDate).transform(v => v.toString())
    .optional(),
  paymentSentOnTo: z.instanceof(RFCDate).transform(v => v.toString())
    .optional(),
  periodStartFrom: z.instanceof(RFCDate).transform(v => v.toString())
    .optional(),
  periodStartTo: z.instanceof(RFCDate).transform(v => v.toString()).optional(),
  periodEndFrom: z.instanceof(RFCDate).transform(v => v.toString()).optional(),
  periodEndTo: z.instanceof(RFCDate).transform(v => v.toString()).optional(),
  amountMin: z.number().optional(),
  amountMax: z.number().optional(),
  sortBy: z.string().optional(),
  page: z.number().int().optional(),
  per: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    xGustoAPIVersion: "X-Gusto-API-Version",
    companyUuid: "company_uuid",
    dueDateFrom: "due_date_from",
    dueDateTo: "due_date_to",
    paymentSentOnFrom: "payment_sent_on_from",
    paymentSentOnTo: "payment_sent_on_to",
    periodStartFrom: "period_start_from",
    periodStartTo: "period_start_to",
    periodEndFrom: "period_end_from",
    periodEndTo: "period_end_to",
    amountMin: "amount_min",
    amountMax: "amount_max",
    sortBy: "sort_by",
  });
});

export function getTaxPaymentsRequestToJSON(
  getTaxPaymentsRequest: GetTaxPaymentsRequest,
): string {
  return JSON.stringify(
    GetTaxPaymentsRequest$outboundSchema.parse(getTaxPaymentsRequest),
  );
}

/** @internal */
export const GetTaxPaymentsResponse$inboundSchema: z.ZodType<
  GetTaxPaymentsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: HTTPMetadata$inboundSchema,
  "Tax-Payment-List": z.array(TaxPayment$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "Tax-Payment-List": "taxPaymentList",
  });
});

export function getTaxPaymentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetTaxPaymentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTaxPaymentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTaxPaymentsResponse' from JSON`,
  );
}
