/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  Garnishment,
  Garnishment$inboundSchema,
} from "../components/garnishment.js";
import {
  HTTPMetadata,
  HTTPMetadata$inboundSchema,
} from "../components/httpmetadata.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export const GetV1EmployeesEmployeeIdGarnishmentsHeaderXGustoAPIVersion = {
  TwoThousandAndTwentyFiveMinus11Minus15: "2025-11-15",
} as const;
/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export type GetV1EmployeesEmployeeIdGarnishmentsHeaderXGustoAPIVersion =
  ClosedEnum<typeof GetV1EmployeesEmployeeIdGarnishmentsHeaderXGustoAPIVersion>;

export type GetV1EmployeesEmployeeIdGarnishmentsRequest = {
  /**
   * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
   */
  xGustoAPIVersion?:
    | GetV1EmployeesEmployeeIdGarnishmentsHeaderXGustoAPIVersion
    | undefined;
  /**
   * The UUID of the employee
   */
  employeeId: string;
  /**
   * The page that is requested. When unspecified, will load all objects unless endpoint forces pagination.
   */
  page?: number | undefined;
  /**
   * Number of objects per page. For majority of endpoints will default to 25
   */
  per?: number | undefined;
};

export type GetV1EmployeesEmployeeIdGarnishmentsResponse = {
  httpMeta: HTTPMetadata;
  /**
   * Example response
   */
  garnishments?: Array<Garnishment> | undefined;
};

/** @internal */
export const GetV1EmployeesEmployeeIdGarnishmentsHeaderXGustoAPIVersion$outboundSchema:
  z.ZodNativeEnum<
    typeof GetV1EmployeesEmployeeIdGarnishmentsHeaderXGustoAPIVersion
  > = z.nativeEnum(GetV1EmployeesEmployeeIdGarnishmentsHeaderXGustoAPIVersion);

/** @internal */
export type GetV1EmployeesEmployeeIdGarnishmentsRequest$Outbound = {
  "X-Gusto-API-Version": string;
  employee_id: string;
  page?: number | undefined;
  per?: number | undefined;
};

/** @internal */
export const GetV1EmployeesEmployeeIdGarnishmentsRequest$outboundSchema:
  z.ZodType<
    GetV1EmployeesEmployeeIdGarnishmentsRequest$Outbound,
    z.ZodTypeDef,
    GetV1EmployeesEmployeeIdGarnishmentsRequest
  > = z.object({
    xGustoAPIVersion:
      GetV1EmployeesEmployeeIdGarnishmentsHeaderXGustoAPIVersion$outboundSchema
        .default("2025-11-15"),
    employeeId: z.string(),
    page: z.number().int().optional(),
    per: z.number().int().optional(),
  }).transform((v) => {
    return remap$(v, {
      xGustoAPIVersion: "X-Gusto-API-Version",
      employeeId: "employee_id",
    });
  });

export function getV1EmployeesEmployeeIdGarnishmentsRequestToJSON(
  getV1EmployeesEmployeeIdGarnishmentsRequest:
    GetV1EmployeesEmployeeIdGarnishmentsRequest,
): string {
  return JSON.stringify(
    GetV1EmployeesEmployeeIdGarnishmentsRequest$outboundSchema.parse(
      getV1EmployeesEmployeeIdGarnishmentsRequest,
    ),
  );
}

/** @internal */
export const GetV1EmployeesEmployeeIdGarnishmentsResponse$inboundSchema:
  z.ZodType<
    GetV1EmployeesEmployeeIdGarnishmentsResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    HttpMeta: HTTPMetadata$inboundSchema,
    Garnishments: z.array(Garnishment$inboundSchema).optional(),
  }).transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "Garnishments": "garnishments",
    });
  });

export function getV1EmployeesEmployeeIdGarnishmentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1EmployeesEmployeeIdGarnishmentsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1EmployeesEmployeeIdGarnishmentsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1EmployeesEmployeeIdGarnishmentsResponse' from JSON`,
  );
}
