/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as models from "../index.js";

/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export const PostV1CompaniesCompanyIdCompanyBenefitsXGustoAPIVersion = {
  TwoThousandAndTwentyFiveMinus11Minus15: "2025-11-15",
} as const;
/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export type PostV1CompaniesCompanyIdCompanyBenefitsXGustoAPIVersion =
  ClosedEnum<typeof PostV1CompaniesCompanyIdCompanyBenefitsXGustoAPIVersion>;

export type PostV1CompaniesCompanyIdCompanyBenefitsRequest = {
  /**
   * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
   */
  xGustoAPIVersion?:
    | PostV1CompaniesCompanyIdCompanyBenefitsXGustoAPIVersion
    | undefined;
  /**
   * The UUID of the company
   */
  companyId: string;
  body: models.CompanyBenefitCreateRequest;
};

/** @internal */
export const PostV1CompaniesCompanyIdCompanyBenefitsXGustoAPIVersion$outboundSchema:
  z.ZodMiniEnum<
    typeof PostV1CompaniesCompanyIdCompanyBenefitsXGustoAPIVersion
  > = z.enum(PostV1CompaniesCompanyIdCompanyBenefitsXGustoAPIVersion);

/** @internal */
export type PostV1CompaniesCompanyIdCompanyBenefitsRequest$Outbound = {
  "X-Gusto-API-Version": string;
  company_id: string;
  body: models.CompanyBenefitCreateRequest$Outbound;
};

/** @internal */
export const PostV1CompaniesCompanyIdCompanyBenefitsRequest$outboundSchema:
  z.ZodMiniType<
    PostV1CompaniesCompanyIdCompanyBenefitsRequest$Outbound,
    PostV1CompaniesCompanyIdCompanyBenefitsRequest
  > = z.pipe(
    z.object({
      xGustoAPIVersion: z._default(
        PostV1CompaniesCompanyIdCompanyBenefitsXGustoAPIVersion$outboundSchema,
        "2025-11-15",
      ),
      companyId: z.string(),
      body: models.CompanyBenefitCreateRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        xGustoAPIVersion: "X-Gusto-API-Version",
        companyId: "company_id",
      });
    }),
  );

export function postV1CompaniesCompanyIdCompanyBenefitsRequestToJSON(
  postV1CompaniesCompanyIdCompanyBenefitsRequest:
    PostV1CompaniesCompanyIdCompanyBenefitsRequest,
): string {
  return JSON.stringify(
    PostV1CompaniesCompanyIdCompanyBenefitsRequest$outboundSchema.parse(
      postV1CompaniesCompanyIdCompanyBenefitsRequest,
    ),
  );
}
