/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as models from "../index.js";

/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export const PutV1PartnerManagedCompaniesCompanyUuidMigrateXGustoAPIVersion = {
  TwoThousandAndTwentyFiveMinus11Minus15: "2025-11-15",
} as const;
/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export type PutV1PartnerManagedCompaniesCompanyUuidMigrateXGustoAPIVersion =
  ClosedEnum<
    typeof PutV1PartnerManagedCompaniesCompanyUuidMigrateXGustoAPIVersion
  >;

export type PutV1PartnerManagedCompaniesCompanyUuidMigrateRequest = {
  /**
   * The UUID of the company
   */
  companyUuid: string;
  /**
   * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
   */
  xGustoAPIVersion?:
    | PutV1PartnerManagedCompaniesCompanyUuidMigrateXGustoAPIVersion
    | undefined;
  body: models.PartnerManagedCompanyMigrateRequest;
};

/** @internal */
export const PutV1PartnerManagedCompaniesCompanyUuidMigrateXGustoAPIVersion$outboundSchema:
  z.ZodMiniEnum<
    typeof PutV1PartnerManagedCompaniesCompanyUuidMigrateXGustoAPIVersion
  > = z.enum(PutV1PartnerManagedCompaniesCompanyUuidMigrateXGustoAPIVersion);

/** @internal */
export type PutV1PartnerManagedCompaniesCompanyUuidMigrateRequest$Outbound = {
  company_uuid: string;
  "X-Gusto-API-Version": string;
  body: models.PartnerManagedCompanyMigrateRequest$Outbound;
};

/** @internal */
export const PutV1PartnerManagedCompaniesCompanyUuidMigrateRequest$outboundSchema:
  z.ZodMiniType<
    PutV1PartnerManagedCompaniesCompanyUuidMigrateRequest$Outbound,
    PutV1PartnerManagedCompaniesCompanyUuidMigrateRequest
  > = z.pipe(
    z.object({
      companyUuid: z.string(),
      xGustoAPIVersion: z._default(
        PutV1PartnerManagedCompaniesCompanyUuidMigrateXGustoAPIVersion$outboundSchema,
        "2025-11-15",
      ),
      body: models.PartnerManagedCompanyMigrateRequest$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        companyUuid: "company_uuid",
        xGustoAPIVersion: "X-Gusto-API-Version",
      });
    }),
  );

export function putV1PartnerManagedCompaniesCompanyUuidMigrateRequestToJSON(
  putV1PartnerManagedCompaniesCompanyUuidMigrateRequest:
    PutV1PartnerManagedCompaniesCompanyUuidMigrateRequest,
): string {
  return JSON.stringify(
    PutV1PartnerManagedCompaniesCompanyUuidMigrateRequest$outboundSchema.parse(
      putV1PartnerManagedCompaniesCompanyUuidMigrateRequest,
    ),
  );
}
