/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as models from "../index.js";

/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export const PutV1CompaniesCompanyUuidTaxRequirementsStateXGustoAPIVersion = {
  TwoThousandAndTwentyFiveMinus11Minus15: "2025-11-15",
} as const;
/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export type PutV1CompaniesCompanyUuidTaxRequirementsStateXGustoAPIVersion =
  ClosedEnum<
    typeof PutV1CompaniesCompanyUuidTaxRequirementsStateXGustoAPIVersion
  >;

export type PutV1CompaniesCompanyUuidTaxRequirementsStateRequestBody = {
  /**
   * Array of requirement sets to update. Each set corresponds to a category of requirements for the state.
   */
  requirementSets?: Array<models.TaxRequirementSetUpdate> | undefined;
};

export type PutV1CompaniesCompanyUuidTaxRequirementsStateRequest = {
  /**
   * The UUID of the company
   */
  companyUuid: string;
  /**
   * The two-letter state abbreviation
   */
  state: string;
  /**
   * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
   */
  xGustoAPIVersion?:
    | PutV1CompaniesCompanyUuidTaxRequirementsStateXGustoAPIVersion
    | undefined;
  body: PutV1CompaniesCompanyUuidTaxRequirementsStateRequestBody;
};

/** @internal */
export const PutV1CompaniesCompanyUuidTaxRequirementsStateXGustoAPIVersion$outboundSchema:
  z.ZodMiniEnum<
    typeof PutV1CompaniesCompanyUuidTaxRequirementsStateXGustoAPIVersion
  > = z.enum(PutV1CompaniesCompanyUuidTaxRequirementsStateXGustoAPIVersion);

/** @internal */
export type PutV1CompaniesCompanyUuidTaxRequirementsStateRequestBody$Outbound =
  {
    requirement_sets?:
      | Array<models.TaxRequirementSetUpdate$Outbound>
      | undefined;
  };

/** @internal */
export const PutV1CompaniesCompanyUuidTaxRequirementsStateRequestBody$outboundSchema:
  z.ZodMiniType<
    PutV1CompaniesCompanyUuidTaxRequirementsStateRequestBody$Outbound,
    PutV1CompaniesCompanyUuidTaxRequirementsStateRequestBody
  > = z.pipe(
    z.object({
      requirementSets: z.optional(
        z.array(models.TaxRequirementSetUpdate$outboundSchema),
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        requirementSets: "requirement_sets",
      });
    }),
  );

export function putV1CompaniesCompanyUuidTaxRequirementsStateRequestBodyToJSON(
  putV1CompaniesCompanyUuidTaxRequirementsStateRequestBody:
    PutV1CompaniesCompanyUuidTaxRequirementsStateRequestBody,
): string {
  return JSON.stringify(
    PutV1CompaniesCompanyUuidTaxRequirementsStateRequestBody$outboundSchema
      .parse(putV1CompaniesCompanyUuidTaxRequirementsStateRequestBody),
  );
}

/** @internal */
export type PutV1CompaniesCompanyUuidTaxRequirementsStateRequest$Outbound = {
  company_uuid: string;
  state: string;
  "X-Gusto-API-Version": string;
  body: PutV1CompaniesCompanyUuidTaxRequirementsStateRequestBody$Outbound;
};

/** @internal */
export const PutV1CompaniesCompanyUuidTaxRequirementsStateRequest$outboundSchema:
  z.ZodMiniType<
    PutV1CompaniesCompanyUuidTaxRequirementsStateRequest$Outbound,
    PutV1CompaniesCompanyUuidTaxRequirementsStateRequest
  > = z.pipe(
    z.object({
      companyUuid: z.string(),
      state: z.string(),
      xGustoAPIVersion: z._default(
        PutV1CompaniesCompanyUuidTaxRequirementsStateXGustoAPIVersion$outboundSchema,
        "2025-11-15",
      ),
      body: z.lazy(() =>
        PutV1CompaniesCompanyUuidTaxRequirementsStateRequestBody$outboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        companyUuid: "company_uuid",
        xGustoAPIVersion: "X-Gusto-API-Version",
      });
    }),
  );

export function putV1CompaniesCompanyUuidTaxRequirementsStateRequestToJSON(
  putV1CompaniesCompanyUuidTaxRequirementsStateRequest:
    PutV1CompaniesCompanyUuidTaxRequirementsStateRequest,
): string {
  return JSON.stringify(
    PutV1CompaniesCompanyUuidTaxRequirementsStateRequest$outboundSchema.parse(
      putV1CompaniesCompanyUuidTaxRequirementsStateRequest,
    ),
  );
}
