/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export const PutV1TimeOffRequestsTimeOffRequestUuidDeclineXGustoAPIVersion = {
  TwoThousandAndTwentyFiveMinus11Minus15: "2025-11-15",
} as const;
/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export type PutV1TimeOffRequestsTimeOffRequestUuidDeclineXGustoAPIVersion =
  ClosedEnum<
    typeof PutV1TimeOffRequestsTimeOffRequestUuidDeclineXGustoAPIVersion
  >;

export type PutV1TimeOffRequestsTimeOffRequestUuidDeclineRequestBody = {
  /**
   * Note explaining why the request was declined
   */
  employerNote: string;
  /**
   * The UUID of the admin declining the request. Defaults to the company's primary payroll admin.
   */
  approverUuid?: string | undefined;
};

export type PutV1TimeOffRequestsTimeOffRequestUuidDeclineRequest = {
  /**
   * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
   */
  xGustoAPIVersion?:
    | PutV1TimeOffRequestsTimeOffRequestUuidDeclineXGustoAPIVersion
    | undefined;
  /**
   * The UUID of the time off request
   */
  timeOffRequestUuid: string;
  body: PutV1TimeOffRequestsTimeOffRequestUuidDeclineRequestBody;
};

/** @internal */
export const PutV1TimeOffRequestsTimeOffRequestUuidDeclineXGustoAPIVersion$outboundSchema:
  z.ZodMiniEnum<
    typeof PutV1TimeOffRequestsTimeOffRequestUuidDeclineXGustoAPIVersion
  > = z.enum(PutV1TimeOffRequestsTimeOffRequestUuidDeclineXGustoAPIVersion);

/** @internal */
export type PutV1TimeOffRequestsTimeOffRequestUuidDeclineRequestBody$Outbound =
  {
    employer_note: string;
    approver_uuid?: string | undefined;
  };

/** @internal */
export const PutV1TimeOffRequestsTimeOffRequestUuidDeclineRequestBody$outboundSchema:
  z.ZodMiniType<
    PutV1TimeOffRequestsTimeOffRequestUuidDeclineRequestBody$Outbound,
    PutV1TimeOffRequestsTimeOffRequestUuidDeclineRequestBody
  > = z.pipe(
    z.object({
      employerNote: z.string(),
      approverUuid: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        employerNote: "employer_note",
        approverUuid: "approver_uuid",
      });
    }),
  );

export function putV1TimeOffRequestsTimeOffRequestUuidDeclineRequestBodyToJSON(
  putV1TimeOffRequestsTimeOffRequestUuidDeclineRequestBody:
    PutV1TimeOffRequestsTimeOffRequestUuidDeclineRequestBody,
): string {
  return JSON.stringify(
    PutV1TimeOffRequestsTimeOffRequestUuidDeclineRequestBody$outboundSchema
      .parse(putV1TimeOffRequestsTimeOffRequestUuidDeclineRequestBody),
  );
}

/** @internal */
export type PutV1TimeOffRequestsTimeOffRequestUuidDeclineRequest$Outbound = {
  "X-Gusto-API-Version": string;
  time_off_request_uuid: string;
  body: PutV1TimeOffRequestsTimeOffRequestUuidDeclineRequestBody$Outbound;
};

/** @internal */
export const PutV1TimeOffRequestsTimeOffRequestUuidDeclineRequest$outboundSchema:
  z.ZodMiniType<
    PutV1TimeOffRequestsTimeOffRequestUuidDeclineRequest$Outbound,
    PutV1TimeOffRequestsTimeOffRequestUuidDeclineRequest
  > = z.pipe(
    z.object({
      xGustoAPIVersion: z._default(
        PutV1TimeOffRequestsTimeOffRequestUuidDeclineXGustoAPIVersion$outboundSchema,
        "2025-11-15",
      ),
      timeOffRequestUuid: z.string(),
      body: z.lazy(() =>
        PutV1TimeOffRequestsTimeOffRequestUuidDeclineRequestBody$outboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        xGustoAPIVersion: "X-Gusto-API-Version",
        timeOffRequestUuid: "time_off_request_uuid",
      });
    }),
  );

export function putV1TimeOffRequestsTimeOffRequestUuidDeclineRequestToJSON(
  putV1TimeOffRequestsTimeOffRequestUuidDeclineRequest:
    PutV1TimeOffRequestsTimeOffRequestUuidDeclineRequest,
): string {
  return JSON.stringify(
    PutV1TimeOffRequestsTimeOffRequestUuidDeclineRequest$outboundSchema.parse(
      putV1TimeOffRequestsTimeOffRequestUuidDeclineRequest,
    ),
  );
}
