"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Benefits = void 0;
const companiesBenefitsList_js_1 = require("../funcs/companiesBenefitsList.js");
const sdks_js_1 = require("../lib/sdks.js");
const fp_js_1 = require("../types/fp.js");
class Benefits extends sdks_js_1.ClientSDK {
    /**
     * Get benefits for a company
     *
     * @remarks
     * Company benefits represent the benefits that a company is offering to employees. This ties together a particular supported benefit with the company-specific information for the offering of that benefit.
     *
     * Note that company benefits can be deactivated only when no employees are enrolled.
     *
     * Benefits containing PHI are only visible to applications with the `company_benefits:read:phi` scope.
     *
     * scope: `company_benefits:read`
     */
    async list(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, companiesBenefitsList_js_1.companiesBenefitsList)(this, request, options));
    }
}
exports.Benefits = Benefits;
//# sourceMappingURL=benefits.js.map