"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CompanyAttachment = void 0;
const companyAttachmentGetDownloadUrl_js_1 = require("../funcs/companyAttachmentGetDownloadUrl.js");
const sdks_js_1 = require("../lib/sdks.js");
const fp_js_1 = require("../types/fp.js");
class CompanyAttachment extends sdks_js_1.ClientSDK {
    /**
     * Get a temporary url to download the Company Attachment file
     *
     * @remarks
     * Retrieve a temporary url to download a attachment file uploaded
     * by the company.
     *
     * scope: `company_attachments:read`
     */
    async getDownloadUrl(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, companyAttachmentGetDownloadUrl_js_1.companyAttachmentGetDownloadUrl)(this, request, options));
    }
}
exports.CompanyAttachment = CompanyAttachment;
//# sourceMappingURL=companyattachment.js.map