"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EmployeeBenefits = void 0;
const employeeBenefitsCreate_js_1 = require("../funcs/employeeBenefitsCreate.js");
const employeeBenefitsCreateYtdBenefitAmountsFromDifferentCompany_js_1 = require("../funcs/employeeBenefitsCreateYtdBenefitAmountsFromDifferentCompany.js");
const employeeBenefitsDelete_js_1 = require("../funcs/employeeBenefitsDelete.js");
const employeeBenefitsGet_js_1 = require("../funcs/employeeBenefitsGet.js");
const employeeBenefitsGetYtdBenefitAmountsFromDifferentCompany_js_1 = require("../funcs/employeeBenefitsGetYtdBenefitAmountsFromDifferentCompany.js");
const employeeBenefitsRetrieve_js_1 = require("../funcs/employeeBenefitsRetrieve.js");
const employeeBenefitsUpdate_js_1 = require("../funcs/employeeBenefitsUpdate.js");
const sdks_js_1 = require("../lib/sdks.js");
const fp_js_1 = require("../types/fp.js");
class EmployeeBenefits extends sdks_js_1.ClientSDK {
    /**
     * Create an employee benefit
     *
     * @remarks
     * Employee benefits represent an employee enrolled in a particular company benefit. It includes information specific to that employee’s enrollment.
     *
     * scope: `employee_benefits:write`
     */
    async create(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, employeeBenefitsCreate_js_1.employeeBenefitsCreate)(this, request, options));
    }
    /**
     * Get all benefits for an employee
     *
     * @remarks
     * Employee benefits represent an employee enrolled in a particular company benefit. It includes information specific to that employee’s enrollment.
     *
     * Returns an array of all employee benefits for this employee
     *
     * Benefits containing PHI are only visible to applications with the `employee_benefits:read:phi` scope.
     *
     * scope: `employee_benefits:read`
     */
    async get(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, employeeBenefitsGet_js_1.employeeBenefitsGet)(this, request, options));
    }
    /**
     * Get an employee benefit
     *
     * @remarks
     * Employee benefits represent an employee enrolled in a particular company benefit. It includes information specific to that employee’s enrollment.
     *
     * Benefits containing PHI are only visible to applications with the `employee_benefits:read:phi` scope.
     *
     * scope: `employee_benefits:read`
     */
    async retrieve(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, employeeBenefitsRetrieve_js_1.employeeBenefitsRetrieve)(this, request, options));
    }
    /**
     * Update an employee benefit
     *
     * @remarks
     * Employee benefits represent an employee enrolled in a particular company benefit. It includes information specific to that employee’s enrollment.
     *
     * scope: `employee_benefits:write`
     */
    async update(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, employeeBenefitsUpdate_js_1.employeeBenefitsUpdate)(this, request, options));
    }
    /**
     * Delete an employee benefit
     *
     * @remarks
     * Employee benefits represent an employee enrolled in a particular company benefit. It includes information specific to that employee’s enrollment.
     *
     * scope: `employee_benefits:write`
     */
    async delete(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, employeeBenefitsDelete_js_1.employeeBenefitsDelete)(this, request, options));
    }
    /**
     * Get year-to-date benefit amounts from a different company
     *
     * @remarks
     * Retrieves year-to-date benefit amounts that were contributed at a different company for the specified employee.
     * Returns benefit amounts for the requested tax year (defaults to current year if not specified).
     *
     * This endpoint only supports retrieving outside contributions for 401(k) benefits.
     *
     * scope: `employee_benefits:read`
     */
    async getYtdBenefitAmountsFromDifferentCompany(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, employeeBenefitsGetYtdBenefitAmountsFromDifferentCompany_js_1.employeeBenefitsGetYtdBenefitAmountsFromDifferentCompany)(this, request, options));
    }
    /**
     * Create year-to-date benefit amounts from a different company
     *
     * @remarks
     * Year-to-date benefit amounts from a different company represents the amount of money added to an employee's plan during a current year, made outside of the current contribution when they were employed at a different company.
     *
     * This endpoint only supports passing outside contributions for 401(k) benefits.
     *
     * scope: `employee_benefits:write`
     */
    async createYtdBenefitAmountsFromDifferentCompany(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, employeeBenefitsCreateYtdBenefitAmountsFromDifferentCompany_js_1.employeeBenefitsCreateYtdBenefitAmountsFromDifferentCompany)(this, request, options));
    }
}
exports.EmployeeBenefits = EmployeeBenefits;
//# sourceMappingURL=employeebenefits.js.map