"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Invoices = void 0;
const invoicesGet_js_1 = require("../funcs/invoicesGet.js");
const sdks_js_1 = require("../lib/sdks.js");
const fp_js_1 = require("../types/fp.js");
class Invoices extends sdks_js_1.ClientSDK {
    /**
     * Retrieve invoicing data for companies
     *
     * @remarks
     * Retrieve data for active companies used to calculate invoices for Gusto Embedded Payroll. A company is considered active for an invoice period if they are an active partner managed company, have run payroll or created contractor payments since becoming a partner managed company, and are not suspended at any point during the invoice period.  This endpoint forces pagination, with 100 results returned at a time. You can learn more about our pagination here: [pagination guide](https://docs.gusto.com/embedded-payroll/docs/pagination)
     *
     * > 📘 System Access Authentication
     * >
     * > This endpoint uses the [Bearer Auth scheme with the system-level access token in the HTTP Authorization header](https://docs.gusto.com/embedded-payroll/docs/system-access)
     *
     * scope: `invoices:read`
     */
    async get(security, request, options) {
        return (0, fp_js_1.unwrapAsync)((0, invoicesGet_js_1.invoicesGet)(this, security, request, options));
    }
}
exports.Invoices = Invoices;
//# sourceMappingURL=invoices.js.map