import { ClientSDK } from "../lib/sdks.js";
import { AchTransactions } from "./achtransactions.js";
import { BankAccounts } from "./bankaccounts.js";
import { Companies } from "./companies.js";
import { CompanyAttachment } from "./companyattachment.js";
import { CompanyAttachments } from "./companyattachments.js";
import { CompanyBenefits } from "./companybenefits.js";
import { CompanyForms } from "./companyforms.js";
import { ContractorDocuments } from "./contractordocuments.js";
import { ContractorForms } from "./contractorforms.js";
import { ContractorPaymentGroups } from "./contractorpaymentgroups.js";
import { ContractorPaymentMethod } from "./contractorpaymentmethod.js";
import { ContractorPaymentMethods } from "./contractorpaymentmethods.js";
import { ContractorPayments } from "./contractorpayments.js";
import { Contractors } from "./contractors.js";
import { Departments } from "./departments.js";
import { EarningTypes } from "./earningtypes.js";
import { EmployeeAddresses } from "./employeeaddresses.js";
import { EmployeeBenefits } from "./employeebenefits.js";
import { EmployeeEmployments } from "./employeeemployments.js";
import { EmployeeForms } from "./employeeforms.js";
import { EmployeePaymentMethod } from "./employeepaymentmethod.js";
import { EmployeePaymentMethods } from "./employeepaymentmethods.js";
import { Employees } from "./employees.js";
import { EmployeeTaxSetup } from "./employeetaxsetup.js";
import { Events } from "./events.js";
import { ExternalPayrolls } from "./externalpayrolls.js";
import { FederalTaxDetails } from "./federaltaxdetails.js";
import { Flows } from "./flows.js";
import { Garnishments } from "./garnishments.js";
import { GeneratedDocuments } from "./generateddocuments.js";
import { HistoricalEmployees } from "./historicalemployees.js";
import { HolidayPayPolicies } from "./holidaypaypolicies.js";
import { I9Verification } from "./i9verification.js";
import { IndustrySelection } from "./industryselection.js";
import { Introspection } from "./introspection.js";
import { Invoices } from "./invoices.js";
import { JobsAndCompensations } from "./jobsandcompensations.js";
import { Locations } from "./locations.js";
import { Notifications } from "./notifications.js";
import { PaymentConfigs } from "./paymentconfigs.js";
import { Payrolls } from "./payrolls.js";
import { PaySchedules } from "./payschedules.js";
import { RecoveryCases } from "./recoverycases.js";
import { Reports } from "./reports.js";
import { Signatories } from "./signatories.js";
import { TaxRequirements } from "./taxrequirements.js";
import { TimeOffPolicies } from "./timeoffpolicies.js";
import { Webhooks } from "./webhooks.js";
import { WireInRequests } from "./wireinrequests.js";
export declare class GustoEmbedded extends ClientSDK {
    private _introspection?;
    get introspection(): Introspection;
    private _companies?;
    get companies(): Companies;
    private _invoices?;
    get invoices(): Invoices;
    private _companyAttachments?;
    get companyAttachments(): CompanyAttachments;
    private _companyAttachment?;
    get companyAttachment(): CompanyAttachment;
    private _federalTaxDetails?;
    get federalTaxDetails(): FederalTaxDetails;
    private _industrySelection?;
    get industrySelection(): IndustrySelection;
    private _signatories?;
    get signatories(): Signatories;
    private _flows?;
    get flows(): Flows;
    private _locations?;
    get locations(): Locations;
    private _bankAccounts?;
    get bankAccounts(): BankAccounts;
    private _externalPayrolls?;
    get externalPayrolls(): ExternalPayrolls;
    private _paymentConfigs?;
    get paymentConfigs(): PaymentConfigs;
    private _paySchedules?;
    get paySchedules(): PaySchedules;
    private _employees?;
    get employees(): Employees;
    private _historicalEmployees?;
    get historicalEmployees(): HistoricalEmployees;
    private _departments?;
    get departments(): Departments;
    private _employeeEmployments?;
    get employeeEmployments(): EmployeeEmployments;
    private _employeeAddresses?;
    get employeeAddresses(): EmployeeAddresses;
    private _employeeTaxSetup?;
    get employeeTaxSetup(): EmployeeTaxSetup;
    private _employeePaymentMethod?;
    get employeePaymentMethod(): EmployeePaymentMethod;
    private _employeePaymentMethods?;
    get employeePaymentMethods(): EmployeePaymentMethods;
    private _jobsAndCompensations?;
    get jobsAndCompensations(): JobsAndCompensations;
    private _earningTypes?;
    get earningTypes(): EarningTypes;
    private _contractors?;
    get contractors(): Contractors;
    private _contractorPaymentMethods?;
    get contractorPaymentMethods(): ContractorPaymentMethods;
    private _contractorPaymentMethod?;
    get contractorPaymentMethod(): ContractorPaymentMethod;
    private _webhooks?;
    get webhooks(): Webhooks;
    private _contractorForms?;
    get contractorForms(): ContractorForms;
    private _contractorDocuments?;
    get contractorDocuments(): ContractorDocuments;
    private _employeeForms?;
    get employeeForms(): EmployeeForms;
    private _payrolls?;
    get payrolls(): Payrolls;
    private _timeOffPolicies?;
    get timeOffPolicies(): TimeOffPolicies;
    private _contractorPayments?;
    get contractorPayments(): ContractorPayments;
    private _contractorPaymentGroups?;
    get contractorPaymentGroups(): ContractorPaymentGroups;
    private _companyForms?;
    get companyForms(): CompanyForms;
    private _generatedDocuments?;
    get generatedDocuments(): GeneratedDocuments;
    private _reports?;
    get reports(): Reports;
    private _companyBenefits?;
    get companyBenefits(): CompanyBenefits;
    private _employeeBenefits?;
    get employeeBenefits(): EmployeeBenefits;
    private _garnishments?;
    get garnishments(): Garnishments;
    private _i9Verification?;
    get i9Verification(): I9Verification;
    private _taxRequirements?;
    get taxRequirements(): TaxRequirements;
    private _holidayPayPolicies?;
    get holidayPayPolicies(): HolidayPayPolicies;
    private _notifications?;
    get notifications(): Notifications;
    private _events?;
    get events(): Events;
    private _recoveryCases?;
    get recoveryCases(): RecoveryCases;
    private _achTransactions?;
    get achTransactions(): AchTransactions;
    private _wireInRequests?;
    get wireInRequests(): WireInRequests;
}
//# sourceMappingURL=sdk.d.ts.map