"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse$ = exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse$outboundSchema = exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse$inboundSchema = exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest$ = exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest$outboundSchema = exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest$inboundSchema = void 0;
exports.deleteV1EmployeeBenefitsEmployeeBenefitIdRequestToJSON = deleteV1EmployeeBenefitsEmployeeBenefitIdRequestToJSON;
exports.deleteV1EmployeeBenefitsEmployeeBenefitIdRequestFromJSON = deleteV1EmployeeBenefitsEmployeeBenefitIdRequestFromJSON;
exports.deleteV1EmployeeBenefitsEmployeeBenefitIdResponseToJSON = deleteV1EmployeeBenefitsEmployeeBenefitIdResponseToJSON;
exports.deleteV1EmployeeBenefitsEmployeeBenefitIdResponseFromJSON = deleteV1EmployeeBenefitsEmployeeBenefitIdResponseFromJSON;
const z = __importStar(require("zod"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const components = __importStar(require("../components/index.js"));
/** @internal */
exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest$inboundSchema = z.object({
    employee_benefit_id: z.string(),
    "X-Gusto-API-Version": components.VersionHeader$inboundSchema.default("2024-04-01"),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "employee_benefit_id": "employeeBenefitId",
        "X-Gusto-API-Version": "xGustoAPIVersion",
    });
});
/** @internal */
exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest$outboundSchema = z.object({
    employeeBenefitId: z.string(),
    xGustoAPIVersion: components.VersionHeader$outboundSchema.default("2024-04-01"),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        employeeBenefitId: "employee_benefit_id",
        xGustoAPIVersion: "X-Gusto-API-Version",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest$;
(function (DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest$) {
    /** @deprecated use `DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest$inboundSchema` instead. */
    DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest$.inboundSchema = exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest$inboundSchema;
    /** @deprecated use `DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest$outboundSchema` instead. */
    DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest$.outboundSchema = exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest$outboundSchema;
})(DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest$ || (exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest$ = DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest$ = {}));
function deleteV1EmployeeBenefitsEmployeeBenefitIdRequestToJSON(deleteV1EmployeeBenefitsEmployeeBenefitIdRequest) {
    return JSON.stringify(exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest$outboundSchema.parse(deleteV1EmployeeBenefitsEmployeeBenefitIdRequest));
}
function deleteV1EmployeeBenefitsEmployeeBenefitIdRequestFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'DeleteV1EmployeeBenefitsEmployeeBenefitIdRequest' from JSON`);
}
/** @internal */
exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse$inboundSchema = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "ContentType": "contentType",
        "StatusCode": "statusCode",
        "RawResponse": "rawResponse",
    });
});
/** @internal */
exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse$outboundSchema = z.object({
    contentType: z.string(),
    statusCode: z.number().int(),
    rawResponse: z.instanceof(Response).transform(() => {
        throw new Error("Response cannot be serialized");
    }),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        contentType: "ContentType",
        statusCode: "StatusCode",
        rawResponse: "RawResponse",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse$;
(function (DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse$) {
    /** @deprecated use `DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse$inboundSchema` instead. */
    DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse$.inboundSchema = exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse$inboundSchema;
    /** @deprecated use `DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse$outboundSchema` instead. */
    DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse$.outboundSchema = exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse$outboundSchema;
})(DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse$ || (exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse$ = DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse$ = {}));
function deleteV1EmployeeBenefitsEmployeeBenefitIdResponseToJSON(deleteV1EmployeeBenefitsEmployeeBenefitIdResponse) {
    return JSON.stringify(exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse$outboundSchema.parse(deleteV1EmployeeBenefitsEmployeeBenefitIdResponse));
}
function deleteV1EmployeeBenefitsEmployeeBenefitIdResponseFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'DeleteV1EmployeeBenefitsEmployeeBenefitIdResponse' from JSON`);
}
//# sourceMappingURL=deletev1employeebenefitsemployeebenefitid.js.map