"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetV1CompanyOnboardingStatusResponse$ = exports.GetV1CompanyOnboardingStatusResponse$outboundSchema = exports.GetV1CompanyOnboardingStatusResponse$inboundSchema = exports.GetV1CompanyOnboardingStatusRequest$ = exports.GetV1CompanyOnboardingStatusRequest$outboundSchema = exports.GetV1CompanyOnboardingStatusRequest$inboundSchema = void 0;
exports.getV1CompanyOnboardingStatusRequestToJSON = getV1CompanyOnboardingStatusRequestToJSON;
exports.getV1CompanyOnboardingStatusRequestFromJSON = getV1CompanyOnboardingStatusRequestFromJSON;
exports.getV1CompanyOnboardingStatusResponseToJSON = getV1CompanyOnboardingStatusResponseToJSON;
exports.getV1CompanyOnboardingStatusResponseFromJSON = getV1CompanyOnboardingStatusResponseFromJSON;
const z = __importStar(require("zod"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const components = __importStar(require("../components/index.js"));
/** @internal */
exports.GetV1CompanyOnboardingStatusRequest$inboundSchema = z.object({
    company_uuid: z.string(),
    additional_steps: z.string().optional(),
    "X-Gusto-API-Version": components.VersionHeader$inboundSchema.default("2024-04-01"),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "company_uuid": "companyUuid",
        "additional_steps": "additionalSteps",
        "X-Gusto-API-Version": "xGustoAPIVersion",
    });
});
/** @internal */
exports.GetV1CompanyOnboardingStatusRequest$outboundSchema = z.object({
    companyUuid: z.string(),
    additionalSteps: z.string().optional(),
    xGustoAPIVersion: components.VersionHeader$outboundSchema.default("2024-04-01"),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        companyUuid: "company_uuid",
        additionalSteps: "additional_steps",
        xGustoAPIVersion: "X-Gusto-API-Version",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var GetV1CompanyOnboardingStatusRequest$;
(function (GetV1CompanyOnboardingStatusRequest$) {
    /** @deprecated use `GetV1CompanyOnboardingStatusRequest$inboundSchema` instead. */
    GetV1CompanyOnboardingStatusRequest$.inboundSchema = exports.GetV1CompanyOnboardingStatusRequest$inboundSchema;
    /** @deprecated use `GetV1CompanyOnboardingStatusRequest$outboundSchema` instead. */
    GetV1CompanyOnboardingStatusRequest$.outboundSchema = exports.GetV1CompanyOnboardingStatusRequest$outboundSchema;
})(GetV1CompanyOnboardingStatusRequest$ || (exports.GetV1CompanyOnboardingStatusRequest$ = GetV1CompanyOnboardingStatusRequest$ = {}));
function getV1CompanyOnboardingStatusRequestToJSON(getV1CompanyOnboardingStatusRequest) {
    return JSON.stringify(exports.GetV1CompanyOnboardingStatusRequest$outboundSchema.parse(getV1CompanyOnboardingStatusRequest));
}
function getV1CompanyOnboardingStatusRequestFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.GetV1CompanyOnboardingStatusRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetV1CompanyOnboardingStatusRequest' from JSON`);
}
/** @internal */
exports.GetV1CompanyOnboardingStatusResponse$inboundSchema = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    "Company-Onboarding-Status": components.CompanyOnboardingStatus$inboundSchema
        .optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "ContentType": "contentType",
        "StatusCode": "statusCode",
        "RawResponse": "rawResponse",
        "Company-Onboarding-Status": "companyOnboardingStatus",
    });
});
/** @internal */
exports.GetV1CompanyOnboardingStatusResponse$outboundSchema = z.object({
    contentType: z.string(),
    statusCode: z.number().int(),
    rawResponse: z.instanceof(Response).transform(() => {
        throw new Error("Response cannot be serialized");
    }),
    companyOnboardingStatus: components.CompanyOnboardingStatus$outboundSchema
        .optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        contentType: "ContentType",
        statusCode: "StatusCode",
        rawResponse: "RawResponse",
        companyOnboardingStatus: "Company-Onboarding-Status",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var GetV1CompanyOnboardingStatusResponse$;
(function (GetV1CompanyOnboardingStatusResponse$) {
    /** @deprecated use `GetV1CompanyOnboardingStatusResponse$inboundSchema` instead. */
    GetV1CompanyOnboardingStatusResponse$.inboundSchema = exports.GetV1CompanyOnboardingStatusResponse$inboundSchema;
    /** @deprecated use `GetV1CompanyOnboardingStatusResponse$outboundSchema` instead. */
    GetV1CompanyOnboardingStatusResponse$.outboundSchema = exports.GetV1CompanyOnboardingStatusResponse$outboundSchema;
})(GetV1CompanyOnboardingStatusResponse$ || (exports.GetV1CompanyOnboardingStatusResponse$ = GetV1CompanyOnboardingStatusResponse$ = {}));
function getV1CompanyOnboardingStatusResponseToJSON(getV1CompanyOnboardingStatusResponse) {
    return JSON.stringify(exports.GetV1CompanyOnboardingStatusResponse$outboundSchema.parse(getV1CompanyOnboardingStatusResponse));
}
function getV1CompanyOnboardingStatusResponseFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.GetV1CompanyOnboardingStatusResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetV1CompanyOnboardingStatusResponse' from JSON`);
}
//# sourceMappingURL=getv1companyonboardingstatus.js.map