"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostV1EmployeesEmployeeIdRehireResponse$ = exports.PostV1EmployeesEmployeeIdRehireResponse$outboundSchema = exports.PostV1EmployeesEmployeeIdRehireResponse$inboundSchema = exports.PostV1EmployeesEmployeeIdRehireRequest$ = exports.PostV1EmployeesEmployeeIdRehireRequest$outboundSchema = exports.PostV1EmployeesEmployeeIdRehireRequest$inboundSchema = void 0;
exports.postV1EmployeesEmployeeIdRehireRequestToJSON = postV1EmployeesEmployeeIdRehireRequestToJSON;
exports.postV1EmployeesEmployeeIdRehireRequestFromJSON = postV1EmployeesEmployeeIdRehireRequestFromJSON;
exports.postV1EmployeesEmployeeIdRehireResponseToJSON = postV1EmployeesEmployeeIdRehireResponseToJSON;
exports.postV1EmployeesEmployeeIdRehireResponseFromJSON = postV1EmployeesEmployeeIdRehireResponseFromJSON;
const z = __importStar(require("zod"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const components = __importStar(require("../components/index.js"));
/** @internal */
exports.PostV1EmployeesEmployeeIdRehireRequest$inboundSchema = z.object({
    employee_id: z.string(),
    "X-Gusto-API-Version": components.VersionHeader$inboundSchema.default("2024-04-01"),
    "Rehire-Body": components.RehireBody$inboundSchema,
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "employee_id": "employeeId",
        "X-Gusto-API-Version": "xGustoAPIVersion",
        "Rehire-Body": "rehireBody",
    });
});
/** @internal */
exports.PostV1EmployeesEmployeeIdRehireRequest$outboundSchema = z.object({
    employeeId: z.string(),
    xGustoAPIVersion: components.VersionHeader$outboundSchema.default("2024-04-01"),
    rehireBody: components.RehireBody$outboundSchema,
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        employeeId: "employee_id",
        xGustoAPIVersion: "X-Gusto-API-Version",
        rehireBody: "Rehire-Body",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var PostV1EmployeesEmployeeIdRehireRequest$;
(function (PostV1EmployeesEmployeeIdRehireRequest$) {
    /** @deprecated use `PostV1EmployeesEmployeeIdRehireRequest$inboundSchema` instead. */
    PostV1EmployeesEmployeeIdRehireRequest$.inboundSchema = exports.PostV1EmployeesEmployeeIdRehireRequest$inboundSchema;
    /** @deprecated use `PostV1EmployeesEmployeeIdRehireRequest$outboundSchema` instead. */
    PostV1EmployeesEmployeeIdRehireRequest$.outboundSchema = exports.PostV1EmployeesEmployeeIdRehireRequest$outboundSchema;
})(PostV1EmployeesEmployeeIdRehireRequest$ || (exports.PostV1EmployeesEmployeeIdRehireRequest$ = PostV1EmployeesEmployeeIdRehireRequest$ = {}));
function postV1EmployeesEmployeeIdRehireRequestToJSON(postV1EmployeesEmployeeIdRehireRequest) {
    return JSON.stringify(exports.PostV1EmployeesEmployeeIdRehireRequest$outboundSchema.parse(postV1EmployeesEmployeeIdRehireRequest));
}
function postV1EmployeesEmployeeIdRehireRequestFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.PostV1EmployeesEmployeeIdRehireRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PostV1EmployeesEmployeeIdRehireRequest' from JSON`);
}
/** @internal */
exports.PostV1EmployeesEmployeeIdRehireResponse$inboundSchema = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    Rehire: components.Rehire$inboundSchema.optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "ContentType": "contentType",
        "StatusCode": "statusCode",
        "RawResponse": "rawResponse",
        "Rehire": "rehire",
    });
});
/** @internal */
exports.PostV1EmployeesEmployeeIdRehireResponse$outboundSchema = z.object({
    contentType: z.string(),
    statusCode: z.number().int(),
    rawResponse: z.instanceof(Response).transform(() => {
        throw new Error("Response cannot be serialized");
    }),
    rehire: components.Rehire$outboundSchema.optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        contentType: "ContentType",
        statusCode: "StatusCode",
        rawResponse: "RawResponse",
        rehire: "Rehire",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var PostV1EmployeesEmployeeIdRehireResponse$;
(function (PostV1EmployeesEmployeeIdRehireResponse$) {
    /** @deprecated use `PostV1EmployeesEmployeeIdRehireResponse$inboundSchema` instead. */
    PostV1EmployeesEmployeeIdRehireResponse$.inboundSchema = exports.PostV1EmployeesEmployeeIdRehireResponse$inboundSchema;
    /** @deprecated use `PostV1EmployeesEmployeeIdRehireResponse$outboundSchema` instead. */
    PostV1EmployeesEmployeeIdRehireResponse$.outboundSchema = exports.PostV1EmployeesEmployeeIdRehireResponse$outboundSchema;
})(PostV1EmployeesEmployeeIdRehireResponse$ || (exports.PostV1EmployeesEmployeeIdRehireResponse$ = PostV1EmployeesEmployeeIdRehireResponse$ = {}));
function postV1EmployeesEmployeeIdRehireResponseToJSON(postV1EmployeesEmployeeIdRehireResponse) {
    return JSON.stringify(exports.PostV1EmployeesEmployeeIdRehireResponse$outboundSchema.parse(postV1EmployeesEmployeeIdRehireResponse));
}
function postV1EmployeesEmployeeIdRehireResponseFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.PostV1EmployeesEmployeeIdRehireResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PostV1EmployeesEmployeeIdRehireResponse' from JSON`);
}
//# sourceMappingURL=postv1employeesemployeeidrehire.js.map