"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse$ = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse$outboundSchema = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse$inboundSchema = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$ = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$outboundSchema = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$inboundSchema = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest$ = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest$outboundSchema = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest$inboundSchema = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$ = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$outboundSchema = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$inboundSchema = void 0;
exports.postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBodyToJSON = postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBodyToJSON;
exports.postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBodyFromJSON = postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBodyFromJSON;
exports.postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestToJSON = postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestToJSON;
exports.postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestFromJSON = postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestFromJSON;
exports.postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBodyToJSON = postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBodyToJSON;
exports.postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBodyFromJSON = postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBodyFromJSON;
exports.postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseToJSON = postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseToJSON;
exports.postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseFromJSON = postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseFromJSON;
const z = __importStar(require("zod"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const components = __importStar(require("../components/index.js"));
/** @internal */
exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$inboundSchema = z.object({
    email: z.string(),
    ip_address: z.string(),
    external_user_id: z.string(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "ip_address": "ipAddress",
        "external_user_id": "externalUserId",
    });
});
/** @internal */
exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$outboundSchema = z.object({
    email: z.string(),
    ipAddress: z.string(),
    externalUserId: z.string(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        ipAddress: "ip_address",
        externalUserId: "external_user_id",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$;
(function (PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$) {
    /** @deprecated use `PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$inboundSchema` instead. */
    PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$.inboundSchema = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$inboundSchema;
    /** @deprecated use `PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$outboundSchema` instead. */
    PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$.outboundSchema = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$outboundSchema;
})(PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$ || (exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$ = PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$ = {}));
function postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBodyToJSON(postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody) {
    return JSON.stringify(exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$outboundSchema
        .parse(postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody));
}
function postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBodyFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$inboundSchema
        .parse(JSON.parse(x)), `Failed to parse 'PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody' from JSON`);
}
/** @internal */
exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest$inboundSchema = z.object({
    company_uuid: z.string(),
    "X-Gusto-API-Version": components.VersionHeader$inboundSchema.default("2024-04-01"),
    RequestBody: z.lazy(() => exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$inboundSchema),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "company_uuid": "companyUuid",
        "X-Gusto-API-Version": "xGustoAPIVersion",
        "RequestBody": "requestBody",
    });
});
/** @internal */
exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest$outboundSchema = z.object({
    companyUuid: z.string(),
    xGustoAPIVersion: components.VersionHeader$outboundSchema.default("2024-04-01"),
    requestBody: z.lazy(() => exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestBody$outboundSchema),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        companyUuid: "company_uuid",
        xGustoAPIVersion: "X-Gusto-API-Version",
        requestBody: "RequestBody",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest$;
(function (PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest$) {
    /** @deprecated use `PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest$inboundSchema` instead. */
    PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest$.inboundSchema = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest$inboundSchema;
    /** @deprecated use `PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest$outboundSchema` instead. */
    PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest$.outboundSchema = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest$outboundSchema;
})(PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest$ || (exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest$ = PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest$ = {}));
function postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestToJSON(postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest) {
    return JSON.stringify(exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest$outboundSchema
        .parse(postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest));
}
function postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequestFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest$inboundSchema
        .parse(JSON.parse(x)), `Failed to parse 'PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceRequest' from JSON`);
}
/** @internal */
exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$inboundSchema = z.object({
    latest_terms_accepted: z.boolean().optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "latest_terms_accepted": "latestTermsAccepted",
    });
});
/** @internal */
exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$outboundSchema = z.object({
    latestTermsAccepted: z.boolean().optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        latestTermsAccepted: "latest_terms_accepted",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$;
(function (PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$) {
    /** @deprecated use `PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$inboundSchema` instead. */
    PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$.inboundSchema = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$inboundSchema;
    /** @deprecated use `PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$outboundSchema` instead. */
    PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$.outboundSchema = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$outboundSchema;
})(PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$ || (exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$ = PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$ = {}));
function postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBodyToJSON(postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody) {
    return JSON.stringify(exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$outboundSchema
        .parse(postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody));
}
function postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBodyFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$inboundSchema
        .parse(JSON.parse(x)), `Failed to parse 'PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody' from JSON`);
}
/** @internal */
exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse$inboundSchema = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    object: z.lazy(() => exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$inboundSchema).optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "ContentType": "contentType",
        "StatusCode": "statusCode",
        "RawResponse": "rawResponse",
    });
});
/** @internal */
exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse$outboundSchema = z.object({
    contentType: z.string(),
    statusCode: z.number().int(),
    rawResponse: z.instanceof(Response).transform(() => {
        throw new Error("Response cannot be serialized");
    }),
    object: z.lazy(() => exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseBody$outboundSchema).optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        contentType: "ContentType",
        statusCode: "StatusCode",
        rawResponse: "RawResponse",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse$;
(function (PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse$) {
    /** @deprecated use `PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse$inboundSchema` instead. */
    PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse$.inboundSchema = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse$inboundSchema;
    /** @deprecated use `PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse$outboundSchema` instead. */
    PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse$.outboundSchema = exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse$outboundSchema;
})(PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse$ || (exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse$ = PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse$ = {}));
function postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseToJSON(postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse) {
    return JSON.stringify(exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse$outboundSchema
        .parse(postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse));
}
function postPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponseFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse$inboundSchema
        .parse(JSON.parse(x)), `Failed to parse 'PostPartnerManagedCompaniesCompanyUuidAcceptTermsOfServiceResponse' from JSON`);
}
//# sourceMappingURL=postpartnermanagedcompaniescompanyuuidaccepttermsofservice.js.map