"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.useContractorPaymentGroupsCreateMutation = useContractorPaymentGroupsCreateMutation;
exports.mutationKeyContractorPaymentGroupsCreate = mutationKeyContractorPaymentGroupsCreate;
exports.buildContractorPaymentGroupsCreateMutation = buildContractorPaymentGroupsCreateMutation;
const react_query_1 = require("@tanstack/react-query");
const contractorPaymentGroupsCreate_js_1 = require("../funcs/contractorPaymentGroupsCreate.js");
const primitives_js_1 = require("../lib/primitives.js");
const fp_js_1 = require("../types/fp.js");
const _context_js_1 = require("./_context.js");
/**
 * Create a contractor payment group
 *
 * @remarks
 * Pay a group of contractors. Information needed depends on the contractor's wage type (hourly vs fixed)
 *
 * scope: `payrolls:run`
 */
function useContractorPaymentGroupsCreateMutation(options) {
    const client = (0, _context_js_1.useGustoEmbeddedContext)();
    return (0, react_query_1.useMutation)({
        ...buildContractorPaymentGroupsCreateMutation(client, options),
        ...options,
    });
}
function mutationKeyContractorPaymentGroupsCreate() {
    return ["@gusto/embedded-api", "contractorPaymentGroups", "create"];
}
function buildContractorPaymentGroupsCreateMutation(client$, hookOptions) {
    return {
        mutationKey: mutationKeyContractorPaymentGroupsCreate(),
        mutationFn: function contractorPaymentGroupsCreateMutationFn({ request, options, }) {
            const mergedOptions = {
                ...hookOptions,
                ...options,
                fetchOptions: {
                    ...hookOptions?.fetchOptions,
                    ...options?.fetchOptions,
                    signal: (0, primitives_js_1.combineSignals)(hookOptions?.fetchOptions?.signal, options?.fetchOptions?.signal),
                },
            };
            return (0, fp_js_1.unwrapAsync)((0, contractorPaymentGroupsCreate_js_1.contractorPaymentGroupsCreate)(client$, request, mergedOptions));
        },
    };
}
//# sourceMappingURL=contractorPaymentGroupsCreate.js.map