"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.useContractorPaymentMethodUpdatePaymentMethodMutation = useContractorPaymentMethodUpdatePaymentMethodMutation;
exports.mutationKeyContractorPaymentMethodUpdatePaymentMethod = mutationKeyContractorPaymentMethodUpdatePaymentMethod;
exports.buildContractorPaymentMethodUpdatePaymentMethodMutation = buildContractorPaymentMethodUpdatePaymentMethodMutation;
const react_query_1 = require("@tanstack/react-query");
const contractorPaymentMethodUpdatePaymentMethod_js_1 = require("../funcs/contractorPaymentMethodUpdatePaymentMethod.js");
const primitives_js_1 = require("../lib/primitives.js");
const fp_js_1 = require("../types/fp.js");
const _context_js_1 = require("./_context.js");
/**
 * Update a contractor's payment method
 *
 * @remarks
 * Updates a contractor's payment method. Note that creating a contractor
 * bank account will also update the contractor's payment method.
 *
 * scope: `contractor_payment_methods:write`
 */
function useContractorPaymentMethodUpdatePaymentMethodMutation(options) {
    const client = (0, _context_js_1.useGustoEmbeddedContext)();
    return (0, react_query_1.useMutation)({
        ...buildContractorPaymentMethodUpdatePaymentMethodMutation(client, options),
        ...options,
    });
}
function mutationKeyContractorPaymentMethodUpdatePaymentMethod() {
    return [
        "@gusto/embedded-api",
        "contractorPaymentMethod",
        "updatePaymentMethod",
    ];
}
function buildContractorPaymentMethodUpdatePaymentMethodMutation(client$, hookOptions) {
    return {
        mutationKey: mutationKeyContractorPaymentMethodUpdatePaymentMethod(),
        mutationFn: function contractorPaymentMethodUpdatePaymentMethodMutationFn({ request, options, }) {
            const mergedOptions = {
                ...hookOptions,
                ...options,
                fetchOptions: {
                    ...hookOptions?.fetchOptions,
                    ...options?.fetchOptions,
                    signal: (0, primitives_js_1.combineSignals)(hookOptions?.fetchOptions?.signal, options?.fetchOptions?.signal),
                },
            };
            return (0, fp_js_1.unwrapAsync)((0, contractorPaymentMethodUpdatePaymentMethod_js_1.contractorPaymentMethodUpdatePaymentMethod)(client$, request, mergedOptions));
        },
    };
}
//# sourceMappingURL=contractorPaymentMethodUpdatePaymentMethod.js.map