"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.useContractorPaymentsGet = useContractorPaymentsGet;
exports.useContractorPaymentsGetSuspense = useContractorPaymentsGetSuspense;
exports.prefetchContractorPaymentsGet = prefetchContractorPaymentsGet;
exports.setContractorPaymentsGetData = setContractorPaymentsGetData;
exports.invalidateContractorPaymentsGet = invalidateContractorPaymentsGet;
exports.invalidateAllContractorPaymentsGet = invalidateAllContractorPaymentsGet;
exports.buildContractorPaymentsGetQuery = buildContractorPaymentsGetQuery;
exports.queryKeyContractorPaymentsGet = queryKeyContractorPaymentsGet;
const react_query_1 = require("@tanstack/react-query");
const contractorPaymentsGet_js_1 = require("../funcs/contractorPaymentsGet.js");
const primitives_js_1 = require("../lib/primitives.js");
const fp_js_1 = require("../types/fp.js");
const _context_js_1 = require("./_context.js");
/**
 * Get a single contractor payment
 *
 * @remarks
 * Returns a single contractor payment.
 * scope: `payrolls:read`
 */
function useContractorPaymentsGet(request, options) {
    const client = (0, _context_js_1.useGustoEmbeddedContext)();
    return (0, react_query_1.useQuery)({
        ...buildContractorPaymentsGetQuery(client, request, options),
        ...options,
    });
}
/**
 * Get a single contractor payment
 *
 * @remarks
 * Returns a single contractor payment.
 * scope: `payrolls:read`
 */
function useContractorPaymentsGetSuspense(request, options) {
    const client = (0, _context_js_1.useGustoEmbeddedContext)();
    return (0, react_query_1.useSuspenseQuery)({
        ...buildContractorPaymentsGetQuery(client, request, options),
        ...options,
    });
}
function prefetchContractorPaymentsGet(queryClient, client$, request) {
    return queryClient.prefetchQuery({
        ...buildContractorPaymentsGetQuery(client$, request),
    });
}
function setContractorPaymentsGetData(client, queryKeyBase, data) {
    const key = queryKeyContractorPaymentsGet(...queryKeyBase);
    return client.setQueryData(key, data);
}
function invalidateContractorPaymentsGet(client, queryKeyBase, filters) {
    return client.invalidateQueries({
        ...filters,
        queryKey: [
            "@gusto/embedded-api",
            "contractorPayments",
            "get",
            ...queryKeyBase,
        ],
    });
}
function invalidateAllContractorPaymentsGet(client, filters) {
    return client.invalidateQueries({
        ...filters,
        queryKey: ["@gusto/embedded-api", "contractorPayments", "get"],
    });
}
function buildContractorPaymentsGetQuery(client$, request, options) {
    return {
        queryKey: queryKeyContractorPaymentsGet(request.companyId, request.contractorPaymentId, { xGustoAPIVersion: request.xGustoAPIVersion }),
        queryFn: async function contractorPaymentsGetQueryFn(ctx) {
            const sig = (0, primitives_js_1.combineSignals)(ctx.signal, options?.fetchOptions?.signal);
            const mergedOptions = {
                ...options,
                fetchOptions: { ...options?.fetchOptions, signal: sig },
            };
            return (0, fp_js_1.unwrapAsync)((0, contractorPaymentsGet_js_1.contractorPaymentsGet)(client$, request, mergedOptions));
        },
    };
}
function queryKeyContractorPaymentsGet(companyId, contractorPaymentId, parameters) {
    return [
        "@gusto/embedded-api",
        "contractorPayments",
        "get",
        companyId,
        contractorPaymentId,
        parameters,
    ];
}
//# sourceMappingURL=contractorPaymentsGet.js.map