"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.useEmployeesUpdateMutation = useEmployeesUpdateMutation;
exports.mutationKeyEmployeesUpdate = mutationKeyEmployeesUpdate;
exports.buildEmployeesUpdateMutation = buildEmployeesUpdateMutation;
const react_query_1 = require("@tanstack/react-query");
const employeesUpdate_js_1 = require("../funcs/employeesUpdate.js");
const primitives_js_1 = require("../lib/primitives.js");
const fp_js_1 = require("../types/fp.js");
const _context_js_1 = require("./_context.js");
/**
 * Update an employee
 *
 * @remarks
 * Update an employee.
 *
 * scope: `employees:write`
 */
function useEmployeesUpdateMutation(options) {
    const client = (0, _context_js_1.useGustoEmbeddedContext)();
    return (0, react_query_1.useMutation)({
        ...buildEmployeesUpdateMutation(client, options),
        ...options,
    });
}
function mutationKeyEmployeesUpdate() {
    return ["@gusto/embedded-api", "Employees", "update"];
}
function buildEmployeesUpdateMutation(client$, hookOptions) {
    return {
        mutationKey: mutationKeyEmployeesUpdate(),
        mutationFn: function employeesUpdateMutationFn({ request, options, }) {
            const mergedOptions = {
                ...hookOptions,
                ...options,
                fetchOptions: {
                    ...hookOptions?.fetchOptions,
                    ...options?.fetchOptions,
                    signal: (0, primitives_js_1.combineSignals)(hookOptions?.fetchOptions?.signal, options?.fetchOptions?.signal),
                },
            };
            return (0, fp_js_1.unwrapAsync)((0, employeesUpdate_js_1.employeesUpdate)(client$, request, mergedOptions));
        },
    };
}
//# sourceMappingURL=employeesUpdate.js.map