"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.useGarnishmentsGet = useGarnishmentsGet;
exports.useGarnishmentsGetSuspense = useGarnishmentsGetSuspense;
exports.prefetchGarnishmentsGet = prefetchGarnishmentsGet;
exports.setGarnishmentsGetData = setGarnishmentsGetData;
exports.invalidateGarnishmentsGet = invalidateGarnishmentsGet;
exports.invalidateAllGarnishmentsGet = invalidateAllGarnishmentsGet;
exports.buildGarnishmentsGetQuery = buildGarnishmentsGetQuery;
exports.queryKeyGarnishmentsGet = queryKeyGarnishmentsGet;
const react_query_1 = require("@tanstack/react-query");
const garnishmentsGet_js_1 = require("../funcs/garnishmentsGet.js");
const primitives_js_1 = require("../lib/primitives.js");
const fp_js_1 = require("../types/fp.js");
const _context_js_1 = require("./_context.js");
/**
 * Get a garnishment
 *
 * @remarks
 * Garnishments, or employee deductions, are fixed amounts or percentages deducted from an employee’s pay. They can be deducted a specific number of times or on a recurring basis. Garnishments can also have maximum deductions on a yearly or per-pay-period bases. Common uses for garnishments are court-ordered payments for child support or back taxes. Some companies provide loans to their employees that are repaid via garnishments.
 *
 * scope: `garnishments:read`
 */
function useGarnishmentsGet(request, options) {
    const client = (0, _context_js_1.useGustoEmbeddedContext)();
    return (0, react_query_1.useQuery)({
        ...buildGarnishmentsGetQuery(client, request, options),
        ...options,
    });
}
/**
 * Get a garnishment
 *
 * @remarks
 * Garnishments, or employee deductions, are fixed amounts or percentages deducted from an employee’s pay. They can be deducted a specific number of times or on a recurring basis. Garnishments can also have maximum deductions on a yearly or per-pay-period bases. Common uses for garnishments are court-ordered payments for child support or back taxes. Some companies provide loans to their employees that are repaid via garnishments.
 *
 * scope: `garnishments:read`
 */
function useGarnishmentsGetSuspense(request, options) {
    const client = (0, _context_js_1.useGustoEmbeddedContext)();
    return (0, react_query_1.useSuspenseQuery)({
        ...buildGarnishmentsGetQuery(client, request, options),
        ...options,
    });
}
function prefetchGarnishmentsGet(queryClient, client$, request) {
    return queryClient.prefetchQuery({
        ...buildGarnishmentsGetQuery(client$, request),
    });
}
function setGarnishmentsGetData(client, queryKeyBase, data) {
    const key = queryKeyGarnishmentsGet(...queryKeyBase);
    return client.setQueryData(key, data);
}
function invalidateGarnishmentsGet(client, queryKeyBase, filters) {
    return client.invalidateQueries({
        ...filters,
        queryKey: ["@gusto/embedded-api", "Garnishments", "get", ...queryKeyBase],
    });
}
function invalidateAllGarnishmentsGet(client, filters) {
    return client.invalidateQueries({
        ...filters,
        queryKey: ["@gusto/embedded-api", "Garnishments", "get"],
    });
}
function buildGarnishmentsGetQuery(client$, request, options) {
    return {
        queryKey: queryKeyGarnishmentsGet(request.garnishmentId, {
            xGustoAPIVersion: request.xGustoAPIVersion,
        }),
        queryFn: async function garnishmentsGetQueryFn(ctx) {
            const sig = (0, primitives_js_1.combineSignals)(ctx.signal, options?.fetchOptions?.signal);
            const mergedOptions = {
                ...options,
                fetchOptions: { ...options?.fetchOptions, signal: sig },
            };
            return (0, fp_js_1.unwrapAsync)((0, garnishmentsGet_js_1.garnishmentsGet)(client$, request, mergedOptions));
        },
    };
}
function queryKeyGarnishmentsGet(garnishmentId, parameters) {
    return [
        "@gusto/embedded-api",
        "Garnishments",
        "get",
        garnishmentId,
        parameters,
    ];
}
//# sourceMappingURL=garnishmentsGet.js.map