"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.useGarnishmentsList = useGarnishmentsList;
exports.useGarnishmentsListSuspense = useGarnishmentsListSuspense;
exports.prefetchGarnishmentsList = prefetchGarnishmentsList;
exports.setGarnishmentsListData = setGarnishmentsListData;
exports.invalidateGarnishmentsList = invalidateGarnishmentsList;
exports.invalidateAllGarnishmentsList = invalidateAllGarnishmentsList;
exports.buildGarnishmentsListQuery = buildGarnishmentsListQuery;
exports.queryKeyGarnishmentsList = queryKeyGarnishmentsList;
const react_query_1 = require("@tanstack/react-query");
const garnishmentsList_js_1 = require("../funcs/garnishmentsList.js");
const primitives_js_1 = require("../lib/primitives.js");
const fp_js_1 = require("../types/fp.js");
const _context_js_1 = require("./_context.js");
/**
 * Get garnishments for an employee
 *
 * @remarks
 * Garnishments, or employee deductions, are fixed amounts or percentages deducted from an employee’s pay. They can be deducted a specific number of times or on a recurring basis. Garnishments can also have maximum deductions on a yearly or per-pay-period bases. Common uses for garnishments are court-ordered payments for child support or back taxes. Some companies provide loans to their employees that are repaid via garnishments.
 *
 * scope: `garnishments:read`
 */
function useGarnishmentsList(request, options) {
    const client = (0, _context_js_1.useGustoEmbeddedContext)();
    return (0, react_query_1.useQuery)({
        ...buildGarnishmentsListQuery(client, request, options),
        ...options,
    });
}
/**
 * Get garnishments for an employee
 *
 * @remarks
 * Garnishments, or employee deductions, are fixed amounts or percentages deducted from an employee’s pay. They can be deducted a specific number of times or on a recurring basis. Garnishments can also have maximum deductions on a yearly or per-pay-period bases. Common uses for garnishments are court-ordered payments for child support or back taxes. Some companies provide loans to their employees that are repaid via garnishments.
 *
 * scope: `garnishments:read`
 */
function useGarnishmentsListSuspense(request, options) {
    const client = (0, _context_js_1.useGustoEmbeddedContext)();
    return (0, react_query_1.useSuspenseQuery)({
        ...buildGarnishmentsListQuery(client, request, options),
        ...options,
    });
}
function prefetchGarnishmentsList(queryClient, client$, request) {
    return queryClient.prefetchQuery({
        ...buildGarnishmentsListQuery(client$, request),
    });
}
function setGarnishmentsListData(client, queryKeyBase, data) {
    const key = queryKeyGarnishmentsList(...queryKeyBase);
    return client.setQueryData(key, data);
}
function invalidateGarnishmentsList(client, queryKeyBase, filters) {
    return client.invalidateQueries({
        ...filters,
        queryKey: ["@gusto/embedded-api", "Garnishments", "list", ...queryKeyBase],
    });
}
function invalidateAllGarnishmentsList(client, filters) {
    return client.invalidateQueries({
        ...filters,
        queryKey: ["@gusto/embedded-api", "Garnishments", "list"],
    });
}
function buildGarnishmentsListQuery(client$, request, options) {
    return {
        queryKey: queryKeyGarnishmentsList(request.employeeId, {
            page: request.page,
            per: request.per,
            xGustoAPIVersion: request.xGustoAPIVersion,
        }),
        queryFn: async function garnishmentsListQueryFn(ctx) {
            const sig = (0, primitives_js_1.combineSignals)(ctx.signal, options?.fetchOptions?.signal);
            const mergedOptions = {
                ...options,
                fetchOptions: { ...options?.fetchOptions, signal: sig },
            };
            return (0, fp_js_1.unwrapAsync)((0, garnishmentsList_js_1.garnishmentsList)(client$, request, mergedOptions));
        },
    };
}
function queryKeyGarnishmentsList(employeeId, parameters) {
    return [
        "@gusto/embedded-api",
        "Garnishments",
        "list",
        employeeId,
        parameters,
    ];
}
//# sourceMappingURL=garnishmentsList.js.map