"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.useHolidayPayPoliciesDeleteMutation = useHolidayPayPoliciesDeleteMutation;
exports.mutationKeyHolidayPayPoliciesDelete = mutationKeyHolidayPayPoliciesDelete;
exports.buildHolidayPayPoliciesDeleteMutation = buildHolidayPayPoliciesDeleteMutation;
const react_query_1 = require("@tanstack/react-query");
const holidayPayPoliciesDelete_js_1 = require("../funcs/holidayPayPoliciesDelete.js");
const primitives_js_1 = require("../lib/primitives.js");
const fp_js_1 = require("../types/fp.js");
const _context_js_1 = require("./_context.js");
/**
 * Delete a company's holiday pay policy
 *
 * @remarks
 * Delete a company's holiday pay policy
 *
 * scope: `holiday_pay_policies:write`
 */
function useHolidayPayPoliciesDeleteMutation(options) {
    const client = (0, _context_js_1.useGustoEmbeddedContext)();
    return (0, react_query_1.useMutation)({
        ...buildHolidayPayPoliciesDeleteMutation(client, options),
        ...options,
    });
}
function mutationKeyHolidayPayPoliciesDelete() {
    return ["@gusto/embedded-api", "holidayPayPolicies", "delete"];
}
function buildHolidayPayPoliciesDeleteMutation(client$, hookOptions) {
    return {
        mutationKey: mutationKeyHolidayPayPoliciesDelete(),
        mutationFn: function holidayPayPoliciesDeleteMutationFn({ request, options, }) {
            const mergedOptions = {
                ...hookOptions,
                ...options,
                fetchOptions: {
                    ...hookOptions?.fetchOptions,
                    ...options?.fetchOptions,
                    signal: (0, primitives_js_1.combineSignals)(hookOptions?.fetchOptions?.signal, options?.fetchOptions?.signal),
                },
            };
            return (0, fp_js_1.unwrapAsync)((0, holidayPayPoliciesDelete_js_1.holidayPayPoliciesDelete)(client$, request, mergedOptions));
        },
    };
}
//# sourceMappingURL=holidayPayPoliciesDelete.js.map