"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.useIntrospectionGetInfo = useIntrospectionGetInfo;
exports.useIntrospectionGetInfoSuspense = useIntrospectionGetInfoSuspense;
exports.prefetchIntrospectionGetInfo = prefetchIntrospectionGetInfo;
exports.setIntrospectionGetInfoData = setIntrospectionGetInfoData;
exports.invalidateIntrospectionGetInfo = invalidateIntrospectionGetInfo;
exports.invalidateAllIntrospectionGetInfo = invalidateAllIntrospectionGetInfo;
exports.buildIntrospectionGetInfoQuery = buildIntrospectionGetInfoQuery;
exports.queryKeyIntrospectionGetInfo = queryKeyIntrospectionGetInfo;
const react_query_1 = require("@tanstack/react-query");
const introspectionGetInfo_js_1 = require("../funcs/introspectionGetInfo.js");
const primitives_js_1 = require("../lib/primitives.js");
const fp_js_1 = require("../types/fp.js");
const _context_js_1 = require("./_context.js");
/**
 * Get info about the current access token
 *
 * @remarks
 * Returns scope and resource information associated with the current access token.
 */
function useIntrospectionGetInfo(request, options) {
    const client = (0, _context_js_1.useGustoEmbeddedContext)();
    return (0, react_query_1.useQuery)({
        ...buildIntrospectionGetInfoQuery(client, request, options),
        ...options,
    });
}
/**
 * Get info about the current access token
 *
 * @remarks
 * Returns scope and resource information associated with the current access token.
 */
function useIntrospectionGetInfoSuspense(request, options) {
    const client = (0, _context_js_1.useGustoEmbeddedContext)();
    return (0, react_query_1.useSuspenseQuery)({
        ...buildIntrospectionGetInfoQuery(client, request, options),
        ...options,
    });
}
function prefetchIntrospectionGetInfo(queryClient, client$, request) {
    return queryClient.prefetchQuery({
        ...buildIntrospectionGetInfoQuery(client$, request),
    });
}
function setIntrospectionGetInfoData(client, queryKeyBase, data) {
    const key = queryKeyIntrospectionGetInfo(...queryKeyBase);
    return client.setQueryData(key, data);
}
function invalidateIntrospectionGetInfo(client, queryKeyBase, filters) {
    return client.invalidateQueries({
        ...filters,
        queryKey: [
            "@gusto/embedded-api",
            "Introspection",
            "getInfo",
            ...queryKeyBase,
        ],
    });
}
function invalidateAllIntrospectionGetInfo(client, filters) {
    return client.invalidateQueries({
        ...filters,
        queryKey: ["@gusto/embedded-api", "Introspection", "getInfo"],
    });
}
function buildIntrospectionGetInfoQuery(client$, request, options) {
    return {
        queryKey: queryKeyIntrospectionGetInfo({
            xGustoAPIVersion: request.xGustoAPIVersion,
        }),
        queryFn: async function introspectionGetInfoQueryFn(ctx) {
            const sig = (0, primitives_js_1.combineSignals)(ctx.signal, options?.fetchOptions?.signal);
            const mergedOptions = {
                ...options,
                fetchOptions: { ...options?.fetchOptions, signal: sig },
            };
            return (0, fp_js_1.unwrapAsync)((0, introspectionGetInfo_js_1.introspectionGetInfo)(client$, request, mergedOptions));
        },
    };
}
function queryKeyIntrospectionGetInfo(parameters) {
    return ["@gusto/embedded-api", "Introspection", "getInfo", parameters];
}
//# sourceMappingURL=introspectionGetInfo.js.map