"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.usePaySchedulesUpdateMutation = usePaySchedulesUpdateMutation;
exports.mutationKeyPaySchedulesUpdate = mutationKeyPaySchedulesUpdate;
exports.buildPaySchedulesUpdateMutation = buildPaySchedulesUpdateMutation;
const react_query_1 = require("@tanstack/react-query");
const paySchedulesUpdate_js_1 = require("../funcs/paySchedulesUpdate.js");
const primitives_js_1 = require("../lib/primitives.js");
const fp_js_1 = require("../types/fp.js");
const _context_js_1 = require("./_context.js");
/**
 * Update a pay schedule
 *
 * @remarks
 * Updates a pay schedule.
 *
 * scope: `pay_schedules:write`
 */
function usePaySchedulesUpdateMutation(options) {
    const client = (0, _context_js_1.useGustoEmbeddedContext)();
    return (0, react_query_1.useMutation)({
        ...buildPaySchedulesUpdateMutation(client, options),
        ...options,
    });
}
function mutationKeyPaySchedulesUpdate() {
    return ["@gusto/embedded-api", "paySchedules", "update"];
}
function buildPaySchedulesUpdateMutation(client$, hookOptions) {
    return {
        mutationKey: mutationKeyPaySchedulesUpdate(),
        mutationFn: function paySchedulesUpdateMutationFn({ request, options, }) {
            const mergedOptions = {
                ...hookOptions,
                ...options,
                fetchOptions: {
                    ...hookOptions?.fetchOptions,
                    ...options?.fetchOptions,
                    signal: (0, primitives_js_1.combineSignals)(hookOptions?.fetchOptions?.signal, options?.fetchOptions?.signal),
                },
            };
            return (0, fp_js_1.unwrapAsync)((0, paySchedulesUpdate_js_1.paySchedulesUpdate)(client$, request, mergedOptions));
        },
    };
}
//# sourceMappingURL=paySchedulesUpdate.js.map