/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type GetCompaniesCompanyUuidReportTemplatesReportTypeRequest = {
  /**
   * The UUID of the company
   */
  companyUuid: string;
  /**
   * The report type
   */
  reportType: string;
  /**
   * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
   */
  xGustoAPIVersion?: models.VersionHeader | undefined;
};

/** @internal */
export type GetCompaniesCompanyUuidReportTemplatesReportTypeRequest$Outbound = {
  company_uuid: string;
  report_type: string;
  "X-Gusto-API-Version": string;
};

/** @internal */
export const GetCompaniesCompanyUuidReportTemplatesReportTypeRequest$outboundSchema:
  z.ZodMiniType<
    GetCompaniesCompanyUuidReportTemplatesReportTypeRequest$Outbound,
    GetCompaniesCompanyUuidReportTemplatesReportTypeRequest
  > = z.pipe(
    z.object({
      companyUuid: z.string(),
      reportType: z.string(),
      xGustoAPIVersion: z._default(
        models.VersionHeader$outboundSchema,
        "2025-06-15",
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        companyUuid: "company_uuid",
        reportType: "report_type",
        xGustoAPIVersion: "X-Gusto-API-Version",
      });
    }),
  );

export function getCompaniesCompanyUuidReportTemplatesReportTypeRequestToJSON(
  getCompaniesCompanyUuidReportTemplatesReportTypeRequest:
    GetCompaniesCompanyUuidReportTemplatesReportTypeRequest,
): string {
  return JSON.stringify(
    GetCompaniesCompanyUuidReportTemplatesReportTypeRequest$outboundSchema
      .parse(getCompaniesCompanyUuidReportTemplatesReportTypeRequest),
  );
}
