/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as models from "../index.js";

export type PostV1WebhookSubscriptionSecurity = {
  systemAccessAuth: string;
};

export const PostV1WebhookSubscriptionSubscriptionType = {
  BankAccount: "BankAccount",
  Company: "Company",
  CompanyBenefit: "CompanyBenefit",
  Contractor: "Contractor",
  ContractorPayment: "ContractorPayment",
  Employee: "Employee",
  EmployeeBenefit: "EmployeeBenefit",
  EmployeeJobCompensation: "EmployeeJobCompensation",
  ExternalPayroll: "ExternalPayroll",
  Form: "Form",
  Location: "Location",
  Notification: "Notification",
  Payroll: "Payroll",
  PaySchedule: "PaySchedule",
  Signatory: "Signatory",
} as const;
export type PostV1WebhookSubscriptionSubscriptionType = ClosedEnum<
  typeof PostV1WebhookSubscriptionSubscriptionType
>;

export type PostV1WebhookSubscriptionRequestBody = {
  url: string;
  subscriptionTypes: Array<PostV1WebhookSubscriptionSubscriptionType>;
};

export type PostV1WebhookSubscriptionRequest = {
  /**
   * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
   */
  xGustoAPIVersion?: models.VersionHeader | undefined;
  body: PostV1WebhookSubscriptionRequestBody;
};

/** @internal */
export type PostV1WebhookSubscriptionSecurity$Outbound = {
  SystemAccessAuth: string;
};

/** @internal */
export const PostV1WebhookSubscriptionSecurity$outboundSchema: z.ZodMiniType<
  PostV1WebhookSubscriptionSecurity$Outbound,
  PostV1WebhookSubscriptionSecurity
> = z.pipe(
  z.object({
    systemAccessAuth: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      systemAccessAuth: "SystemAccessAuth",
    });
  }),
);

export function postV1WebhookSubscriptionSecurityToJSON(
  postV1WebhookSubscriptionSecurity: PostV1WebhookSubscriptionSecurity,
): string {
  return JSON.stringify(
    PostV1WebhookSubscriptionSecurity$outboundSchema.parse(
      postV1WebhookSubscriptionSecurity,
    ),
  );
}

/** @internal */
export const PostV1WebhookSubscriptionSubscriptionType$outboundSchema:
  z.ZodMiniEnum<typeof PostV1WebhookSubscriptionSubscriptionType> = z.enum(
    PostV1WebhookSubscriptionSubscriptionType,
  );

/** @internal */
export type PostV1WebhookSubscriptionRequestBody$Outbound = {
  url: string;
  subscription_types: Array<string>;
};

/** @internal */
export const PostV1WebhookSubscriptionRequestBody$outboundSchema: z.ZodMiniType<
  PostV1WebhookSubscriptionRequestBody$Outbound,
  PostV1WebhookSubscriptionRequestBody
> = z.pipe(
  z.object({
    url: z.string(),
    subscriptionTypes: z.array(
      PostV1WebhookSubscriptionSubscriptionType$outboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      subscriptionTypes: "subscription_types",
    });
  }),
);

export function postV1WebhookSubscriptionRequestBodyToJSON(
  postV1WebhookSubscriptionRequestBody: PostV1WebhookSubscriptionRequestBody,
): string {
  return JSON.stringify(
    PostV1WebhookSubscriptionRequestBody$outboundSchema.parse(
      postV1WebhookSubscriptionRequestBody,
    ),
  );
}

/** @internal */
export type PostV1WebhookSubscriptionRequest$Outbound = {
  "X-Gusto-API-Version": string;
  body: PostV1WebhookSubscriptionRequestBody$Outbound;
};

/** @internal */
export const PostV1WebhookSubscriptionRequest$outboundSchema: z.ZodMiniType<
  PostV1WebhookSubscriptionRequest$Outbound,
  PostV1WebhookSubscriptionRequest
> = z.pipe(
  z.object({
    xGustoAPIVersion: z._default(
      models.VersionHeader$outboundSchema,
      "2025-06-15",
    ),
    body: z.lazy(() => PostV1WebhookSubscriptionRequestBody$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      xGustoAPIVersion: "X-Gusto-API-Version",
    });
  }),
);

export function postV1WebhookSubscriptionRequestToJSON(
  postV1WebhookSubscriptionRequest: PostV1WebhookSubscriptionRequest,
): string {
  return JSON.stringify(
    PostV1WebhookSubscriptionRequest$outboundSchema.parse(
      postV1WebhookSubscriptionRequest,
    ),
  );
}
