/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export const PutV1HomeAddressesHomeAddressUuidXGustoAPIVersion = {
  TwoThousandAndTwentyFiveMinus06Minus15: "2025-06-15",
} as const;
/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export type PutV1HomeAddressesHomeAddressUuidXGustoAPIVersion = ClosedEnum<
  typeof PutV1HomeAddressesHomeAddressUuidXGustoAPIVersion
>;

export type PutV1HomeAddressesHomeAddressUuidRequestBody = {
  /**
   * The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field.
   */
  version: string;
  street1?: string | undefined;
  street2?: string | null | undefined;
  city?: string | undefined;
  state?: string | undefined;
  zip?: string | undefined;
  effectiveDate?: Date | null | undefined;
  courtesyWithholding?: boolean | undefined;
};

export type PutV1HomeAddressesHomeAddressUuidRequest = {
  /**
   * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
   */
  xGustoAPIVersion?:
    | PutV1HomeAddressesHomeAddressUuidXGustoAPIVersion
    | undefined;
  /**
   * The UUID of the home address
   */
  homeAddressUuid: string;
  body: PutV1HomeAddressesHomeAddressUuidRequestBody;
};

/** @internal */
export const PutV1HomeAddressesHomeAddressUuidXGustoAPIVersion$outboundSchema:
  z.ZodMiniEnum<typeof PutV1HomeAddressesHomeAddressUuidXGustoAPIVersion> = z
    .enum(PutV1HomeAddressesHomeAddressUuidXGustoAPIVersion);

/** @internal */
export type PutV1HomeAddressesHomeAddressUuidRequestBody$Outbound = {
  version: string;
  street_1?: string | undefined;
  street_2?: string | null | undefined;
  city?: string | undefined;
  state?: string | undefined;
  zip?: string | undefined;
  effective_date?: string | null | undefined;
  courtesy_withholding?: boolean | undefined;
};

/** @internal */
export const PutV1HomeAddressesHomeAddressUuidRequestBody$outboundSchema:
  z.ZodMiniType<
    PutV1HomeAddressesHomeAddressUuidRequestBody$Outbound,
    PutV1HomeAddressesHomeAddressUuidRequestBody
  > = z.pipe(
    z.object({
      version: z.string(),
      street1: z.optional(z.string()),
      street2: z.optional(z.nullable(z.string())),
      city: z.optional(z.string()),
      state: z.optional(z.string()),
      zip: z.optional(z.string()),
      effectiveDate: z.optional(z.nullable(z.pipe(
        z.date(),
        z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
      ))),
      courtesyWithholding: z.optional(z.boolean()),
    }),
    z.transform((v) => {
      return remap$(v, {
        street1: "street_1",
        street2: "street_2",
        effectiveDate: "effective_date",
        courtesyWithholding: "courtesy_withholding",
      });
    }),
  );

export function putV1HomeAddressesHomeAddressUuidRequestBodyToJSON(
  putV1HomeAddressesHomeAddressUuidRequestBody:
    PutV1HomeAddressesHomeAddressUuidRequestBody,
): string {
  return JSON.stringify(
    PutV1HomeAddressesHomeAddressUuidRequestBody$outboundSchema.parse(
      putV1HomeAddressesHomeAddressUuidRequestBody,
    ),
  );
}

/** @internal */
export type PutV1HomeAddressesHomeAddressUuidRequest$Outbound = {
  "X-Gusto-API-Version": string;
  home_address_uuid: string;
  body: PutV1HomeAddressesHomeAddressUuidRequestBody$Outbound;
};

/** @internal */
export const PutV1HomeAddressesHomeAddressUuidRequest$outboundSchema:
  z.ZodMiniType<
    PutV1HomeAddressesHomeAddressUuidRequest$Outbound,
    PutV1HomeAddressesHomeAddressUuidRequest
  > = z.pipe(
    z.object({
      xGustoAPIVersion: z._default(
        PutV1HomeAddressesHomeAddressUuidXGustoAPIVersion$outboundSchema,
        "2025-06-15",
      ),
      homeAddressUuid: z.string(),
      body: z.lazy(() =>
        PutV1HomeAddressesHomeAddressUuidRequestBody$outboundSchema
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        xGustoAPIVersion: "X-Gusto-API-Version",
        homeAddressUuid: "home_address_uuid",
      });
    }),
  );

export function putV1HomeAddressesHomeAddressUuidRequestToJSON(
  putV1HomeAddressesHomeAddressUuidRequest:
    PutV1HomeAddressesHomeAddressUuidRequest,
): string {
  return JSON.stringify(
    PutV1HomeAddressesHomeAddressUuidRequest$outboundSchema.parse(
      putV1HomeAddressesHomeAddressUuidRequest,
    ),
  );
}
