"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.EmployeeAddress$ = exports.EmployeeAddress$outboundSchema = exports.EmployeeAddress$inboundSchema = void 0;
exports.employeeAddressToJSON = employeeAddressToJSON;
exports.employeeAddressFromJSON = employeeAddressFromJSON;
const z = __importStar(require("zod"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const rfcdate_js_1 = require("../../types/rfcdate.js");
/** @internal */
exports.EmployeeAddress$inboundSchema = z.object({
    version: z.string().optional(),
    street_1: z.string().optional(),
    street_2: z.nullable(z.string()).optional(),
    city: z.string().optional(),
    state: z.string().optional(),
    zip: z.string().optional(),
    country: z.string().default("USA"),
    active: z.boolean().optional(),
    uuid: z.string().optional(),
    employee_uuid: z.string().optional(),
    effective_date: z.string().transform(v => new rfcdate_js_1.RFCDate(v)).optional(),
    courtesy_withholding: z.boolean().optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "street_1": "street1",
        "street_2": "street2",
        "employee_uuid": "employeeUuid",
        "effective_date": "effectiveDate",
        "courtesy_withholding": "courtesyWithholding",
    });
});
/** @internal */
exports.EmployeeAddress$outboundSchema = z.object({
    version: z.string().optional(),
    street1: z.string().optional(),
    street2: z.nullable(z.string()).optional(),
    city: z.string().optional(),
    state: z.string().optional(),
    zip: z.string().optional(),
    country: z.string().default("USA"),
    active: z.boolean().optional(),
    uuid: z.string().optional(),
    employeeUuid: z.string().optional(),
    effectiveDate: z.instanceof(rfcdate_js_1.RFCDate).transform(v => v.toString()).optional(),
    courtesyWithholding: z.boolean().optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        street1: "street_1",
        street2: "street_2",
        employeeUuid: "employee_uuid",
        effectiveDate: "effective_date",
        courtesyWithholding: "courtesy_withholding",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var EmployeeAddress$;
(function (EmployeeAddress$) {
    /** @deprecated use `EmployeeAddress$inboundSchema` instead. */
    EmployeeAddress$.inboundSchema = exports.EmployeeAddress$inboundSchema;
    /** @deprecated use `EmployeeAddress$outboundSchema` instead. */
    EmployeeAddress$.outboundSchema = exports.EmployeeAddress$outboundSchema;
})(EmployeeAddress$ || (exports.EmployeeAddress$ = EmployeeAddress$ = {}));
function employeeAddressToJSON(employeeAddress) {
    return JSON.stringify(exports.EmployeeAddress$outboundSchema.parse(employeeAddress));
}
function employeeAddressFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.EmployeeAddress$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'EmployeeAddress' from JSON`);
}
//# sourceMappingURL=employeeaddress.js.map