"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.Employee$ = exports.Employee$outboundSchema = exports.Employee$inboundSchema = exports.CurrentEmploymentStatus$ = exports.CurrentEmploymentStatus$outboundSchema = exports.CurrentEmploymentStatus$inboundSchema = exports.PaymentMethod$ = exports.PaymentMethod$outboundSchema = exports.PaymentMethod$inboundSchema = exports.OnboardingDocumentsConfig$ = exports.OnboardingDocumentsConfig$outboundSchema = exports.OnboardingDocumentsConfig$inboundSchema = exports.OnboardingStatus$ = exports.OnboardingStatus$outboundSchema = exports.OnboardingStatus$inboundSchema = exports.CurrentEmploymentStatus = exports.PaymentMethod = exports.OnboardingStatus = void 0;
exports.onboardingDocumentsConfigToJSON = onboardingDocumentsConfigToJSON;
exports.onboardingDocumentsConfigFromJSON = onboardingDocumentsConfigFromJSON;
exports.employeeToJSON = employeeToJSON;
exports.employeeFromJSON = employeeFromJSON;
const z = __importStar(require("zod"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const employeecustomfield_js_1 = require("./employeecustomfield.js");
const garnishment_js_1 = require("./garnishment.js");
const job_js_1 = require("./job.js");
const paidtimeoff_js_1 = require("./paidtimeoff.js");
const termination_js_1 = require("./termination.js");
/**
 * The current onboarding status of the employee
 */
exports.OnboardingStatus = {
    OnboardingCompleted: "onboarding_completed",
    AdminOnboardingIncomplete: "admin_onboarding_incomplete",
    SelfOnboardingPendingInvite: "self_onboarding_pending_invite",
    SelfOnboardingInvited: "self_onboarding_invited",
    SelfOnboardingInvitedStarted: "self_onboarding_invited_started",
    SelfOnboardingInvitedOverdue: "self_onboarding_invited_overdue",
    SelfOnboardingCompletedByEmployee: "self_onboarding_completed_by_employee",
    SelfOnboardingAwaitingAdminReview: "self_onboarding_awaiting_admin_review",
};
/**
 * The employee's payment method
 */
exports.PaymentMethod = {
    DirectDeposit: "Direct Deposit",
    Check: "Check",
};
/**
 * The current employment status of the employee. Full-time employees work 30+ hours per week. Part-time employees are split into two groups: those that work 20-29 hours a week, and those that work under 20 hours a week. Variable employees have hours that vary each week. Seasonal employees are hired for 6 months of the year or less.
 */
exports.CurrentEmploymentStatus = {
    FullTime: "full_time",
    PartTimeUnderTwentyHours: "part_time_under_twenty_hours",
    PartTimeTwentyPlusHours: "part_time_twenty_plus_hours",
    Variable: "variable",
    Seasonal: "seasonal",
};
/** @internal */
exports.OnboardingStatus$inboundSchema = z.nativeEnum(exports.OnboardingStatus);
/** @internal */
exports.OnboardingStatus$outboundSchema = exports.OnboardingStatus$inboundSchema;
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var OnboardingStatus$;
(function (OnboardingStatus$) {
    /** @deprecated use `OnboardingStatus$inboundSchema` instead. */
    OnboardingStatus$.inboundSchema = exports.OnboardingStatus$inboundSchema;
    /** @deprecated use `OnboardingStatus$outboundSchema` instead. */
    OnboardingStatus$.outboundSchema = exports.OnboardingStatus$outboundSchema;
})(OnboardingStatus$ || (exports.OnboardingStatus$ = OnboardingStatus$ = {}));
/** @internal */
exports.OnboardingDocumentsConfig$inboundSchema = z.object({
    uuid: z.nullable(z.string()).optional(),
    i9_document: z.boolean().optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "i9_document": "i9Document",
    });
});
/** @internal */
exports.OnboardingDocumentsConfig$outboundSchema = z.object({
    uuid: z.nullable(z.string()).optional(),
    i9Document: z.boolean().optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        i9Document: "i9_document",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var OnboardingDocumentsConfig$;
(function (OnboardingDocumentsConfig$) {
    /** @deprecated use `OnboardingDocumentsConfig$inboundSchema` instead. */
    OnboardingDocumentsConfig$.inboundSchema = exports.OnboardingDocumentsConfig$inboundSchema;
    /** @deprecated use `OnboardingDocumentsConfig$outboundSchema` instead. */
    OnboardingDocumentsConfig$.outboundSchema = exports.OnboardingDocumentsConfig$outboundSchema;
})(OnboardingDocumentsConfig$ || (exports.OnboardingDocumentsConfig$ = OnboardingDocumentsConfig$ = {}));
function onboardingDocumentsConfigToJSON(onboardingDocumentsConfig) {
    return JSON.stringify(exports.OnboardingDocumentsConfig$outboundSchema.parse(onboardingDocumentsConfig));
}
function onboardingDocumentsConfigFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.OnboardingDocumentsConfig$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'OnboardingDocumentsConfig' from JSON`);
}
/** @internal */
exports.PaymentMethod$inboundSchema = z.nativeEnum(exports.PaymentMethod);
/** @internal */
exports.PaymentMethod$outboundSchema = exports.PaymentMethod$inboundSchema;
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var PaymentMethod$;
(function (PaymentMethod$) {
    /** @deprecated use `PaymentMethod$inboundSchema` instead. */
    PaymentMethod$.inboundSchema = exports.PaymentMethod$inboundSchema;
    /** @deprecated use `PaymentMethod$outboundSchema` instead. */
    PaymentMethod$.outboundSchema = exports.PaymentMethod$outboundSchema;
})(PaymentMethod$ || (exports.PaymentMethod$ = PaymentMethod$ = {}));
/** @internal */
exports.CurrentEmploymentStatus$inboundSchema = z.nativeEnum(exports.CurrentEmploymentStatus);
/** @internal */
exports.CurrentEmploymentStatus$outboundSchema = exports.CurrentEmploymentStatus$inboundSchema;
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var CurrentEmploymentStatus$;
(function (CurrentEmploymentStatus$) {
    /** @deprecated use `CurrentEmploymentStatus$inboundSchema` instead. */
    CurrentEmploymentStatus$.inboundSchema = exports.CurrentEmploymentStatus$inboundSchema;
    /** @deprecated use `CurrentEmploymentStatus$outboundSchema` instead. */
    CurrentEmploymentStatus$.outboundSchema = exports.CurrentEmploymentStatus$outboundSchema;
})(CurrentEmploymentStatus$ || (exports.CurrentEmploymentStatus$ = CurrentEmploymentStatus$ = {}));
/** @internal */
exports.Employee$inboundSchema = z.object({
    uuid: z.string(),
    first_name: z.string(),
    middle_initial: z.nullable(z.string()).optional(),
    last_name: z.string(),
    email: z.nullable(z.string()).optional(),
    company_uuid: z.string().optional(),
    manager_uuid: z.nullable(z.string()).optional(),
    version: z.string().optional(),
    department: z.nullable(z.string()).optional(),
    terminated: z.boolean().optional(),
    two_percent_shareholder: z.nullable(z.boolean()).optional(),
    onboarded: z.boolean().optional(),
    onboarding_status: exports.OnboardingStatus$inboundSchema.optional(),
    onboarding_documents_config: z.lazy(() => exports.OnboardingDocumentsConfig$inboundSchema).optional(),
    jobs: z.array(job_js_1.Job$inboundSchema).optional(),
    eligible_paid_time_off: z.array(paidtimeoff_js_1.PaidTimeOff$inboundSchema).optional(),
    terminations: z.array(termination_js_1.Termination$inboundSchema).optional(),
    garnishments: z.array(garnishment_js_1.Garnishment$inboundSchema).optional(),
    custom_fields: z.array(employeecustomfield_js_1.EmployeeCustomField$inboundSchema).optional(),
    date_of_birth: z.nullable(z.string()).optional(),
    has_ssn: z.boolean().optional(),
    ssn: z.string().optional(),
    phone: z.nullable(z.string()).optional(),
    preferred_first_name: z.nullable(z.string()).optional(),
    payment_method: exports.PaymentMethod$inboundSchema.default("Check"),
    work_email: z.nullable(z.string()).optional(),
    current_employment_status: z.nullable(exports.CurrentEmploymentStatus$inboundSchema)
        .optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "first_name": "firstName",
        "middle_initial": "middleInitial",
        "last_name": "lastName",
        "company_uuid": "companyUuid",
        "manager_uuid": "managerUuid",
        "two_percent_shareholder": "twoPercentShareholder",
        "onboarding_status": "onboardingStatus",
        "onboarding_documents_config": "onboardingDocumentsConfig",
        "eligible_paid_time_off": "eligiblePaidTimeOff",
        "custom_fields": "customFields",
        "date_of_birth": "dateOfBirth",
        "has_ssn": "hasSsn",
        "preferred_first_name": "preferredFirstName",
        "payment_method": "paymentMethod",
        "work_email": "workEmail",
        "current_employment_status": "currentEmploymentStatus",
    });
});
/** @internal */
exports.Employee$outboundSchema = z.object({
    uuid: z.string(),
    firstName: z.string(),
    middleInitial: z.nullable(z.string()).optional(),
    lastName: z.string(),
    email: z.nullable(z.string()).optional(),
    companyUuid: z.string().optional(),
    managerUuid: z.nullable(z.string()).optional(),
    version: z.string().optional(),
    department: z.nullable(z.string()).optional(),
    terminated: z.boolean().optional(),
    twoPercentShareholder: z.nullable(z.boolean()).optional(),
    onboarded: z.boolean().optional(),
    onboardingStatus: exports.OnboardingStatus$outboundSchema.optional(),
    onboardingDocumentsConfig: z.lazy(() => exports.OnboardingDocumentsConfig$outboundSchema).optional(),
    jobs: z.array(job_js_1.Job$outboundSchema).optional(),
    eligiblePaidTimeOff: z.array(paidtimeoff_js_1.PaidTimeOff$outboundSchema).optional(),
    terminations: z.array(termination_js_1.Termination$outboundSchema).optional(),
    garnishments: z.array(garnishment_js_1.Garnishment$outboundSchema).optional(),
    customFields: z.array(employeecustomfield_js_1.EmployeeCustomField$outboundSchema).optional(),
    dateOfBirth: z.nullable(z.string()).optional(),
    hasSsn: z.boolean().optional(),
    ssn: z.string().optional(),
    phone: z.nullable(z.string()).optional(),
    preferredFirstName: z.nullable(z.string()).optional(),
    paymentMethod: exports.PaymentMethod$outboundSchema.default("Check"),
    workEmail: z.nullable(z.string()).optional(),
    currentEmploymentStatus: z.nullable(exports.CurrentEmploymentStatus$outboundSchema)
        .optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        firstName: "first_name",
        middleInitial: "middle_initial",
        lastName: "last_name",
        companyUuid: "company_uuid",
        managerUuid: "manager_uuid",
        twoPercentShareholder: "two_percent_shareholder",
        onboardingStatus: "onboarding_status",
        onboardingDocumentsConfig: "onboarding_documents_config",
        eligiblePaidTimeOff: "eligible_paid_time_off",
        customFields: "custom_fields",
        dateOfBirth: "date_of_birth",
        hasSsn: "has_ssn",
        preferredFirstName: "preferred_first_name",
        paymentMethod: "payment_method",
        workEmail: "work_email",
        currentEmploymentStatus: "current_employment_status",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var Employee$;
(function (Employee$) {
    /** @deprecated use `Employee$inboundSchema` instead. */
    Employee$.inboundSchema = exports.Employee$inboundSchema;
    /** @deprecated use `Employee$outboundSchema` instead. */
    Employee$.outboundSchema = exports.Employee$outboundSchema;
})(Employee$ || (exports.Employee$ = Employee$ = {}));
function employeeToJSON(employee) {
    return JSON.stringify(exports.Employee$outboundSchema.parse(employee));
}
function employeeFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.Employee$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'Employee' from JSON`);
}
//# sourceMappingURL=employee.js.map