"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.PaidTimeOff$ = exports.PaidTimeOff$outboundSchema = exports.PaidTimeOff$inboundSchema = exports.Name$ = exports.Name$outboundSchema = exports.Name$inboundSchema = exports.Name = void 0;
exports.paidTimeOffToJSON = paidTimeOffToJSON;
exports.paidTimeOffFromJSON = paidTimeOffFromJSON;
const z = __importStar(require("zod"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
/**
 * The name of the paid time off type.
 */
exports.Name = {
    VacationHours: "Vacation Hours",
    SickHours: "Sick Hours",
    HolidayHours: "Holiday Hours",
};
/** @internal */
exports.Name$inboundSchema = z.nativeEnum(exports.Name);
/** @internal */
exports.Name$outboundSchema = exports.Name$inboundSchema;
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var Name$;
(function (Name$) {
    /** @deprecated use `Name$inboundSchema` instead. */
    Name$.inboundSchema = exports.Name$inboundSchema;
    /** @deprecated use `Name$outboundSchema` instead. */
    Name$.outboundSchema = exports.Name$outboundSchema;
})(Name$ || (exports.Name$ = Name$ = {}));
/** @internal */
exports.PaidTimeOff$inboundSchema = z.object({
    name: exports.Name$inboundSchema.optional(),
    policy_name: z.string().optional(),
    policy_uuid: z.string().optional(),
    accrual_unit: z.string().optional(),
    accrual_rate: z.string().optional(),
    accrual_method: z.string().optional(),
    accrual_period: z.string().optional(),
    accrual_balance: z.string().optional(),
    maximum_accrual_balance: z.nullable(z.string()).optional(),
    paid_at_termination: z.boolean().optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "policy_name": "policyName",
        "policy_uuid": "policyUuid",
        "accrual_unit": "accrualUnit",
        "accrual_rate": "accrualRate",
        "accrual_method": "accrualMethod",
        "accrual_period": "accrualPeriod",
        "accrual_balance": "accrualBalance",
        "maximum_accrual_balance": "maximumAccrualBalance",
        "paid_at_termination": "paidAtTermination",
    });
});
/** @internal */
exports.PaidTimeOff$outboundSchema = z.object({
    name: exports.Name$outboundSchema.optional(),
    policyName: z.string().optional(),
    policyUuid: z.string().optional(),
    accrualUnit: z.string().optional(),
    accrualRate: z.string().optional(),
    accrualMethod: z.string().optional(),
    accrualPeriod: z.string().optional(),
    accrualBalance: z.string().optional(),
    maximumAccrualBalance: z.nullable(z.string()).optional(),
    paidAtTermination: z.boolean().optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        policyName: "policy_name",
        policyUuid: "policy_uuid",
        accrualUnit: "accrual_unit",
        accrualRate: "accrual_rate",
        accrualMethod: "accrual_method",
        accrualPeriod: "accrual_period",
        accrualBalance: "accrual_balance",
        maximumAccrualBalance: "maximum_accrual_balance",
        paidAtTermination: "paid_at_termination",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
var PaidTimeOff$;
(function (PaidTimeOff$) {
    /** @deprecated use `PaidTimeOff$inboundSchema` instead. */
    PaidTimeOff$.inboundSchema = exports.PaidTimeOff$inboundSchema;
    /** @deprecated use `PaidTimeOff$outboundSchema` instead. */
    PaidTimeOff$.outboundSchema = exports.PaidTimeOff$outboundSchema;
})(PaidTimeOff$ || (exports.PaidTimeOff$ = PaidTimeOff$ = {}));
function paidTimeOffToJSON(paidTimeOff) {
    return JSON.stringify(exports.PaidTimeOff$outboundSchema.parse(paidTimeOff));
}
function paidTimeOffFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.PaidTimeOff$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PaidTimeOff' from JSON`);
}
//# sourceMappingURL=paidtimeoff.js.map