/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";
import { SDKError } from "./sdk-error.js";

/**
 * Not Found
 *
 * @remarks
 *
 * The requested resource does not exist. Make sure the provided ID/UUID is valid.
 */
export type NotFoundErrorObjectData = {
  errors: Array<models.NotFoundErrorObjectError>;
};

/**
 * Not Found
 *
 * @remarks
 *
 * The requested resource does not exist. Make sure the provided ID/UUID is valid.
 */
export class NotFoundErrorObject extends SDKError {
  errors: Array<models.NotFoundErrorObjectError>;

  /** The original data that was passed to this error instance. */
  data$: NotFoundErrorObjectData;

  constructor(
    err: NotFoundErrorObjectData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.errors = err.errors;

    this.name = "NotFoundErrorObject";
  }
}

/** @internal */
export const NotFoundErrorObject$inboundSchema: z.ZodMiniType<
  NotFoundErrorObject,
  unknown
> = z.pipe(
  z.object({
    errors: z.array(
      z.lazy(() => models.NotFoundErrorObjectError$inboundSchema),
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new NotFoundErrorObject(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
