/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { companiesGetCustomFields } from "../funcs/companiesGetCustomFields.js";
import { combineSignals } from "../lib/primitives.js";
import { unwrapAsync } from "../types/fp.js";
export function prefetchCompaniesGetCustomFields(queryClient, client$, request, options) {
    return queryClient.prefetchQuery({
        ...buildCompaniesGetCustomFieldsQuery(client$, request, options),
    });
}
export function buildCompaniesGetCustomFieldsQuery(client$, request, options) {
    return {
        queryKey: queryKeyCompaniesGetCustomFields(request.companyId, {
            page: request.page,
            per: request.per,
            xGustoAPIVersion: request.xGustoAPIVersion,
        }),
        queryFn: async function companiesGetCustomFieldsQueryFn(ctx) {
            const sig = combineSignals(ctx.signal, options?.signal, options?.fetchOptions?.signal);
            const mergedOptions = {
                ...options?.fetchOptions,
                ...options,
                signal: sig,
            };
            return unwrapAsync(companiesGetCustomFields(client$, request, mergedOptions));
        },
    };
}
export function queryKeyCompaniesGetCustomFields(companyId, parameters) {
    return [
        "@gusto/embedded-api",
        "Companies",
        "getCustomFields",
        companyId,
        parameters,
    ];
}
//# sourceMappingURL=companiesGetCustomFields.core.js.map