/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { useQuery, useSuspenseQuery, } from "@tanstack/react-query";
import { useGustoEmbeddedContext } from "./_context.js";
import { buildCompaniesGetQuery, prefetchCompaniesGet, queryKeyCompaniesGet, } from "./companiesGet.core.js";
export { buildCompaniesGetQuery, prefetchCompaniesGet, queryKeyCompaniesGet, };
/**
 * Get a company
 *
 * @remarks
 * Get a company.
 *
 * The employees:read scope is required to return home_address and non-work locations.
 * The company_admin:read scope is required to return primary_payroll_admin.
 * The signatories:read scope is required to return primary_signatory.
 *
 * scope: `companies:read`
 */
export function useCompaniesGet(request, options) {
    const client = useGustoEmbeddedContext();
    return useQuery({
        ...buildCompaniesGetQuery(client, request, options),
        ...options,
    });
}
/**
 * Get a company
 *
 * @remarks
 * Get a company.
 *
 * The employees:read scope is required to return home_address and non-work locations.
 * The company_admin:read scope is required to return primary_payroll_admin.
 * The signatories:read scope is required to return primary_signatory.
 *
 * scope: `companies:read`
 */
export function useCompaniesGetSuspense(request, options) {
    const client = useGustoEmbeddedContext();
    return useSuspenseQuery({
        ...buildCompaniesGetQuery(client, request, options),
        ...options,
    });
}
export function setCompaniesGetData(client, queryKeyBase, data) {
    const key = queryKeyCompaniesGet(...queryKeyBase);
    return client.setQueryData(key, data);
}
export function invalidateCompaniesGet(client, queryKeyBase, filters) {
    return client.invalidateQueries({
        ...filters,
        queryKey: ["@gusto/embedded-api", "Companies", "get", ...queryKeyBase],
    });
}
export function invalidateAllCompaniesGet(client, filters) {
    return client.invalidateQueries({
        ...filters,
        queryKey: ["@gusto/embedded-api", "Companies", "get"],
    });
}
//# sourceMappingURL=companiesGet.js.map