/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { useMutation, } from "@tanstack/react-query";
import { contractorsUpdate } from "../funcs/contractorsUpdate.js";
import { combineSignals } from "../lib/primitives.js";
import { unwrapAsync } from "../types/fp.js";
import { useGustoEmbeddedContext } from "./_context.js";
/**
 * Update a contractor
 *
 * @remarks
 * Update a contractor.
 *
 * > 🚧 Warning
 * >
 * > Watch out when changing a contractor's type (when the contractor is finished onboarding). Specifically, changing contractor type can be dangerous since Gusto won't recognize and file two separate 1099s if they simply change from business to individual
 *
 * scope: `contractors:write`
 */
export function useContractorsUpdateMutation(options) {
    const client = useGustoEmbeddedContext();
    return useMutation({
        ...buildContractorsUpdateMutation(client, options),
        ...options,
    });
}
export function mutationKeyContractorsUpdate() {
    return ["@gusto/embedded-api", "Contractors", "update"];
}
export function buildContractorsUpdateMutation(client$, hookOptions) {
    return {
        mutationKey: mutationKeyContractorsUpdate(),
        mutationFn: function contractorsUpdateMutationFn({ request, options, }) {
            const mergedOptions = {
                ...hookOptions,
                ...options,
                fetchOptions: {
                    ...hookOptions?.fetchOptions,
                    ...options?.fetchOptions,
                    signal: combineSignals(hookOptions?.fetchOptions?.signal, options?.fetchOptions?.signal),
                },
            };
            return unwrapAsync(contractorsUpdate(client$, request, mergedOptions));
        },
    };
}
//# sourceMappingURL=contractorsUpdate.js.map