/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { useQuery, useSuspenseQuery, } from "@tanstack/react-query";
import { useGustoEmbeddedContext } from "./_context.js";
import { buildEmployeeAddressesRetrieveWorkAddressQuery, prefetchEmployeeAddressesRetrieveWorkAddress, queryKeyEmployeeAddressesRetrieveWorkAddress, } from "./employeeAddressesRetrieveWorkAddress.core.js";
export { buildEmployeeAddressesRetrieveWorkAddressQuery, prefetchEmployeeAddressesRetrieveWorkAddress, queryKeyEmployeeAddressesRetrieveWorkAddress, };
/**
 * Get an employee work address
 *
 * @remarks
 * The work address of an employee is used for payroll tax purposes.
 *
 * scope: `employees:read`
 */
export function useEmployeeAddressesRetrieveWorkAddress(request, options) {
    const client = useGustoEmbeddedContext();
    return useQuery({
        ...buildEmployeeAddressesRetrieveWorkAddressQuery(client, request, options),
        ...options,
    });
}
/**
 * Get an employee work address
 *
 * @remarks
 * The work address of an employee is used for payroll tax purposes.
 *
 * scope: `employees:read`
 */
export function useEmployeeAddressesRetrieveWorkAddressSuspense(request, options) {
    const client = useGustoEmbeddedContext();
    return useSuspenseQuery({
        ...buildEmployeeAddressesRetrieveWorkAddressQuery(client, request, options),
        ...options,
    });
}
export function setEmployeeAddressesRetrieveWorkAddressData(client, queryKeyBase, data) {
    const key = queryKeyEmployeeAddressesRetrieveWorkAddress(...queryKeyBase);
    return client.setQueryData(key, data);
}
export function invalidateEmployeeAddressesRetrieveWorkAddress(client, queryKeyBase, filters) {
    return client.invalidateQueries({
        ...filters,
        queryKey: [
            "@gusto/embedded-api",
            "employeeAddresses",
            "retrieveWorkAddress",
            ...queryKeyBase,
        ],
    });
}
export function invalidateAllEmployeeAddressesRetrieveWorkAddress(client, filters) {
    return client.invalidateQueries({
        ...filters,
        queryKey: [
            "@gusto/embedded-api",
            "employeeAddresses",
            "retrieveWorkAddress",
        ],
    });
}
//# sourceMappingURL=employeeAddressesRetrieveWorkAddress.js.map