/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { employeeAddressesGet } from "../funcs/employeeAddressesGet.js";
import { combineSignals } from "../lib/primitives.js";
import { unwrapAsync } from "../types/fp.js";
export function prefetchEmployeeAddressesGet(queryClient, client$, request, options) {
    return queryClient.prefetchQuery({
        ...buildEmployeeAddressesGetQuery(client$, request, options),
    });
}
export function buildEmployeeAddressesGetQuery(client$, request, options) {
    return {
        queryKey: queryKeyEmployeeAddressesGet(request.employeeId, {
            xGustoAPIVersion: request.xGustoAPIVersion,
        }),
        queryFn: async function employeeAddressesGetQueryFn(ctx) {
            const sig = combineSignals(ctx.signal, options?.signal, options?.fetchOptions?.signal);
            const mergedOptions = {
                ...options?.fetchOptions,
                ...options,
                signal: sig,
            };
            return unwrapAsync(employeeAddressesGet(client$, request, mergedOptions));
        },
    };
}
export function queryKeyEmployeeAddressesGet(employeeId, parameters) {
    return [
        "@gusto/embedded-api",
        "employeeAddresses",
        "get",
        employeeId,
        parameters,
    ];
}
//# sourceMappingURL=employeeAddressesGet.core.js.map