/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { useQuery, useSuspenseQuery, } from "@tanstack/react-query";
import { useGustoEmbeddedContext } from "./_context.js";
import { buildNotificationsGetCompanyNotificationsQuery, prefetchNotificationsGetCompanyNotifications, queryKeyNotificationsGetCompanyNotifications, } from "./notificationsGetCompanyNotifications.core.js";
export { buildNotificationsGetCompanyNotificationsQuery, prefetchNotificationsGetCompanyNotifications, queryKeyNotificationsGetCompanyNotifications, };
/**
 * Get notifications for company
 *
 * @remarks
 * Returns all notifications relevant for the given company.
 *
 * scope: `notifications:read`
 */
export function useNotificationsGetCompanyNotifications(request, options) {
    const client = useGustoEmbeddedContext();
    return useQuery({
        ...buildNotificationsGetCompanyNotificationsQuery(client, request, options),
        ...options,
    });
}
/**
 * Get notifications for company
 *
 * @remarks
 * Returns all notifications relevant for the given company.
 *
 * scope: `notifications:read`
 */
export function useNotificationsGetCompanyNotificationsSuspense(request, options) {
    const client = useGustoEmbeddedContext();
    return useSuspenseQuery({
        ...buildNotificationsGetCompanyNotificationsQuery(client, request, options),
        ...options,
    });
}
export function setNotificationsGetCompanyNotificationsData(client, queryKeyBase, data) {
    const key = queryKeyNotificationsGetCompanyNotifications(...queryKeyBase);
    return client.setQueryData(key, data);
}
export function invalidateNotificationsGetCompanyNotifications(client, queryKeyBase, filters) {
    return client.invalidateQueries({
        ...filters,
        queryKey: [
            "@gusto/embedded-api",
            "Notifications",
            "getCompanyNotifications",
            ...queryKeyBase,
        ],
    });
}
export function invalidateAllNotificationsGetCompanyNotifications(client, filters) {
    return client.invalidateQueries({
        ...filters,
        queryKey: [
            "@gusto/embedded-api",
            "Notifications",
            "getCompanyNotifications",
        ],
    });
}
//# sourceMappingURL=notificationsGetCompanyNotifications.js.map