/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { notificationsGetDetails } from "../funcs/notificationsGetDetails.js";
import { combineSignals } from "../lib/primitives.js";
import { unwrapAsync } from "../types/fp.js";
export function prefetchNotificationsGetDetails(queryClient, client$, request, options) {
    return queryClient.prefetchQuery({
        ...buildNotificationsGetDetailsQuery(client$, request, options),
    });
}
export function buildNotificationsGetDetailsQuery(client$, request, options) {
    return {
        queryKey: queryKeyNotificationsGetDetails(request.notificationUuid, {
            xGustoAPIVersion: request.xGustoAPIVersion,
        }),
        queryFn: async function notificationsGetDetailsQueryFn(ctx) {
            const sig = combineSignals(ctx.signal, options?.signal, options?.fetchOptions?.signal);
            const mergedOptions = {
                ...options?.fetchOptions,
                ...options,
                signal: sig,
            };
            return unwrapAsync(notificationsGetDetails(client$, request, mergedOptions));
        },
    };
}
export function queryKeyNotificationsGetDetails(notificationUuid, parameters) {
    return [
        "@gusto/embedded-api",
        "Notifications",
        "getDetails",
        notificationUuid,
        parameters,
    ];
}
//# sourceMappingURL=notificationsGetDetails.core.js.map