/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { useMutation, } from "@tanstack/react-query";
import { reimbursementsDeleteV1RecurringReimbursements } from "../funcs/reimbursementsDeleteV1RecurringReimbursements.js";
import { combineSignals } from "../lib/primitives.js";
import { unwrapAsync } from "../types/fp.js";
import { useGustoEmbeddedContext } from "./_context.js";
/**
 * Delete a recurring reimbursement
 *
 * @remarks
 * Delete (soft delete) a recurring reimbursement for an employee.
 *
 * scope: `reimbursements:write`
 */
export function useReimbursementsDeleteV1RecurringReimbursementsMutation(options) {
    const client = useGustoEmbeddedContext();
    return useMutation({
        ...buildReimbursementsDeleteV1RecurringReimbursementsMutation(client, options),
        ...options,
    });
}
export function mutationKeyReimbursementsDeleteV1RecurringReimbursements() {
    return [
        "@gusto/embedded-api",
        "Reimbursements",
        "deleteV1RecurringReimbursements",
    ];
}
export function buildReimbursementsDeleteV1RecurringReimbursementsMutation(client$, hookOptions) {
    return {
        mutationKey: mutationKeyReimbursementsDeleteV1RecurringReimbursements(),
        mutationFn: function reimbursementsDeleteV1RecurringReimbursementsMutationFn({ request, options, }) {
            const mergedOptions = {
                ...hookOptions,
                ...options,
                fetchOptions: {
                    ...hookOptions?.fetchOptions,
                    ...options?.fetchOptions,
                    signal: combineSignals(hookOptions?.fetchOptions?.signal, options?.fetchOptions?.signal),
                },
            };
            return unwrapAsync(reimbursementsDeleteV1RecurringReimbursements(client$, request, mergedOptions));
        },
    };
}
//# sourceMappingURL=reimbursementsDeleteV1RecurringReimbursements.js.map