/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { achTransactionsGetAll } from "../funcs/achTransactionsGetAll.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class AchTransactions extends ClientSDK {
  /**
   * Get all ACH transactions for a company
   *
   * @remarks
   * Fetches all ACH transactions for a company.
   *
   * scope: `ach_transactions:read`
   */
  async getAll(
    request: operations.GetAchTransactionsRequest,
    options?: RequestOptions,
  ): Promise<Array<components.AchTransaction>> {
    return unwrapAsync(achTransactionsGetAll(
      this,
      request,
      options,
    ));
  }
}
