/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { employeeTaxSetupGetFederalTaxes } from "../funcs/employeeTaxSetupGetFederalTaxes.js";
import { employeeTaxSetupGetStateTaxes } from "../funcs/employeeTaxSetupGetStateTaxes.js";
import { employeeTaxSetupUpdateFederalTaxes } from "../funcs/employeeTaxSetupUpdateFederalTaxes.js";
import { employeeTaxSetupUpdateStateTaxes } from "../funcs/employeeTaxSetupUpdateStateTaxes.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class EmployeeTaxSetup extends ClientSDK {
  /**
   * Get an employee's federal taxes
   *
   * @remarks
   * Get attributes relevant for an employee's federal taxes.
   *
   *  scope: `employee_federal_taxes:read`
   */
  async getFederalTaxes(
    request: operations.GetV1EmployeesEmployeeIdFederalTaxesRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1EmployeesEmployeeIdFederalTaxesResponse> {
    return unwrapAsync(employeeTaxSetupGetFederalTaxes(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an employee's federal taxes
   *
   * @remarks
   * Update attributes relevant for an employee's federal taxes.
   *
   * scope: `employee_federal_taxes:write`
   */
  async updateFederalTaxes(
    request: operations.PutV1EmployeesEmployeeIdFederalTaxesRequest,
    options?: RequestOptions,
  ): Promise<operations.PutV1EmployeesEmployeeIdFederalTaxesResponse> {
    return unwrapAsync(employeeTaxSetupUpdateFederalTaxes(
      this,
      request,
      options,
    ));
  }

  /**
   * Get an employee's state taxes
   *
   * @remarks
   * Get attributes relevant for an employee's state taxes.
   *
   * The data required to correctly calculate an employee's state taxes varies by both home and work location. This API returns information about each question that must be answered grouped by state. Mostly commonly, an employee lives and works in the same state and will only have questions for a single state. The response contains metadata about each question, the type of answer expected, and the current answer stored in Gusto for that question.
   *
   * Answers are represented by an array. Today, this array can only be empty or contain exactly one element, but is designed to allow for forward compatibility with effective-dated fields. Until effective dated answers are supported, the `valid_from` and `valid_up_to` must always be `"2010-01-01"` and `null` respectively.
   *
   * ## About filing new hire reports
   * Payroll Admins are responsible for filing a new hire report for each Employee. The `file_new_hire_report` question will only be listed if:
   * - the `employee.onboarding_status` is one of the following:
   *   - `admin_onboarding_incomplete`
   *   - `self_onboarding_awaiting_admin_review`
   * - that employee's work state requires filing a new hire report
   *
   * scope: `employee_state_taxes:read`
   */
  async getStateTaxes(
    request: operations.GetV1EmployeesEmployeeIdStateTaxesRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV1EmployeesEmployeeIdStateTaxesResponse> {
    return unwrapAsync(employeeTaxSetupGetStateTaxes(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an employee's state taxes
   *
   * @remarks
   * Update attributes relevant for an employee's state taxes.
   *
   * As described for the GET endpoint, the answers must be supplied in the effective-dated format, but currently only a single answer will be accepted - `valid_from` and `valid_up_to` must be `"2010-01-01"` and `null` respectively.
   *
   * scope: `employee_state_taxes:write`
   */
  async updateStateTaxes(
    request: operations.PutV1EmployeesEmployeeIdStateTaxesRequest,
    options?: RequestOptions,
  ): Promise<operations.PutV1EmployeesEmployeeIdStateTaxesResponse> {
    return unwrapAsync(employeeTaxSetupUpdateStateTaxes(
      this,
      request,
      options,
    ));
  }
}
