"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
const vitest_1 = require("vitest");
const index_js_1 = require("../index.js");
const index_js_2 = require("../types/index.js");
const testclient_js_1 = require("./testclient.js");
(0, vitest_1.test)("Reports Post Companies Company Uuid Reports Example", async () => {
    const gustoEmbedded = new index_js_1.GustoEmbedded({
        httpClient: (0, testclient_js_1.createTestHTTPClient)("post-companies-company_uuid-reports-Example"),
        companyAccessAuth: process.env["GUSTOEMBEDDED_COMPANY_ACCESS_AUTH"] ?? "",
    });
    const result = await gustoEmbedded.reports.create({
        companyUuid: "<id>",
        requestBody: {
            columns: [
                "employee_compensation_time_period",
                "employee_social_security_tax",
                "bank_account_account_number",
            ],
            groupings: [
                "work_address_state",
            ],
            fileType: "csv",
            startDate: new index_js_2.RFCDate("2024-01-01"),
            endDate: new index_js_2.RFCDate("2024-04-01"),
            dismissedStartDate: new index_js_2.RFCDate("2024-01-01"),
            dismissedEndDate: new index_js_2.RFCDate("2024-04-01"),
        },
    });
    (0, vitest_1.expect)(result).toBeDefined();
    (0, vitest_1.expect)(result).toEqual({
        requestUuid: "p83d0ca8-7d41-42a9-834y-7d218ef6cb20",
        companyUuid: "z83d0ca8-7d41-42a9-834y-7d218ef6cb20",
        customName: "CustomReport",
        fileType: "csv",
    });
});
(0, vitest_1.test)("Reports Post Companies Company Uuid Reports Basic", async () => {
    const gustoEmbedded = new index_js_1.GustoEmbedded({
        httpClient: (0, testclient_js_1.createTestHTTPClient)("post-companies-company_uuid-reports-Basic"),
        companyAccessAuth: process.env["GUSTOEMBEDDED_COMPANY_ACCESS_AUTH"] ?? "",
    });
    const result = await gustoEmbedded.reports.create({
        companyUuid: "<id>",
        requestBody: {
            columns: [],
            groupings: [
                "employee",
            ],
            fileType: "json",
            startDate: new index_js_2.RFCDate("2024-01-01"),
            endDate: new index_js_2.RFCDate("2024-04-01"),
            dismissedStartDate: new index_js_2.RFCDate("2024-01-01"),
            dismissedEndDate: new index_js_2.RFCDate("2024-04-01"),
        },
    });
    (0, vitest_1.expect)(result).toBeDefined();
});
(0, vitest_1.test)("Reports Post Companies Company Uuid Reports Resource", async () => {
    const gustoEmbedded = new index_js_1.GustoEmbedded({
        httpClient: (0, testclient_js_1.createTestHTTPClient)("post-companies-company_uuid-reports-Resource"),
        companyAccessAuth: process.env["GUSTOEMBEDDED_COMPANY_ACCESS_AUTH"] ?? "",
    });
    const result = await gustoEmbedded.reports.create({
        companyUuid: "<id>",
        requestBody: {
            columns: [
                "employee_taxes",
                "check_date",
            ],
            groupings: [
                "work_address",
                "payroll",
                "work_address",
            ],
            fileType: "json",
            startDate: new index_js_2.RFCDate("2024-01-01"),
            endDate: new index_js_2.RFCDate("2024-04-01"),
            dismissedStartDate: new index_js_2.RFCDate("2024-01-01"),
            dismissedEndDate: new index_js_2.RFCDate("2024-04-01"),
        },
    });
    (0, vitest_1.expect)(result).toBeDefined();
});
(0, vitest_1.test)("Reports Post Companies Company Uuid Reports Nested", async () => {
    const gustoEmbedded = new index_js_1.GustoEmbedded({
        httpClient: (0, testclient_js_1.createTestHTTPClient)("post-companies-company_uuid-reports-Nested"),
        companyAccessAuth: process.env["GUSTOEMBEDDED_COMPANY_ACCESS_AUTH"] ?? "",
    });
    const result = await gustoEmbedded.reports.create({
        companyUuid: "<id>",
        requestBody: {
            columns: [],
            groupings: [
                "work_address_state",
                "work_address",
            ],
            fileType: "csv",
            startDate: new index_js_2.RFCDate("2024-01-01"),
            endDate: new index_js_2.RFCDate("2024-04-01"),
            dismissedStartDate: new index_js_2.RFCDate("2024-01-01"),
            dismissedEndDate: new index_js_2.RFCDate("2024-04-01"),
        },
    });
    (0, vitest_1.expect)(result).toBeDefined();
});
(0, vitest_1.test)("Reports Get Reports Report Uuid Example", async () => {
    const gustoEmbedded = new index_js_1.GustoEmbedded({
        httpClient: (0, testclient_js_1.createTestHTTPClient)("get-reports-report_uuid-Example"),
        companyAccessAuth: process.env["GUSTOEMBEDDED_COMPANY_ACCESS_AUTH"] ?? "",
    });
    const result = await gustoEmbedded.reports.get({
        reportUuid: "<id>",
    });
    (0, vitest_1.expect)(result).toBeDefined();
    (0, vitest_1.expect)(result).toEqual({
        requestUuid: "p83d0ca8-7d41-42a9-834y-7d218ef6cb20",
        status: "succeeded",
        reportUrls: [
            "https://report.url.com",
        ],
    });
});
(0, vitest_1.test)("Reports Get Companies Company Uuid Report Templates Report Type Example", async () => {
    const gustoEmbedded = new index_js_1.GustoEmbedded({
        httpClient: (0, testclient_js_1.createTestHTTPClient)("get-companies-company_uuid-report-templates-report_type-Example"),
        companyAccessAuth: process.env["GUSTOEMBEDDED_COMPANY_ACCESS_AUTH"] ?? "",
    });
    const result = await gustoEmbedded.reports.getTemplate({
        companyUuid: "<id>",
        reportType: "<value>",
    });
    (0, vitest_1.expect)(result).toBeDefined();
    (0, vitest_1.expect)(result).toEqual({
        columns: [
            "regular_rate",
            "regular_hours",
            "regular_earnings",
        ],
        groupings: [
            "payroll",
            "employee",
        ],
        companyUuid: "p83d0ca8-7d41-42a9-834y-7d218ef6cb20",
        reportType: "payroll_journal",
    });
});
//# sourceMappingURL=reports.test.js.map