/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  BenefitSummary,
  BenefitSummary$inboundSchema,
} from "../components/benefitsummary.js";
import {
  HTTPMetadata,
  HTTPMetadata$inboundSchema,
} from "../components/httpmetadata.js";
import {
  VersionHeader,
  VersionHeader$outboundSchema,
} from "../components/versionheader.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV1BenefitsCompanyBenefitIdSummaryRequest = {
  /**
   * The UUID of the company benefit
   */
  companyBenefitId: string;
  /**
   * The start date for which to retrieve company benefit summary
   */
  startDate?: string | undefined;
  /**
   * The end date for which to retrieve company benefit summary. If left empty, defaults to today's date.
   */
  endDate?: string | undefined;
  /**
   * Display employee payroll item summary
   */
  detailed?: boolean | undefined;
  /**
   * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
   */
  xGustoAPIVersion?: VersionHeader | undefined;
};

export type GetV1BenefitsCompanyBenefitIdSummaryResponse = {
  httpMeta: HTTPMetadata;
  /**
   * Benefit summary response
   */
  benefitSummary?: BenefitSummary | undefined;
};

/** @internal */
export type GetV1BenefitsCompanyBenefitIdSummaryRequest$Outbound = {
  company_benefit_id: string;
  start_date?: string | undefined;
  end_date?: string | undefined;
  detailed?: boolean | undefined;
  "X-Gusto-API-Version": string;
};

/** @internal */
export const GetV1BenefitsCompanyBenefitIdSummaryRequest$outboundSchema:
  z.ZodType<
    GetV1BenefitsCompanyBenefitIdSummaryRequest$Outbound,
    z.ZodTypeDef,
    GetV1BenefitsCompanyBenefitIdSummaryRequest
  > = z.object({
    companyBenefitId: z.string(),
    startDate: z.string().optional(),
    endDate: z.string().optional(),
    detailed: z.boolean().optional(),
    xGustoAPIVersion: VersionHeader$outboundSchema.default("2025-06-15"),
  }).transform((v) => {
    return remap$(v, {
      companyBenefitId: "company_benefit_id",
      startDate: "start_date",
      endDate: "end_date",
      xGustoAPIVersion: "X-Gusto-API-Version",
    });
  });

export function getV1BenefitsCompanyBenefitIdSummaryRequestToJSON(
  getV1BenefitsCompanyBenefitIdSummaryRequest:
    GetV1BenefitsCompanyBenefitIdSummaryRequest,
): string {
  return JSON.stringify(
    GetV1BenefitsCompanyBenefitIdSummaryRequest$outboundSchema.parse(
      getV1BenefitsCompanyBenefitIdSummaryRequest,
    ),
  );
}

/** @internal */
export const GetV1BenefitsCompanyBenefitIdSummaryResponse$inboundSchema:
  z.ZodType<
    GetV1BenefitsCompanyBenefitIdSummaryResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    HttpMeta: HTTPMetadata$inboundSchema,
    "Benefit-Summary": BenefitSummary$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "Benefit-Summary": "benefitSummary",
    });
  });

export function getV1BenefitsCompanyBenefitIdSummaryResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV1BenefitsCompanyBenefitIdSummaryResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV1BenefitsCompanyBenefitIdSummaryResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV1BenefitsCompanyBenefitIdSummaryResponse' from JSON`,
  );
}
