/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  HTTPMetadata,
  HTTPMetadata$inboundSchema,
} from "../components/httpmetadata.js";
import {
  SalaryEstimate,
  SalaryEstimate$inboundSchema,
} from "../components/salaryestimate.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export const GetV1SalaryEstimatesIdHeaderXGustoAPIVersion = {
  TwoThousandAndTwentyFiveMinus06Minus15: "2025-06-15",
} as const;
/**
 * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
 */
export type GetV1SalaryEstimatesIdHeaderXGustoAPIVersion = ClosedEnum<
  typeof GetV1SalaryEstimatesIdHeaderXGustoAPIVersion
>;

export type GetV1SalaryEstimatesIdRequest = {
  /**
   * Determines the date-based API version associated with your API call. If none is provided, your application's [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
   */
  xGustoAPIVersion?: GetV1SalaryEstimatesIdHeaderXGustoAPIVersion | undefined;
  /**
   * The UUID of the salary estimate
   */
  uuid: string;
};

export type GetV1SalaryEstimatesIdResponse = {
  httpMeta: HTTPMetadata;
  /**
   * successful
   */
  salaryEstimate?: SalaryEstimate | undefined;
};

/** @internal */
export const GetV1SalaryEstimatesIdHeaderXGustoAPIVersion$outboundSchema:
  z.ZodNativeEnum<typeof GetV1SalaryEstimatesIdHeaderXGustoAPIVersion> = z
    .nativeEnum(GetV1SalaryEstimatesIdHeaderXGustoAPIVersion);

/** @internal */
export type GetV1SalaryEstimatesIdRequest$Outbound = {
  "X-Gusto-API-Version": string;
  uuid: string;
};

/** @internal */
export const GetV1SalaryEstimatesIdRequest$outboundSchema: z.ZodType<
  GetV1SalaryEstimatesIdRequest$Outbound,
  z.ZodTypeDef,
  GetV1SalaryEstimatesIdRequest
> = z.object({
  xGustoAPIVersion: GetV1SalaryEstimatesIdHeaderXGustoAPIVersion$outboundSchema
    .default("2025-06-15"),
  uuid: z.string(),
}).transform((v) => {
  return remap$(v, {
    xGustoAPIVersion: "X-Gusto-API-Version",
  });
});

export function getV1SalaryEstimatesIdRequestToJSON(
  getV1SalaryEstimatesIdRequest: GetV1SalaryEstimatesIdRequest,
): string {
  return JSON.stringify(
    GetV1SalaryEstimatesIdRequest$outboundSchema.parse(
      getV1SalaryEstimatesIdRequest,
    ),
  );
}

/** @internal */
export const GetV1SalaryEstimatesIdResponse$inboundSchema: z.ZodType<
  GetV1SalaryEstimatesIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: HTTPMetadata$inboundSchema,
  "Salary-Estimate": SalaryEstimate$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "Salary-Estimate": "salaryEstimate",
  });
});

export function getV1SalaryEstimatesIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1SalaryEstimatesIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1SalaryEstimatesIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1SalaryEstimatesIdResponse' from JSON`,
  );
}
