/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { GustoEmbeddedError } from "../models/errors/gustoembeddederror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { NotFoundErrorObject } from "../models/errors/notfounderrorobject.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  GetV1WorkAddressesWorkAddressUuidHeaderXGustoAPIVersion,
  GetV1WorkAddressesWorkAddressUuidRequest,
} from "../models/operations/getv1workaddressesworkaddressuuid.js";
import { useGustoEmbeddedContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildEmployeeAddressesRetrieveWorkAddressQuery,
  EmployeeAddressesRetrieveWorkAddressQueryData,
  prefetchEmployeeAddressesRetrieveWorkAddress,
  queryKeyEmployeeAddressesRetrieveWorkAddress,
} from "./employeeAddressesRetrieveWorkAddress.core.js";
export {
  buildEmployeeAddressesRetrieveWorkAddressQuery,
  type EmployeeAddressesRetrieveWorkAddressQueryData,
  prefetchEmployeeAddressesRetrieveWorkAddress,
  queryKeyEmployeeAddressesRetrieveWorkAddress,
};

export type EmployeeAddressesRetrieveWorkAddressQueryError =
  | NotFoundErrorObject
  | GustoEmbeddedError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get an employee work address
 *
 * @remarks
 * The work address of an employee is used for payroll tax purposes.
 *
 * scope: `employees:read`
 */
export function useEmployeeAddressesRetrieveWorkAddress(
  request: GetV1WorkAddressesWorkAddressUuidRequest,
  options?: QueryHookOptions<
    EmployeeAddressesRetrieveWorkAddressQueryData,
    EmployeeAddressesRetrieveWorkAddressQueryError
  >,
): UseQueryResult<
  EmployeeAddressesRetrieveWorkAddressQueryData,
  EmployeeAddressesRetrieveWorkAddressQueryError
> {
  const client = useGustoEmbeddedContext();
  return useQuery({
    ...buildEmployeeAddressesRetrieveWorkAddressQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get an employee work address
 *
 * @remarks
 * The work address of an employee is used for payroll tax purposes.
 *
 * scope: `employees:read`
 */
export function useEmployeeAddressesRetrieveWorkAddressSuspense(
  request: GetV1WorkAddressesWorkAddressUuidRequest,
  options?: SuspenseQueryHookOptions<
    EmployeeAddressesRetrieveWorkAddressQueryData,
    EmployeeAddressesRetrieveWorkAddressQueryError
  >,
): UseSuspenseQueryResult<
  EmployeeAddressesRetrieveWorkAddressQueryData,
  EmployeeAddressesRetrieveWorkAddressQueryError
> {
  const client = useGustoEmbeddedContext();
  return useSuspenseQuery({
    ...buildEmployeeAddressesRetrieveWorkAddressQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setEmployeeAddressesRetrieveWorkAddressData(
  client: QueryClient,
  queryKeyBase: [
    workAddressUuid: string,
    parameters: {
      xGustoAPIVersion?:
        | GetV1WorkAddressesWorkAddressUuidHeaderXGustoAPIVersion
        | undefined;
    },
  ],
  data: EmployeeAddressesRetrieveWorkAddressQueryData,
): EmployeeAddressesRetrieveWorkAddressQueryData | undefined {
  const key = queryKeyEmployeeAddressesRetrieveWorkAddress(...queryKeyBase);

  return client.setQueryData<EmployeeAddressesRetrieveWorkAddressQueryData>(
    key,
    data,
  );
}

export function invalidateEmployeeAddressesRetrieveWorkAddress(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [
      workAddressUuid: string,
      parameters: {
        xGustoAPIVersion?:
          | GetV1WorkAddressesWorkAddressUuidHeaderXGustoAPIVersion
          | undefined;
      },
    ]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@gusto/embedded-api-v2025-11-15",
      "employeeAddresses",
      "retrieveWorkAddress",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllEmployeeAddressesRetrieveWorkAddress(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@gusto/embedded-api-v2025-11-15",
      "employeeAddresses",
      "retrieveWorkAddress",
    ],
  });
}
