/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { VersionHeader } from "../models/components/versionheader.js";
import { GustoEmbeddedError } from "../models/errors/gustoembeddederror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { GetEmployeeYtdBenefitAmountsFromDifferentCompanyRequest } from "../models/operations/getemployeeytdbenefitamountsfromdifferentcompany.js";
import { useGustoEmbeddedContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildEmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyQuery,
  EmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyQueryData,
  prefetchEmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompany,
  queryKeyEmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompany,
} from "./employeeBenefitsGetYtdBenefitAmountsFromDifferentCompany.core.js";
export {
  buildEmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyQuery,
  type EmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyQueryData,
  prefetchEmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompany,
  queryKeyEmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompany,
};

export type EmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyQueryError =
  | GustoEmbeddedError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get year-to-date benefit amounts from a different company
 *
 * @remarks
 * Retrieves year-to-date benefit amounts that were contributed at a different company for the specified employee.
 * Returns benefit amounts for the requested tax year (defaults to current year if not specified).
 *
 * This endpoint only supports retrieving outside contributions for 401(k) benefits.
 *
 * scope: `employee_benefits:read`
 */
export function useEmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompany(
  request: GetEmployeeYtdBenefitAmountsFromDifferentCompanyRequest,
  options?: QueryHookOptions<
    EmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyQueryData,
    EmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyQueryError
  >,
): UseQueryResult<
  EmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyQueryData,
  EmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyQueryError
> {
  const client = useGustoEmbeddedContext();
  return useQuery({
    ...buildEmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get year-to-date benefit amounts from a different company
 *
 * @remarks
 * Retrieves year-to-date benefit amounts that were contributed at a different company for the specified employee.
 * Returns benefit amounts for the requested tax year (defaults to current year if not specified).
 *
 * This endpoint only supports retrieving outside contributions for 401(k) benefits.
 *
 * scope: `employee_benefits:read`
 */
export function useEmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanySuspense(
  request: GetEmployeeYtdBenefitAmountsFromDifferentCompanyRequest,
  options?: SuspenseQueryHookOptions<
    EmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyQueryData,
    EmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyQueryError
  >,
): UseSuspenseQueryResult<
  EmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyQueryData,
  EmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyQueryError
> {
  const client = useGustoEmbeddedContext();
  return useSuspenseQuery({
    ...buildEmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setEmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyData(
  client: QueryClient,
  queryKeyBase: [
    employeeId: string,
    parameters: {
      taxYear?: number | undefined;
      xGustoAPIVersion?: VersionHeader | undefined;
    },
  ],
  data: EmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyQueryData,
):
  | EmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyQueryData
  | undefined
{
  const key = queryKeyEmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompany(
    ...queryKeyBase,
  );

  return client.setQueryData<
    EmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompanyQueryData
  >(key, data);
}

export function invalidateEmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompany(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [
      employeeId: string,
      parameters: {
        taxYear?: number | undefined;
        xGustoAPIVersion?: VersionHeader | undefined;
      },
    ]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@gusto/embedded-api-v2025-11-15",
      "employeeBenefits",
      "getYtdBenefitAmountsFromDifferentCompany",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllEmployeeBenefitsGetYtdBenefitAmountsFromDifferentCompany(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@gusto/embedded-api-v2025-11-15",
      "employeeBenefits",
      "getYtdBenefitAmountsFromDifferentCompany",
    ],
  });
}
