/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { employeeAddressesCreateWorkAddress } from "../../funcs/employeeAddressesCreateWorkAddress.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.PostV1EmployeesEmployeeIdWorkAddressesRequest$inboundSchema,
};

export const tool$employeeAddressesCreateWorkAddress: ToolDefinition<
  typeof args
> = {
  name: "employee-addresses_create-work-address",
  description: `Create an employee work address

The work address of an employee describes when an employee began working at an associated company location.

scope: \`employees:manage\``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await employeeAddressesCreateWorkAddress(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
