/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { employeeAddressesDelete } from "../../funcs/employeeAddressesDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteV1HomeAddressesHomeAddressUuidRequest$inboundSchema,
};

export const tool$employeeAddressesDelete: ToolDefinition<typeof args> = {
  name: "employee-addresses_delete",
  description: `Delete an employee's home address

Used for deleting an employee's home address.  Cannot delete the employee's active home address.

scope: \`employees:write\``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await employeeAddressesDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
