/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { externalPayrollsUpdate } from "../../funcs/externalPayrollsUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PutV1ExternalPayrollRequest$inboundSchema,
};

export const tool$externalPayrollsUpdate: ToolDefinition<typeof args> = {
  name: "external-payrolls_update",
  description: `Update an external payroll

Update an external payroll with a list of external payroll items

scope: \`external_payrolls:write\``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await externalPayrollsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
