/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
/** @internal */
export const DetailedPaymentAccountSplit$inboundSchema = z.object({
    bank_account_uuid: z.string().optional(),
    hidden_account_number: z.string().optional(),
    name: z.string().optional(),
    priority: z.number().int().optional(),
    split_amount: z.nullable(z.number().int()).optional(),
    encrypted_account_number: z.nullable(z.string()).optional(),
}).transform((v) => {
    return remap$(v, {
        "bank_account_uuid": "bankAccountUuid",
        "hidden_account_number": "hiddenAccountNumber",
        "split_amount": "splitAmount",
        "encrypted_account_number": "encryptedAccountNumber",
    });
});
export function detailedPaymentAccountSplitFromJSON(jsonString) {
    return safeParse(jsonString, (x) => DetailedPaymentAccountSplit$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'DetailedPaymentAccountSplit' from JSON`);
}
//# sourceMappingURL=detailedpaymentaccountsplit.js.map