/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
/** @internal */
export const PaymentMethodBankAccount$inboundSchema = z.object({
    uuid: z.string(),
    name: z.string().optional(),
    hidden_account_number: z.string().optional(),
    priority: z.number().int().optional(),
    split_amount: z.nullable(z.number().int()).optional(),
}).transform((v) => {
    return remap$(v, {
        "hidden_account_number": "hiddenAccountNumber",
        "split_amount": "splitAmount",
    });
});
export function paymentMethodBankAccountFromJSON(jsonString) {
    return safeParse(jsonString, (x) => PaymentMethodBankAccount$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PaymentMethodBankAccount' from JSON`);
}
//# sourceMappingURL=paymentmethodbankaccount.js.map