/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
/** @internal */
export const PayrollCreditBlockerUnblockOptionRespondToHighRiskFraudRfiMetadata$inboundSchema = z.object({
    information_request_uuid: z.string(),
}).transform((v) => {
    return remap$(v, {
        "information_request_uuid": "informationRequestUuid",
    });
});
export function payrollCreditBlockerUnblockOptionRespondToHighRiskFraudRfiMetadataFromJSON(jsonString) {
    return safeParse(jsonString, (x) => PayrollCreditBlockerUnblockOptionRespondToHighRiskFraudRfiMetadata$inboundSchema
        .parse(JSON.parse(x)), `Failed to parse 'PayrollCreditBlockerUnblockOptionRespondToHighRiskFraudRfiMetadata' from JSON`);
}
/** @internal */
export const PayrollCreditBlockerUnblockOptionRespondToHighRiskFraudRfi$inboundSchema = z.object({
    unblock_type: z.literal("respond_to_high_risk_fraud_rfi"),
    check_date: z.string(),
    metadata: z.lazy(() => PayrollCreditBlockerUnblockOptionRespondToHighRiskFraudRfiMetadata$inboundSchema),
}).transform((v) => {
    return remap$(v, {
        "unblock_type": "unblockType",
        "check_date": "checkDate",
    });
});
export function payrollCreditBlockerUnblockOptionRespondToHighRiskFraudRfiFromJSON(jsonString) {
    return safeParse(jsonString, (x) => PayrollCreditBlockerUnblockOptionRespondToHighRiskFraudRfi$inboundSchema
        .parse(JSON.parse(x)), `Failed to parse 'PayrollCreditBlockerUnblockOptionRespondToHighRiskFraudRfi' from JSON`);
}
//# sourceMappingURL=payrollcreditblockerunblockoptionrespondtohighriskfraudrfi.js.map