/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
/** @internal */
export const PayrollCompanyTaxesType$inboundSchema = z.object({
    name: z.string().optional(),
    employer: z.boolean().optional(),
    amount: z.string().optional(),
});
export function payrollCompanyTaxesTypeFromJSON(jsonString) {
    return safeParse(jsonString, (x) => PayrollCompanyTaxesType$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PayrollCompanyTaxesType' from JSON`);
}
//# sourceMappingURL=payrollcompanytaxestype.js.map