/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { PayScheduleAssignmentDepartment$inboundSchema, } from "./payscheduleassignmentdepartment.js";
import { PayScheduleAssignmentEmployee$inboundSchema, } from "./payscheduleassignmentemployee.js";
export const Type = {
    Single: "single",
    HourlySalaried: "hourly_salaried",
    ByEmployee: "by_employee",
    ByDepartment: "by_department",
};
/** @internal */
export const Type$inboundSchema = z.nativeEnum(Type);
/** @internal */
export const PayScheduleAssignment$inboundSchema = z.object({
    type: z.nullable(Type$inboundSchema).optional(),
    hourly_pay_schedule_uuid: z.nullable(z.string()).optional(),
    salaried_pay_schedule_uuid: z.nullable(z.string()).optional(),
    default_pay_schedule_uuid: z.nullable(z.string()).optional(),
    employees: z.nullable(z.array(PayScheduleAssignmentEmployee$inboundSchema))
        .optional(),
    departments: z.nullable(z.array(PayScheduleAssignmentDepartment$inboundSchema)).optional(),
}).transform((v) => {
    return remap$(v, {
        "hourly_pay_schedule_uuid": "hourlyPayScheduleUuid",
        "salaried_pay_schedule_uuid": "salariedPayScheduleUuid",
        "default_pay_schedule_uuid": "defaultPayScheduleUuid",
    });
});
export function payScheduleAssignmentFromJSON(jsonString) {
    return safeParse(jsonString, (x) => PayScheduleAssignment$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PayScheduleAssignment' from JSON`);
}
//# sourceMappingURL=payscheduleassignment.js.map