/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { RFCDate } from "../../types/rfcdate.js";
/** @internal */
export const HomeAddress$outboundSchema = z.object({
    street1: z.string(),
    street2: z.string().optional(),
    city: z.string(),
    state: z.string(),
    zip: z.string(),
    country: z.string().default("USA"),
}).transform((v) => {
    return remap$(v, {
        street1: "street_1",
        street2: "street_2",
    });
});
export function homeAddressToJSON(homeAddress) {
    return JSON.stringify(HomeAddress$outboundSchema.parse(homeAddress));
}
/** @internal */
export const SignatoryCreateRequest$outboundSchema = z.object({
    firstName: z.string(),
    lastName: z.string(),
    title: z.string(),
    phone: z.string(),
    birthday: z.instanceof(RFCDate).transform(v => v.toString()),
    email: z.string(),
    ssn: z.string(),
    homeAddress: z.lazy(() => HomeAddress$outboundSchema),
}).transform((v) => {
    return remap$(v, {
        firstName: "first_name",
        lastName: "last_name",
        homeAddress: "home_address",
    });
});
export function signatoryCreateRequestToJSON(signatoryCreateRequest) {
    return JSON.stringify(SignatoryCreateRequest$outboundSchema.parse(signatoryCreateRequest));
}
//# sourceMappingURL=signatorycreaterequest.js.map