/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * An allowed value to answer the question
 */
export type EmployeeStateTaxInputQuestionFormatValue =
  | string
  | boolean
  | number;

export type EmployeeStateTaxInputQuestionFormatOptions = {
  /**
   * An allowed value to answer the question
   */
  value?: string | boolean | number | undefined;
  /**
   * A display label that corresponds to the answer value
   */
  label: string;
};

export type EmployeeStateTaxInputQuestionFormat = {
  /**
   * Describes the type of question - Text, Number, Select, Currency, Date
   */
  type: string;
  /**
   * For "Select" type questions, the allowed values and display labels.
   */
  options?: Array<EmployeeStateTaxInputQuestionFormatOptions> | undefined;
};

/** @internal */
export const EmployeeStateTaxInputQuestionFormatValue$inboundSchema: z.ZodType<
  EmployeeStateTaxInputQuestionFormatValue,
  z.ZodTypeDef,
  unknown
> = smartUnion([types.string(), types.boolean(), types.number()]);

export function employeeStateTaxInputQuestionFormatValueFromJSON(
  jsonString: string,
): SafeParseResult<
  EmployeeStateTaxInputQuestionFormatValue,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EmployeeStateTaxInputQuestionFormatValue$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EmployeeStateTaxInputQuestionFormatValue' from JSON`,
  );
}

/** @internal */
export const EmployeeStateTaxInputQuestionFormatOptions$inboundSchema:
  z.ZodType<EmployeeStateTaxInputQuestionFormatOptions, z.ZodTypeDef, unknown> =
    z.object({
      value: types.optional(
        smartUnion([types.string(), types.boolean(), types.number()]),
      ),
      label: types.string(),
    });

export function employeeStateTaxInputQuestionFormatOptionsFromJSON(
  jsonString: string,
): SafeParseResult<
  EmployeeStateTaxInputQuestionFormatOptions,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EmployeeStateTaxInputQuestionFormatOptions$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EmployeeStateTaxInputQuestionFormatOptions' from JSON`,
  );
}

/** @internal */
export const EmployeeStateTaxInputQuestionFormat$inboundSchema: z.ZodType<
  EmployeeStateTaxInputQuestionFormat,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: types.string(),
  options: types.optional(
    z.array(z.lazy(() =>
      EmployeeStateTaxInputQuestionFormatOptions$inboundSchema
    )),
  ),
});

export function employeeStateTaxInputQuestionFormatFromJSON(
  jsonString: string,
): SafeParseResult<EmployeeStateTaxInputQuestionFormat, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EmployeeStateTaxInputQuestionFormat$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmployeeStateTaxInputQuestionFormat' from JSON`,
  );
}
