/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const IdentityVerificationStatus = {
  Pass: "Pass",
  Fail: "Fail",
  Skipped: "Skipped",
} as const;
export type IdentityVerificationStatus = OpenEnum<
  typeof IdentityVerificationStatus
>;

export type SignatoryHomeAddress = {
  street1?: string | undefined;
  street2?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  zip?: string | undefined;
  country: string;
};

/**
 * The representation of a company's signatory
 */
export type Signatory = {
  uuid: string;
  firstName?: string | null | undefined;
  lastName?: string | null | undefined;
  title?: string | null | undefined;
  phone?: string | null | undefined;
  email?: string | undefined;
  birthday?: string | null | undefined;
  /**
   * Whether or not the signatory is also the payroll admin of the company.
   */
  isAdmin?: boolean | undefined;
  /**
   * Indicates whether the signatory has an SSN in Gusto.
   */
  hasSsn?: boolean | undefined;
  /**
   * The current version of the signatory. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field.
   */
  version?: string | undefined;
  /**
   * |   |   |
   *
   * @remarks
   * |---|---|
   * |__Status__| __Description__ |
   * | Pass | Signatory can sign all forms |
   * | Fail | Signatory cannot sign forms |
   * | Skipped | Signatory cannot sign Form 8655 until the form is manually uploaded as wet-signed |
   * | null | Identity verification process has not been completed |
   */
  identityVerificationStatus?: IdentityVerificationStatus | null | undefined;
  homeAddress?: SignatoryHomeAddress | null | undefined;
};

/** @internal */
export const IdentityVerificationStatus$inboundSchema: z.ZodType<
  IdentityVerificationStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(IdentityVerificationStatus);

/** @internal */
export const SignatoryHomeAddress$inboundSchema: z.ZodType<
  SignatoryHomeAddress,
  z.ZodTypeDef,
  unknown
> = z.object({
  street_1: types.optional(types.string()),
  street_2: types.optional(types.string()),
  city: types.optional(types.string()),
  state: types.optional(types.string()),
  zip: types.optional(types.string()),
  country: types.string().default("USA"),
}).transform((v) => {
  return remap$(v, {
    "street_1": "street1",
    "street_2": "street2",
  });
});

export function signatoryHomeAddressFromJSON(
  jsonString: string,
): SafeParseResult<SignatoryHomeAddress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SignatoryHomeAddress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SignatoryHomeAddress' from JSON`,
  );
}

/** @internal */
export const Signatory$inboundSchema: z.ZodType<
  Signatory,
  z.ZodTypeDef,
  unknown
> = z.object({
  uuid: types.string(),
  first_name: z.nullable(types.string()).optional(),
  last_name: z.nullable(types.string()).optional(),
  title: z.nullable(types.string()).optional(),
  phone: z.nullable(types.string()).optional(),
  email: types.optional(types.string()),
  birthday: z.nullable(types.string()).optional(),
  is_admin: types.optional(types.boolean()),
  has_ssn: types.optional(types.boolean()),
  version: types.optional(types.string()),
  identity_verification_status: z.nullable(
    IdentityVerificationStatus$inboundSchema,
  ).optional(),
  home_address: z.nullable(z.lazy(() => SignatoryHomeAddress$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "first_name": "firstName",
    "last_name": "lastName",
    "is_admin": "isAdmin",
    "has_ssn": "hasSsn",
    "identity_verification_status": "identityVerificationStatus",
    "home_address": "homeAddress",
  });
});

export function signatoryFromJSON(
  jsonString: string,
): SafeParseResult<Signatory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Signatory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Signatory' from JSON`,
  );
}
