/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The response from requesting a webhook subscription verification token.
 */
export type WebhookVerificationTokenResponse = {
  /**
   * A message indicating the verification token has been sent.
   */
  message?: string | undefined;
};

/** @internal */
export const WebhookVerificationTokenResponse$inboundSchema: z.ZodType<
  WebhookVerificationTokenResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
});

export function webhookVerificationTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<WebhookVerificationTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookVerificationTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookVerificationTokenResponse' from JSON`,
  );
}
