/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ContractorPayment$inboundSchema, } from "../components/contractorpayment.js";
import { HTTPMetadata$inboundSchema, } from "../components/httpmetadata.js";
import { VersionHeader$outboundSchema, } from "../components/versionheader.js";
/** @internal */
export const GetV1ContractorPaymentsContractorPaymentUuidFundRequest$outboundSchema = z.object({
    contractorPaymentUuid: z.string(),
    xGustoAPIVersion: VersionHeader$outboundSchema.default("2026-02-01"),
}).transform((v) => {
    return remap$(v, {
        contractorPaymentUuid: "contractor_payment_uuid",
        xGustoAPIVersion: "X-Gusto-API-Version",
    });
});
export function getV1ContractorPaymentsContractorPaymentUuidFundRequestToJSON(getV1ContractorPaymentsContractorPaymentUuidFundRequest) {
    return JSON.stringify(GetV1ContractorPaymentsContractorPaymentUuidFundRequest$outboundSchema
        .parse(getV1ContractorPaymentsContractorPaymentUuidFundRequest));
}
/** @internal */
export const GetV1ContractorPaymentsContractorPaymentUuidFundResponse$inboundSchema = z.object({
    HttpMeta: HTTPMetadata$inboundSchema,
    "Contractor-Payment": ContractorPayment$inboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        "HttpMeta": "httpMeta",
        "Contractor-Payment": "contractorPayment",
    });
});
export function getV1ContractorPaymentsContractorPaymentUuidFundResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetV1ContractorPaymentsContractorPaymentUuidFundResponse$inboundSchema
        .parse(JSON.parse(x)), `Failed to parse 'GetV1ContractorPaymentsContractorPaymentUuidFundResponse' from JSON`);
}
//# sourceMappingURL=getv1contractorpaymentscontractorpaymentuuidfund.js.map