/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ContractorPaymentMethod$inboundSchema, } from "../components/contractorpaymentmethod.js";
import { HTTPMetadata$inboundSchema, } from "../components/httpmetadata.js";
import { VersionHeader$outboundSchema, } from "../components/versionheader.js";
/** @internal */
export const GetV1ContractorsContractorUuidPaymentMethodRequest$outboundSchema = z.object({
    contractorUuid: z.string(),
    xGustoAPIVersion: VersionHeader$outboundSchema.default("2026-02-01"),
}).transform((v) => {
    return remap$(v, {
        contractorUuid: "contractor_uuid",
        xGustoAPIVersion: "X-Gusto-API-Version",
    });
});
export function getV1ContractorsContractorUuidPaymentMethodRequestToJSON(getV1ContractorsContractorUuidPaymentMethodRequest) {
    return JSON.stringify(GetV1ContractorsContractorUuidPaymentMethodRequest$outboundSchema.parse(getV1ContractorsContractorUuidPaymentMethodRequest));
}
/** @internal */
export const GetV1ContractorsContractorUuidPaymentMethodResponse$inboundSchema = z.object({
    HttpMeta: HTTPMetadata$inboundSchema,
    "Contractor-Payment-Method": ContractorPaymentMethod$inboundSchema
        .optional(),
}).transform((v) => {
    return remap$(v, {
        "HttpMeta": "httpMeta",
        "Contractor-Payment-Method": "contractorPaymentMethod",
    });
});
export function getV1ContractorsContractorUuidPaymentMethodResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetV1ContractorsContractorUuidPaymentMethodResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetV1ContractorsContractorUuidPaymentMethodResponse' from JSON`);
}
//# sourceMappingURL=getv1contractorscontractoruuidpaymentmethod.js.map