/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { HTTPMetadata$inboundSchema, } from "../components/httpmetadata.js";
import { VersionHeader$outboundSchema, } from "../components/versionheader.js";
/** @internal */
export const GetV1WebhookSubscriptionVerificationTokenUuidSecurity$outboundSchema = z.object({
    systemAccessAuth: z.string(),
}).transform((v) => {
    return remap$(v, {
        systemAccessAuth: "SystemAccessAuth",
    });
});
export function getV1WebhookSubscriptionVerificationTokenUuidSecurityToJSON(getV1WebhookSubscriptionVerificationTokenUuidSecurity) {
    return JSON.stringify(GetV1WebhookSubscriptionVerificationTokenUuidSecurity$outboundSchema.parse(getV1WebhookSubscriptionVerificationTokenUuidSecurity));
}
/** @internal */
export const GetV1WebhookSubscriptionVerificationTokenUuidRequest$outboundSchema = z.object({
    webhookSubscriptionUuid: z.string(),
    xGustoAPIVersion: VersionHeader$outboundSchema.default("2026-02-01"),
}).transform((v) => {
    return remap$(v, {
        webhookSubscriptionUuid: "webhook_subscription_uuid",
        xGustoAPIVersion: "X-Gusto-API-Version",
    });
});
export function getV1WebhookSubscriptionVerificationTokenUuidRequestToJSON(getV1WebhookSubscriptionVerificationTokenUuidRequest) {
    return JSON.stringify(GetV1WebhookSubscriptionVerificationTokenUuidRequest$outboundSchema.parse(getV1WebhookSubscriptionVerificationTokenUuidRequest));
}
/** @internal */
export const GetV1WebhookSubscriptionVerificationTokenUuidResponse$inboundSchema = z.object({
    HttpMeta: HTTPMetadata$inboundSchema,
}).transform((v) => {
    return remap$(v, {
        "HttpMeta": "httpMeta",
    });
});
export function getV1WebhookSubscriptionVerificationTokenUuidResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetV1WebhookSubscriptionVerificationTokenUuidResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetV1WebhookSubscriptionVerificationTokenUuidResponse' from JSON`);
}
//# sourceMappingURL=getv1webhooksubscriptionverificationtokenuuid.js.map