/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { EmployeePaymentDetail$inboundSchema, } from "../components/employeepaymentdetail.js";
import { HTTPMetadata$inboundSchema, } from "../components/httpmetadata.js";
import { VersionHeader$outboundSchema, } from "../components/versionheader.js";
/** @internal */
export const GetV1CompaniesCompanyIdEmployeesPaymentDetailsRequest$outboundSchema = z.object({
    companyId: z.string(),
    employeeUuid: z.string().optional(),
    payrollUuid: z.string().optional(),
    page: z.number().int().optional(),
    per: z.number().int().optional(),
    xGustoAPIVersion: VersionHeader$outboundSchema.default("2026-02-01"),
}).transform((v) => {
    return remap$(v, {
        companyId: "company_id",
        employeeUuid: "employee_uuid",
        payrollUuid: "payroll_uuid",
        xGustoAPIVersion: "X-Gusto-API-Version",
    });
});
export function getV1CompaniesCompanyIdEmployeesPaymentDetailsRequestToJSON(getV1CompaniesCompanyIdEmployeesPaymentDetailsRequest) {
    return JSON.stringify(GetV1CompaniesCompanyIdEmployeesPaymentDetailsRequest$outboundSchema.parse(getV1CompaniesCompanyIdEmployeesPaymentDetailsRequest));
}
/** @internal */
export const GetV1CompaniesCompanyIdEmployeesPaymentDetailsResponse$inboundSchema = z.object({
    HttpMeta: HTTPMetadata$inboundSchema,
    EmployeePaymentDetailsList: z.array(EmployeePaymentDetail$inboundSchema)
        .optional(),
}).transform((v) => {
    return remap$(v, {
        "HttpMeta": "httpMeta",
        "EmployeePaymentDetailsList": "employeePaymentDetailsList",
    });
});
export function getV1CompaniesCompanyIdEmployeesPaymentDetailsResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetV1CompaniesCompanyIdEmployeesPaymentDetailsResponse$inboundSchema
        .parse(JSON.parse(x)), `Failed to parse 'GetV1CompaniesCompanyIdEmployeesPaymentDetailsResponse' from JSON`);
}
//# sourceMappingURL=getv1companiescompanyidemployeespaymentdetails.js.map