/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { HTTPMetadata$inboundSchema, } from "../components/httpmetadata.js";
import { PayrollCheck$inboundSchema, } from "../components/payrollcheck.js";
import { VersionHeader$outboundSchema, } from "../components/versionheader.js";
/**
 * The type of check stock being printed. Check the "Types of check stock" section in this [link](https://support.gusto.com/article/999877761000000/Pay-your-team-by-check) for more info on check types
 */
export const PrintingFormat = {
    Top: "top",
    Bottom: "bottom",
};
/** @internal */
export const PrintingFormat$outboundSchema = z.nativeEnum(PrintingFormat);
/** @internal */
export const PostV1PayrollsPayrollUuidGeneratedDocumentsPrintablePayrollChecksRequestBody$outboundSchema = z.object({
    printingFormat: PrintingFormat$outboundSchema,
    startingCheckNumber: z.number().int().optional(),
}).transform((v) => {
    return remap$(v, {
        printingFormat: "printing_format",
        startingCheckNumber: "starting_check_number",
    });
});
export function postV1PayrollsPayrollUuidGeneratedDocumentsPrintablePayrollChecksRequestBodyToJSON(postV1PayrollsPayrollUuidGeneratedDocumentsPrintablePayrollChecksRequestBody) {
    return JSON.stringify(PostV1PayrollsPayrollUuidGeneratedDocumentsPrintablePayrollChecksRequestBody$outboundSchema
        .parse(postV1PayrollsPayrollUuidGeneratedDocumentsPrintablePayrollChecksRequestBody));
}
/** @internal */
export const PostV1PayrollsPayrollUuidGeneratedDocumentsPrintablePayrollChecksRequest$outboundSchema = z.object({
    payrollUuid: z.string(),
    xGustoAPIVersion: VersionHeader$outboundSchema.default("2026-02-01"),
    requestBody: z.lazy(() => PostV1PayrollsPayrollUuidGeneratedDocumentsPrintablePayrollChecksRequestBody$outboundSchema),
}).transform((v) => {
    return remap$(v, {
        payrollUuid: "payroll_uuid",
        xGustoAPIVersion: "X-Gusto-API-Version",
        requestBody: "RequestBody",
    });
});
export function postV1PayrollsPayrollUuidGeneratedDocumentsPrintablePayrollChecksRequestToJSON(postV1PayrollsPayrollUuidGeneratedDocumentsPrintablePayrollChecksRequest) {
    return JSON.stringify(PostV1PayrollsPayrollUuidGeneratedDocumentsPrintablePayrollChecksRequest$outboundSchema
        .parse(postV1PayrollsPayrollUuidGeneratedDocumentsPrintablePayrollChecksRequest));
}
/** @internal */
export const PostV1PayrollsPayrollUuidGeneratedDocumentsPrintablePayrollChecksResponse$inboundSchema = z.object({
    HttpMeta: HTTPMetadata$inboundSchema,
    "Payroll-Check": PayrollCheck$inboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        "HttpMeta": "httpMeta",
        "Payroll-Check": "payrollCheck",
    });
});
export function postV1PayrollsPayrollUuidGeneratedDocumentsPrintablePayrollChecksResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => PostV1PayrollsPayrollUuidGeneratedDocumentsPrintablePayrollChecksResponse$inboundSchema
        .parse(JSON.parse(x)), `Failed to parse 'PostV1PayrollsPayrollUuidGeneratedDocumentsPrintablePayrollChecksResponse' from JSON`);
}
//# sourceMappingURL=postv1payrollspayrolluuidgenerateddocumentsprintablepayrollchecks.js.map