/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { GustoEmbeddedError } from "../models/errors/gustoembeddederror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { NotFoundErrorObject } from "../models/errors/notfounderrorobject.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  GetV1BenefitsBenefitsIdRequirementsHeaderXGustoAPIVersion,
  GetV1BenefitsBenefitsIdRequirementsRequest,
} from "../models/operations/getv1benefitsbenefitsidrequirements.js";
import { useGustoEmbeddedContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildCompanyBenefitsGetRequirementsQuery,
  CompanyBenefitsGetRequirementsQueryData,
  prefetchCompanyBenefitsGetRequirements,
  queryKeyCompanyBenefitsGetRequirements,
} from "./companyBenefitsGetRequirements.core.js";
export {
  buildCompanyBenefitsGetRequirementsQuery,
  type CompanyBenefitsGetRequirementsQueryData,
  prefetchCompanyBenefitsGetRequirements,
  queryKeyCompanyBenefitsGetRequirements,
};

export type CompanyBenefitsGetRequirementsQueryError =
  | NotFoundErrorObject
  | GustoEmbeddedError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get benefit fields requirements by benefit type
 *
 * @remarks
 * Returns the field requirements for a given benefit type.
 *
 * scope: `benefits:read`
 */
export function useCompanyBenefitsGetRequirements(
  request: GetV1BenefitsBenefitsIdRequirementsRequest,
  options?: QueryHookOptions<
    CompanyBenefitsGetRequirementsQueryData,
    CompanyBenefitsGetRequirementsQueryError
  >,
): UseQueryResult<
  CompanyBenefitsGetRequirementsQueryData,
  CompanyBenefitsGetRequirementsQueryError
> {
  const client = useGustoEmbeddedContext();
  return useQuery({
    ...buildCompanyBenefitsGetRequirementsQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get benefit fields requirements by benefit type
 *
 * @remarks
 * Returns the field requirements for a given benefit type.
 *
 * scope: `benefits:read`
 */
export function useCompanyBenefitsGetRequirementsSuspense(
  request: GetV1BenefitsBenefitsIdRequirementsRequest,
  options?: SuspenseQueryHookOptions<
    CompanyBenefitsGetRequirementsQueryData,
    CompanyBenefitsGetRequirementsQueryError
  >,
): UseSuspenseQueryResult<
  CompanyBenefitsGetRequirementsQueryData,
  CompanyBenefitsGetRequirementsQueryError
> {
  const client = useGustoEmbeddedContext();
  return useSuspenseQuery({
    ...buildCompanyBenefitsGetRequirementsQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setCompanyBenefitsGetRequirementsData(
  client: QueryClient,
  queryKeyBase: [
    benefitId: string,
    parameters: {
      xGustoAPIVersion?:
        | GetV1BenefitsBenefitsIdRequirementsHeaderXGustoAPIVersion
        | undefined;
    },
  ],
  data: CompanyBenefitsGetRequirementsQueryData,
): CompanyBenefitsGetRequirementsQueryData | undefined {
  const key = queryKeyCompanyBenefitsGetRequirements(...queryKeyBase);

  return client.setQueryData<CompanyBenefitsGetRequirementsQueryData>(
    key,
    data,
  );
}

export function invalidateCompanyBenefitsGetRequirements(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [
      benefitId: string,
      parameters: {
        xGustoAPIVersion?:
          | GetV1BenefitsBenefitsIdRequirementsHeaderXGustoAPIVersion
          | undefined;
      },
    ]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@gusto/embedded-api",
      "companyBenefits",
      "getRequirements",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllCompanyBenefitsGetRequirements(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gusto/embedded-api", "companyBenefits", "getRequirements"],
  });
}
