/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GustoEmbeddedCore } from "../core.js";
import { timeOffPoliciesDeactivate } from "../funcs/timeOffPoliciesDeactivate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { GustoEmbeddedError } from "../models/errors/gustoembeddederror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { NotFoundErrorObject } from "../models/errors/notfounderrorobject.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { UnprocessableEntityErrorObject } from "../models/errors/unprocessableentityerrorobject.js";
import {
  PutV1TimeOffPoliciesTimeOffPolicyUuidDeactivateRequest,
  PutV1TimeOffPoliciesTimeOffPolicyUuidDeactivateResponse,
} from "../models/operations/putv1timeoffpoliciestimeoffpolicyuuiddeactivate.js";
import { unwrapAsync } from "../types/fp.js";
import { useGustoEmbeddedContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type TimeOffPoliciesDeactivateMutationVariables = {
  request: PutV1TimeOffPoliciesTimeOffPolicyUuidDeactivateRequest;
  options?: RequestOptions;
};

export type TimeOffPoliciesDeactivateMutationData =
  PutV1TimeOffPoliciesTimeOffPolicyUuidDeactivateResponse;

export type TimeOffPoliciesDeactivateMutationError =
  | NotFoundErrorObject
  | UnprocessableEntityErrorObject
  | GustoEmbeddedError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Deactivate a time off policy
 *
 * @remarks
 * Deactivate a time off policy
 *
 * scope: `time_off_policies:write`
 */
export function useTimeOffPoliciesDeactivateMutation(
  options?: MutationHookOptions<
    TimeOffPoliciesDeactivateMutationData,
    TimeOffPoliciesDeactivateMutationError,
    TimeOffPoliciesDeactivateMutationVariables
  >,
): UseMutationResult<
  TimeOffPoliciesDeactivateMutationData,
  TimeOffPoliciesDeactivateMutationError,
  TimeOffPoliciesDeactivateMutationVariables
> {
  const client = useGustoEmbeddedContext();
  return useMutation({
    ...buildTimeOffPoliciesDeactivateMutation(client, options),
    ...options,
  });
}

export function mutationKeyTimeOffPoliciesDeactivate(): MutationKey {
  return ["@gusto/embedded-api", "timeOffPolicies", "deactivate"];
}

export function buildTimeOffPoliciesDeactivateMutation(
  client$: GustoEmbeddedCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: TimeOffPoliciesDeactivateMutationVariables,
  ) => Promise<TimeOffPoliciesDeactivateMutationData>;
} {
  return {
    mutationKey: mutationKeyTimeOffPoliciesDeactivate(),
    mutationFn: function timeOffPoliciesDeactivateMutationFn({
      request,
      options,
    }): Promise<TimeOffPoliciesDeactivateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(timeOffPoliciesDeactivate(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
