/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { VersionHeader } from "../models/components/versionheader.js";
import { GetV1BenefitsCompanyBenefitIdSummaryRequest } from "../models/operations/getv1benefitscompanybenefitidsummary.js";
import { useGustoEmbeddedContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildCompanyBenefitsGetSummaryQuery,
  CompanyBenefitsGetSummaryQueryData,
  prefetchCompanyBenefitsGetSummary,
  queryKeyCompanyBenefitsGetSummary,
} from "./companyBenefitsGetSummary.core.js";
export {
  buildCompanyBenefitsGetSummaryQuery,
  type CompanyBenefitsGetSummaryQueryData,
  prefetchCompanyBenefitsGetSummary,
  queryKeyCompanyBenefitsGetSummary,
};

/**
 * Get company benefit summary by company benefit id.
 *
 * @remarks
 * Returns summary benefit data for the requested company benefit id.
 *
 * Benefits containing PHI are only visible to applications with the `company_benefits:read:phi` scope.
 *
 * scope: `company_benefits:read`
 */
export function useCompanyBenefitsGetSummary(
  request: GetV1BenefitsCompanyBenefitIdSummaryRequest,
  options?: QueryHookOptions<CompanyBenefitsGetSummaryQueryData>,
): UseQueryResult<CompanyBenefitsGetSummaryQueryData, Error> {
  const client = useGustoEmbeddedContext();
  return useQuery({
    ...buildCompanyBenefitsGetSummaryQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get company benefit summary by company benefit id.
 *
 * @remarks
 * Returns summary benefit data for the requested company benefit id.
 *
 * Benefits containing PHI are only visible to applications with the `company_benefits:read:phi` scope.
 *
 * scope: `company_benefits:read`
 */
export function useCompanyBenefitsGetSummarySuspense(
  request: GetV1BenefitsCompanyBenefitIdSummaryRequest,
  options?: SuspenseQueryHookOptions<CompanyBenefitsGetSummaryQueryData>,
): UseSuspenseQueryResult<CompanyBenefitsGetSummaryQueryData, Error> {
  const client = useGustoEmbeddedContext();
  return useSuspenseQuery({
    ...buildCompanyBenefitsGetSummaryQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setCompanyBenefitsGetSummaryData(
  client: QueryClient,
  queryKeyBase: [
    companyBenefitId: string,
    parameters: {
      startDate?: string | undefined;
      endDate?: string | undefined;
      detailed?: boolean | undefined;
      xGustoAPIVersion?: VersionHeader | undefined;
    },
  ],
  data: CompanyBenefitsGetSummaryQueryData,
): CompanyBenefitsGetSummaryQueryData | undefined {
  const key = queryKeyCompanyBenefitsGetSummary(...queryKeyBase);

  return client.setQueryData<CompanyBenefitsGetSummaryQueryData>(key, data);
}

export function invalidateCompanyBenefitsGetSummary(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [
      companyBenefitId: string,
      parameters: {
        startDate?: string | undefined;
        endDate?: string | undefined;
        detailed?: boolean | undefined;
        xGustoAPIVersion?: VersionHeader | undefined;
      },
    ]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@gusto/embedded-api",
      "companyBenefits",
      "getSummary",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllCompanyBenefitsGetSummary(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gusto/embedded-api", "companyBenefits", "getSummary"],
  });
}
