/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { GustoEmbeddedCore } from "../core.js";
import { companiesFormsList } from "../funcs/companiesFormsList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useGustoEmbeddedContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type CompaniesFormsListQueryData = Array<components.Form>;

/**
 * Get all company forms
 *
 * @remarks
 * Get a list of all company's forms
 *
 * scope: `company_forms:read`
 */
export function useCompaniesFormsList(
  request: operations.GetV1CompanyFormsRequest,
  options?: QueryHookOptions<CompaniesFormsListQueryData>,
): UseQueryResult<CompaniesFormsListQueryData, Error> {
  const client = useGustoEmbeddedContext();
  return useQuery({
    ...buildCompaniesFormsListQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get all company forms
 *
 * @remarks
 * Get a list of all company's forms
 *
 * scope: `company_forms:read`
 */
export function useCompaniesFormsListSuspense(
  request: operations.GetV1CompanyFormsRequest,
  options?: SuspenseQueryHookOptions<CompaniesFormsListQueryData>,
): UseSuspenseQueryResult<CompaniesFormsListQueryData, Error> {
  const client = useGustoEmbeddedContext();
  return useSuspenseQuery({
    ...buildCompaniesFormsListQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function prefetchCompaniesFormsList(
  queryClient: QueryClient,
  client$: GustoEmbeddedCore,
  request: operations.GetV1CompanyFormsRequest,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildCompaniesFormsListQuery(
      client$,
      request,
    ),
  });
}

export function setCompaniesFormsListData(
  client: QueryClient,
  queryKeyBase: [
    companyId: string,
    parameters: { xGustoAPIVersion?: components.VersionHeader | undefined },
  ],
  data: CompaniesFormsListQueryData,
): CompaniesFormsListQueryData | undefined {
  const key = queryKeyCompaniesFormsList(...queryKeyBase);

  return client.setQueryData<CompaniesFormsListQueryData>(key, data);
}

export function invalidateCompaniesFormsList(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [
      companyId: string,
      parameters: { xGustoAPIVersion?: components.VersionHeader | undefined },
    ]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gusto/embedded-api", "forms", "list", ...queryKeyBase],
  });
}

export function invalidateAllCompaniesFormsList(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gusto/embedded-api", "forms", "list"],
  });
}

export function buildCompaniesFormsListQuery(
  client$: GustoEmbeddedCore,
  request: operations.GetV1CompanyFormsRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<CompaniesFormsListQueryData>;
} {
  return {
    queryKey: queryKeyCompaniesFormsList(request.companyId, {
      xGustoAPIVersion: request.xGustoAPIVersion,
    }),
    queryFn: async function companiesFormsListQueryFn(
      ctx,
    ): Promise<CompaniesFormsListQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(companiesFormsList(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyCompaniesFormsList(
  companyId: string,
  parameters: { xGustoAPIVersion?: components.VersionHeader | undefined },
): QueryKey {
  return ["@gusto/embedded-api", "forms", "list", companyId, parameters];
}
