/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { GustoEmbeddedCore } from "../core.js";
import { contractorsList } from "../funcs/contractorsList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { ContractorsSortBy } from "../models/components/contractorssortby.js";
import { VersionHeader } from "../models/components/versionheader.js";
import {
  GetV1CompaniesCompanyUuidContractorsRequest,
  GetV1CompaniesCompanyUuidContractorsResponse,
} from "../models/operations/getv1companiescompanyuuidcontractors.js";
import { unwrapAsync } from "../types/fp.js";
export type ContractorsListQueryData =
  GetV1CompaniesCompanyUuidContractorsResponse;

export function prefetchContractorsList(
  queryClient: QueryClient,
  client$: GustoEmbeddedCore,
  request: GetV1CompaniesCompanyUuidContractorsRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildContractorsListQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildContractorsListQuery(
  client$: GustoEmbeddedCore,
  request: GetV1CompaniesCompanyUuidContractorsRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<ContractorsListQueryData>;
} {
  return {
    queryKey: queryKeyContractorsList(request.companyUuid, {
      page: request.page,
      per: request.per,
      searchTerm: request.searchTerm,
      sortBy: request.sortBy,
      xGustoAPIVersion: request.xGustoAPIVersion,
    }),
    queryFn: async function contractorsListQueryFn(
      ctx,
    ): Promise<ContractorsListQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(contractorsList(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyContractorsList(
  companyUuid: string,
  parameters: {
    page?: number | undefined;
    per?: number | undefined;
    searchTerm?: string | undefined;
    sortBy?: ContractorsSortBy | undefined;
    xGustoAPIVersion?: VersionHeader | undefined;
  },
): QueryKey {
  return [
    "@gusto/embedded-api",
    "Contractors",
    "list",
    companyUuid,
    parameters,
  ];
}
