/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GustoEmbeddedCore } from "../core.js";
import { employeeBenefitsCreateYtdAmountsFromDifferentCompany } from "../funcs/employeeBenefitsCreateYtdAmountsFromDifferentCompany.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useGustoEmbeddedContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type EmployeeBenefitsCreateYtdAmountsFromDifferentCompanyMutationVariables =
  {
    request:
      operations.PostEmployeeYtdBenefitAmountsFromDifferentCompanyRequest;
    options?: RequestOptions;
  };

export type EmployeeBenefitsCreateYtdAmountsFromDifferentCompanyMutationData =
  void;

/**
 * Create year-to-date benefit amounts from a different company
 *
 * @remarks
 * Year-to-date benefit amounts from a different company represents the amount of money added to an employee's plan during a current year, made outside of the current contribution when they were employed at a different company.
 *
 * This endpoint only supports passing outside contributions for 401(k) benefits.
 *
 * scope: `employee_benefits:write`
 */
export function useEmployeeBenefitsCreateYtdAmountsFromDifferentCompanyMutation(
  options?: MutationHookOptions<
    EmployeeBenefitsCreateYtdAmountsFromDifferentCompanyMutationData,
    Error,
    EmployeeBenefitsCreateYtdAmountsFromDifferentCompanyMutationVariables
  >,
): UseMutationResult<
  EmployeeBenefitsCreateYtdAmountsFromDifferentCompanyMutationData,
  Error,
  EmployeeBenefitsCreateYtdAmountsFromDifferentCompanyMutationVariables
> {
  const client = useGustoEmbeddedContext();
  return useMutation({
    ...buildEmployeeBenefitsCreateYtdAmountsFromDifferentCompanyMutation(
      client,
      options,
    ),
    ...options,
  });
}

export function mutationKeyEmployeeBenefitsCreateYtdAmountsFromDifferentCompany(): MutationKey {
  return [
    "@gusto/embedded-api",
    "employeeBenefits",
    "createYtdAmountsFromDifferentCompany",
  ];
}

export function buildEmployeeBenefitsCreateYtdAmountsFromDifferentCompanyMutation(
  client$: GustoEmbeddedCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables:
      EmployeeBenefitsCreateYtdAmountsFromDifferentCompanyMutationVariables,
  ) => Promise<
    EmployeeBenefitsCreateYtdAmountsFromDifferentCompanyMutationData
  >;
} {
  return {
    mutationKey:
      mutationKeyEmployeeBenefitsCreateYtdAmountsFromDifferentCompany(),
    mutationFn:
      function employeeBenefitsCreateYtdAmountsFromDifferentCompanyMutationFn({
        request,
        options,
      }): Promise<
        EmployeeBenefitsCreateYtdAmountsFromDifferentCompanyMutationData
      > {
        const mergedOptions = {
          ...hookOptions,
          ...options,
          fetchOptions: {
            ...hookOptions?.fetchOptions,
            ...options?.fetchOptions,
            signal: combineSignals(
              hookOptions?.fetchOptions?.signal,
              options?.fetchOptions?.signal,
            ),
          },
        };
        return unwrapAsync(employeeBenefitsCreateYtdAmountsFromDifferentCompany(
          client$,
          request,
          mergedOptions,
        ));
      },
  };
}
