name: Publish
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write
'on':
  push:
    branches:
    - main
    paths:
    - gusto_embedded/.speakeasy/gen.lock
    - gusto_embedded_v_2025_11_15/.speakeasy/gen.lock
    - gusto_embedded_v_2026_06_15/.speakeasy/gen.lock
  workflow_dispatch: {}
jobs:
  publish-gusto-embedded:
    uses: Gusto/sdk-generation-action/.github/workflows/sdk-publish.yaml@main
    with:
      target: gusto-embedded
      runs-on: '{"group": "gusto-ubuntu-default"}'
    secrets:
      github_access_token: "${{ secrets.GITHUB_TOKEN }}"
      npm_token: "${{ secrets.NPM_TOKEN }}"
      speakeasy_api_key: "${{ secrets.SPEAKEASY_API_KEY }}"
  publish-gusto-embedded-v2025-11-15:
    uses: Gusto/sdk-generation-action/.github/workflows/sdk-publish.yaml@main
    with:
      target: gusto-embedded-v2025-11-15
      runs-on: '{"group": "gusto-ubuntu-default"}'
    secrets:
      github_access_token: "${{ secrets.GITHUB_TOKEN }}"
      npm_token: "${{ secrets.NPM_TOKEN }}"
      speakeasy_api_key: "${{ secrets.SPEAKEASY_API_KEY }}"
  publish-gusto-embedded-v2026-06-15:
    uses: Gusto/sdk-generation-action/.github/workflows/sdk-publish.yaml@main
    with:
      target: gusto-embedded-v2026-06-15
      runs-on: '{"group": "gusto-ubuntu-default"}'
    secrets:
      github_access_token: "${{ secrets.GITHUB_TOKEN }}"
      npm_token: "${{ secrets.NPM_TOKEN }}"
      speakeasy_api_key: "${{ secrets.SPEAKEASY_API_KEY }}"
