workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    GustoEmbedded-OAS:
        inputs:
            - location: https://raw.githubusercontent.com/Gusto/Gusto-Partner-API/refs/heads/main/generated/embedded/api.v2024-04-01.embedded.yaml
              authHeader: Authorization
              authSecret: $openapi_doc_auth_token
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/gusto/ruby-sdk/gusto-embedded-oas
targets:
    gusto-embedded:
        target: typescript
        source: GustoEmbedded-OAS
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/gusto/ruby-sdk/gusto-embedded-oas-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
